// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// The `mutate` write surface CONTRACT: one typed method per allowlisted /v1
// write op, `<op>(data: <Op>Data): Promise<<Op>Response>`. Regenerate with:
//   pnpm --filter @saturation/sdk generate:mutate
//
// This interface is the forcing function: when the OpenAPI document (and thus
// the generated `types.gen.ts` request/response types) changes, every
// `satisfies WriteSurface` implementation must update to match or fail `tsc`.
//
// 25 write operations.

import type {
  BudgetUpdateLineData,
  BudgetUpdateLineResponse,
  BudgetUpdatePhaseData,
  BudgetUpdatePhaseResponse,
  BudgetUpsertLinePhaseDataData,
  BudgetUpsertLinePhaseDataResponse,
  DocumentsUpdateData,
  DocumentsUpdateResponse,
  LibraryUpdateCurrencyTemplateData,
  LibraryUpdateCurrencyTemplateResponse,
  LibraryUpdateCustomUnitData,
  LibraryUpdateCustomUnitResponse,
  LibraryUpdateFringeTagTemplateData,
  LibraryUpdateFringeTagTemplateResponse,
  LibraryUpdateFringeTemplateData,
  LibraryUpdateFringeTemplateResponse,
  LibraryUpdateGlobalTemplateData,
  LibraryUpdateGlobalTemplateResponse,
  LibraryUpdateProjectCurrencyData,
  LibraryUpdateProjectCurrencyResponse,
  LibraryUpdateProjectFringeData,
  LibraryUpdateProjectFringeResponse,
  LibraryUpdateProjectFringeTagData,
  LibraryUpdateProjectFringeTagResponse,
  LibraryUpdateProjectGlobalData,
  LibraryUpdateProjectGlobalResponse,
  LibraryUpdateProjectIncentiveData,
  LibraryUpdateProjectIncentiveResponse,
  LibraryUpdateRatePackData,
  LibraryUpdateRatePackItemData,
  LibraryUpdateRatePackItemResponse,
  LibraryUpdateRatePackResponse,
  LibraryUpdateTagData,
  LibraryUpdateTagResponse,
  MasterDataUpdateCommentData,
  MasterDataUpdateCommentResponse,
  MasterDataUpdateContactData,
  MasterDataUpdateContactResponse,
  MasterDataUpdateProjectData,
  MasterDataUpdateProjectResponse,
  MasterDataUpdateSpaceData,
  MasterDataUpdateSpaceResponse,
  PurchaseOrdersUpdateData,
  PurchaseOrdersUpdateItemData,
  PurchaseOrdersUpdateItemResponse,
  PurchaseOrdersUpdateResponse,
  TransactionsItemsUpdateData,
  TransactionsItemsUpdateResponse,
  TransactionsUpdateData,
  TransactionsUpdateResponse,
} from '../generated/types.gen.js';

/**
 * The typed write surface over the gated /v1 API. Each method takes the
 * generated hey-api options envelope (`{ body, path, query, headers? }`) for its
 * op and resolves the unwrapped success payload (the created/updated resource).
 */
export interface WriteSurface {
  /** Update a budget line (`PATCH /projects/{projectId}/budget/lines/{lineId}`). */
  budgetUpdateLine(data: BudgetUpdateLineData): Promise<BudgetUpdateLineResponse>;
  /** Update a budget phase (`PATCH /projects/{projectId}/budget/phases/{phaseId}`). */
  budgetUpdatePhase(data: BudgetUpdatePhaseData): Promise<BudgetUpdatePhaseResponse>;
  /** Upsert one editable line phase-data entry (`PUT /projects/{projectId}/budget/lines/{lineId}/phase-data/{phaseId}`). */
  budgetUpsertLinePhaseData(data: BudgetUpsertLinePhaseDataData): Promise<BudgetUpsertLinePhaseDataResponse>;
  /** Rename / move / re-describe a document (`PATCH /documents/{documentId}`). */
  documentsUpdate(data: DocumentsUpdateData): Promise<DocumentsUpdateResponse>;
  /** Update a workspace currency template (`PATCH /library/currencies/{currencyId}`). */
  libraryUpdateCurrencyTemplate(data: LibraryUpdateCurrencyTemplateData): Promise<LibraryUpdateCurrencyTemplateResponse>;
  /** Update a workspace custom unit (`PATCH /library/units/custom/{unitId}`). */
  libraryUpdateCustomUnit(data: LibraryUpdateCustomUnitData): Promise<LibraryUpdateCustomUnitResponse>;
  /** Update a workspace fringe-tag template (`PATCH /library/fringe-tags/{fringeTagId}`). */
  libraryUpdateFringeTagTemplate(data: LibraryUpdateFringeTagTemplateData): Promise<LibraryUpdateFringeTagTemplateResponse>;
  /** Update a workspace fringe template (`PATCH /library/fringes/{fringeId}`). */
  libraryUpdateFringeTemplate(data: LibraryUpdateFringeTemplateData): Promise<LibraryUpdateFringeTemplateResponse>;
  /** Update a workspace global template (`PATCH /library/globals/{globalId}`). */
  libraryUpdateGlobalTemplate(data: LibraryUpdateGlobalTemplateData): Promise<LibraryUpdateGlobalTemplateResponse>;
  /** Update a project currency copy (`PATCH /projects/{projectId}/library/currencies/{currencyId}`). */
  libraryUpdateProjectCurrency(data: LibraryUpdateProjectCurrencyData): Promise<LibraryUpdateProjectCurrencyResponse>;
  /** Update a project fringe copy (`PATCH /projects/{projectId}/library/fringes/{fringeId}`). */
  libraryUpdateProjectFringe(data: LibraryUpdateProjectFringeData): Promise<LibraryUpdateProjectFringeResponse>;
  /** Update a project fringe-tag copy (`PATCH /projects/{projectId}/library/fringe-tags/{fringeTagId}`). */
  libraryUpdateProjectFringeTag(data: LibraryUpdateProjectFringeTagData): Promise<LibraryUpdateProjectFringeTagResponse>;
  /** Update a project global copy (`PATCH /projects/{projectId}/library/globals/{globalId}`). */
  libraryUpdateProjectGlobal(data: LibraryUpdateProjectGlobalData): Promise<LibraryUpdateProjectGlobalResponse>;
  /** Update a project incentive (`PATCH /projects/{projectId}/library/incentives/{incentiveId}`). */
  libraryUpdateProjectIncentive(data: LibraryUpdateProjectIncentiveData): Promise<LibraryUpdateProjectIncentiveResponse>;
  /** Update an owned rate pack (`PATCH /library/rates/{packId}`). */
  libraryUpdateRatePack(data: LibraryUpdateRatePackData): Promise<LibraryUpdateRatePackResponse>;
  /** Update a pack item (`PATCH /library/rates/{packId}/items/{itemId}`). */
  libraryUpdateRatePackItem(data: LibraryUpdateRatePackItemData): Promise<LibraryUpdateRatePackItemResponse>;
  /** Update a workspace tag (`PATCH /library/tags/{tagId}`). */
  libraryUpdateTag(data: LibraryUpdateTagData): Promise<LibraryUpdateTagResponse>;
  /** Update a comment (`PATCH /comments/{commentId}`). */
  masterDataUpdateComment(data: MasterDataUpdateCommentData): Promise<MasterDataUpdateCommentResponse>;
  /** Update a contact (`PATCH /contacts/{contactId}`). */
  masterDataUpdateContact(data: MasterDataUpdateContactData): Promise<MasterDataUpdateContactResponse>;
  /** Update a project (`PATCH /projects/{slugOrId}`). */
  masterDataUpdateProject(data: MasterDataUpdateProjectData): Promise<MasterDataUpdateProjectResponse>;
  /** Update a space (`PATCH /spaces/{spaceId}`). */
  masterDataUpdateSpace(data: MasterDataUpdateSpaceData): Promise<MasterDataUpdateSpaceResponse>;
  /** Update a purchase order (`PATCH /purchase-orders/{purchaseOrderId}`). */
  purchaseOrdersUpdate(data: PurchaseOrdersUpdateData): Promise<PurchaseOrdersUpdateResponse>;
  /** Update a purchase order item (`PATCH /purchase-orders/{purchaseOrderId}/items/{itemId}`). */
  purchaseOrdersUpdateItem(data: PurchaseOrdersUpdateItemData): Promise<PurchaseOrdersUpdateItemResponse>;
  /** Update a transaction item (`PATCH /transactions/{txId}/items/{itemId}`). */
  transactionsItemsUpdate(data: TransactionsItemsUpdateData): Promise<TransactionsItemsUpdateResponse>;
  /** Update a transaction (`PATCH /transactions/{txId}`). */
  transactionsUpdate(data: TransactionsUpdateData): Promise<TransactionsUpdateResponse>;
}
