// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// The `mutate` write surface CONTRACT: one typed method per allowlisted /v1
// write op, `<op>(data: <Op>Data): Promise<<Op>Response>`. Regenerate with:
//   pnpm --filter @saturation/sdk generate:mutate
//
// This interface is the forcing function: when the OpenAPI document (and thus
// the generated `types.gen.ts` request/response types) changes, every
// `satisfies WriteSurface` implementation must update to match or fail `tsc`.
//
// 60 write operations.

import type {
  BudgetCreateLineData,
  BudgetCreateLineResponse,
  BudgetCreateLinesBatchData,
  BudgetCreateLinesBatchResponse,
  BudgetCreatePhaseData,
  BudgetCreatePhaseResponse,
  BudgetUpdateLineData,
  BudgetUpdateLineResponse,
  BudgetUpdatePhaseData,
  BudgetUpdatePhaseResponse,
  BudgetUpsertLinePhaseDataBatchData,
  BudgetUpsertLinePhaseDataBatchResponse,
  BudgetUpsertLinePhaseDataData,
  BudgetUpsertLinePhaseDataResponse,
  DocumentsAssignData,
  DocumentsAssignResponse,
  DocumentsDropData,
  DocumentsDropResponse,
  DocumentsUpdateData,
  DocumentsUpdateResponse,
  LibraryAddProjectCurrencyData,
  LibraryAddProjectCurrencyResponse,
  LibraryAddProjectFringeData,
  LibraryAddProjectFringeResponse,
  LibraryAddProjectFringeTagData,
  LibraryAddProjectFringeTagResponse,
  LibraryAddProjectGlobalData,
  LibraryAddProjectGlobalResponse,
  LibraryAddProjectIncentiveData,
  LibraryAddProjectIncentiveResponse,
  LibraryAddProjectTagData,
  LibraryAddProjectTagResponse,
  LibraryAddRatePackData,
  LibraryAddRatePackResponse,
  LibraryCreateCurrencyTemplateData,
  LibraryCreateCurrencyTemplateResponse,
  LibraryCreateCustomUnitData,
  LibraryCreateCustomUnitResponse,
  LibraryCreateFringeTagTemplateData,
  LibraryCreateFringeTagTemplateResponse,
  LibraryCreateFringeTemplateData,
  LibraryCreateFringeTemplateResponse,
  LibraryCreateGlobalTemplateData,
  LibraryCreateGlobalTemplateResponse,
  LibraryCreateRatePackData,
  LibraryCreateRatePackItemData,
  LibraryCreateRatePackItemResponse,
  LibraryCreateRatePackResponse,
  LibraryCreateTagData,
  LibraryCreateTagResponse,
  LibraryEnableIncentivePackData,
  LibraryEnableIncentivePackResponse,
  LibraryEnableRatePackData,
  LibraryEnableRatePackResponse,
  LibraryUpdateCurrencyTemplateData,
  LibraryUpdateCurrencyTemplateResponse,
  LibraryUpdateCustomUnitData,
  LibraryUpdateCustomUnitResponse,
  LibraryUpdateFringeTagTemplateData,
  LibraryUpdateFringeTagTemplateResponse,
  LibraryUpdateFringeTemplateData,
  LibraryUpdateFringeTemplateResponse,
  LibraryUpdateGlobalTemplateData,
  LibraryUpdateGlobalTemplateResponse,
  LibraryUpdateProjectCurrencyData,
  LibraryUpdateProjectCurrencyResponse,
  LibraryUpdateProjectFringeData,
  LibraryUpdateProjectFringeResponse,
  LibraryUpdateProjectFringeTagData,
  LibraryUpdateProjectFringeTagResponse,
  LibraryUpdateProjectGlobalData,
  LibraryUpdateProjectGlobalResponse,
  LibraryUpdateProjectIncentiveData,
  LibraryUpdateProjectIncentiveResponse,
  LibraryUpdateRatePackData,
  LibraryUpdateRatePackItemData,
  LibraryUpdateRatePackItemResponse,
  LibraryUpdateRatePackResponse,
  LibraryUpdateTagData,
  LibraryUpdateTagResponse,
  MasterDataCreateCommentData,
  MasterDataCreateCommentResponse,
  MasterDataCreateContactData,
  MasterDataCreateContactResponse,
  MasterDataCreateProjectData,
  MasterDataCreateProjectResponse,
  MasterDataCreateSpaceData,
  MasterDataCreateSpaceResponse,
  MasterDataUpdateCommentData,
  MasterDataUpdateCommentResponse,
  MasterDataUpdateContactData,
  MasterDataUpdateContactResponse,
  MasterDataUpdateProjectData,
  MasterDataUpdateProjectResponse,
  MasterDataUpdateSpaceData,
  MasterDataUpdateSpaceResponse,
  PurchaseOrdersCreateData,
  PurchaseOrdersCreateItemData,
  PurchaseOrdersCreateItemResponse,
  PurchaseOrdersCreateResponse,
  PurchaseOrdersLinkData,
  PurchaseOrdersLinkResponse,
  PurchaseOrdersUpdateData,
  PurchaseOrdersUpdateItemData,
  PurchaseOrdersUpdateItemResponse,
  PurchaseOrdersUpdateResponse,
  TransactionsBatchCreateData,
  TransactionsBatchCreateResponse,
  TransactionsCreateData,
  TransactionsCreateResponse,
  TransactionsItemsCreateData,
  TransactionsItemsCreateResponse,
  TransactionsItemsUpdateData,
  TransactionsItemsUpdateResponse,
  TransactionsUpdateData,
  TransactionsUpdateResponse,
  WebhooksCreateData,
  WebhooksCreateResponse,
  WebhooksUpdateData,
  WebhooksUpdateResponse,
} from '../generated/types.gen.js';

/**
 * The typed write surface over the gated /v1 API. Each method takes the
 * generated hey-api options envelope (`{ body, path, query, headers? }`) for its
 * op and resolves the unwrapped success payload (the created/updated resource).
 */
export interface WriteSurface {
  /** Create a budget line with optional phase data (`POST /projects/{projectId}/budget/lines`). */
  budgetCreateLine(data: BudgetCreateLineData): Promise<BudgetCreateLineResponse>;
  /** Create budget lines in one all-or-nothing batch (`POST /projects/{projectId}/budget/lines/batch`). */
  budgetCreateLinesBatch(data: BudgetCreateLinesBatchData): Promise<BudgetCreateLinesBatchResponse>;
  /** Create a budget phase (`POST /projects/{projectId}/budget/phases`). */
  budgetCreatePhase(data: BudgetCreatePhaseData): Promise<BudgetCreatePhaseResponse>;
  /** Update a budget line (`PATCH /projects/{projectId}/budget/lines/{lineId}`). */
  budgetUpdateLine(data: BudgetUpdateLineData): Promise<BudgetUpdateLineResponse>;
  /** Update a budget phase (`PATCH /projects/{projectId}/budget/phases/{phaseId}`). */
  budgetUpdatePhase(data: BudgetUpdatePhaseData): Promise<BudgetUpdatePhaseResponse>;
  /** Upsert one editable line phase-data entry (`PUT /projects/{projectId}/budget/lines/{lineId}/phase-data/{phaseId}`). */
  budgetUpsertLinePhaseData(data: BudgetUpsertLinePhaseDataData): Promise<BudgetUpsertLinePhaseDataResponse>;
  /** Upsert editable line phase data in one all-or-nothing batch (`POST /projects/{projectId}/budget/lines/phase-data/batch`). */
  budgetUpsertLinePhaseDataBatch(data: BudgetUpsertLinePhaseDataBatchData): Promise<BudgetUpsertLinePhaseDataBatchResponse>;
  /** Assign a document to a typed target (`POST /documents/{documentId}/assign`). */
  documentsAssign(data: DocumentsAssignData): Promise<DocumentsAssignResponse>;
  /** Drop a document (optionally assign atomically) (`POST /documents`). */
  documentsDrop(data: DocumentsDropData): Promise<DocumentsDropResponse>;
  /** Rename / move / re-describe a document (`PATCH /documents/{documentId}`). */
  documentsUpdate(data: DocumentsUpdateData): Promise<DocumentsUpdateResponse>;
  /** Copy a workspace currency into the project (`POST /projects/{projectId}/library/currencies/add`). */
  libraryAddProjectCurrency(data: LibraryAddProjectCurrencyData): Promise<LibraryAddProjectCurrencyResponse>;
  /** Copy a workspace fringe into the project (`POST /projects/{projectId}/library/fringes/add`). */
  libraryAddProjectFringe(data: LibraryAddProjectFringeData): Promise<LibraryAddProjectFringeResponse>;
  /** Copy a workspace fringe-tag into the project (`POST /projects/{projectId}/library/fringe-tags/add`). */
  libraryAddProjectFringeTag(data: LibraryAddProjectFringeTagData): Promise<LibraryAddProjectFringeTagResponse>;
  /** Copy a workspace global into the project (`POST /projects/{projectId}/library/globals/add`). */
  libraryAddProjectGlobal(data: LibraryAddProjectGlobalData): Promise<LibraryAddProjectGlobalResponse>;
  /** Add an incentive program into the project (`POST /projects/{projectId}/library/incentives/add`). */
  libraryAddProjectIncentive(data: LibraryAddProjectIncentiveData): Promise<LibraryAddProjectIncentiveResponse>;
  /** Add a workspace tag to the project (`POST /projects/{projectId}/library/tags/{tagId}/add`). */
  libraryAddProjectTag(data: LibraryAddProjectTagData): Promise<LibraryAddProjectTagResponse>;
  /** Add a rate pack into the project (`POST /projects/{projectId}/library/rates/{packId}/add`). */
  libraryAddRatePack(data: LibraryAddRatePackData): Promise<LibraryAddRatePackResponse>;
  /** Create a workspace currency template (`POST /library/currencies`). */
  libraryCreateCurrencyTemplate(data: LibraryCreateCurrencyTemplateData): Promise<LibraryCreateCurrencyTemplateResponse>;
  /** Create a workspace custom unit (`POST /library/units/custom`). */
  libraryCreateCustomUnit(data: LibraryCreateCustomUnitData): Promise<LibraryCreateCustomUnitResponse>;
  /** Create a workspace fringe-tag template (`POST /library/fringe-tags`). */
  libraryCreateFringeTagTemplate(data: LibraryCreateFringeTagTemplateData): Promise<LibraryCreateFringeTagTemplateResponse>;
  /** Create a workspace fringe template (`POST /library/fringes`). */
  libraryCreateFringeTemplate(data: LibraryCreateFringeTemplateData): Promise<LibraryCreateFringeTemplateResponse>;
  /** Create a workspace global template (`POST /library/globals`). */
  libraryCreateGlobalTemplate(data: LibraryCreateGlobalTemplateData): Promise<LibraryCreateGlobalTemplateResponse>;
  /** Author a PRIVATE workspace-owned rate pack (`POST /library/rates`). */
  libraryCreateRatePack(data: LibraryCreateRatePackData): Promise<LibraryCreateRatePackResponse>;
  /** Add an item to an owned pack (`POST /library/rates/{packId}/items`). */
  libraryCreateRatePackItem(data: LibraryCreateRatePackItemData): Promise<LibraryCreateRatePackItemResponse>;
  /** Create a workspace tag (`POST /library/tags`). */
  libraryCreateTag(data: LibraryCreateTagData): Promise<LibraryCreateTagResponse>;
  /** Enable an incentive pack for the workspace (`POST /library/incentives/{packId}/enable`). */
  libraryEnableIncentivePack(data: LibraryEnableIncentivePackData): Promise<LibraryEnableIncentivePackResponse>;
  /** Enable a rate pack for the workspace (`POST /library/rates/{packId}/enable`). */
  libraryEnableRatePack(data: LibraryEnableRatePackData): Promise<LibraryEnableRatePackResponse>;
  /** Update a workspace currency template (`PATCH /library/currencies/{currencyId}`). */
  libraryUpdateCurrencyTemplate(data: LibraryUpdateCurrencyTemplateData): Promise<LibraryUpdateCurrencyTemplateResponse>;
  /** Update a workspace custom unit (`PATCH /library/units/custom/{unitId}`). */
  libraryUpdateCustomUnit(data: LibraryUpdateCustomUnitData): Promise<LibraryUpdateCustomUnitResponse>;
  /** Update a workspace fringe-tag template (`PATCH /library/fringe-tags/{fringeTagId}`). */
  libraryUpdateFringeTagTemplate(data: LibraryUpdateFringeTagTemplateData): Promise<LibraryUpdateFringeTagTemplateResponse>;
  /** Update a workspace fringe template (`PATCH /library/fringes/{fringeId}`). */
  libraryUpdateFringeTemplate(data: LibraryUpdateFringeTemplateData): Promise<LibraryUpdateFringeTemplateResponse>;
  /** Update a workspace global template (`PATCH /library/globals/{globalId}`). */
  libraryUpdateGlobalTemplate(data: LibraryUpdateGlobalTemplateData): Promise<LibraryUpdateGlobalTemplateResponse>;
  /** Update a project currency copy (`PATCH /projects/{projectId}/library/currencies/{currencyId}`). */
  libraryUpdateProjectCurrency(data: LibraryUpdateProjectCurrencyData): Promise<LibraryUpdateProjectCurrencyResponse>;
  /** Update a project fringe copy (`PATCH /projects/{projectId}/library/fringes/{fringeId}`). */
  libraryUpdateProjectFringe(data: LibraryUpdateProjectFringeData): Promise<LibraryUpdateProjectFringeResponse>;
  /** Update a project fringe-tag copy (`PATCH /projects/{projectId}/library/fringe-tags/{fringeTagId}`). */
  libraryUpdateProjectFringeTag(data: LibraryUpdateProjectFringeTagData): Promise<LibraryUpdateProjectFringeTagResponse>;
  /** Update a project global copy (`PATCH /projects/{projectId}/library/globals/{globalId}`). */
  libraryUpdateProjectGlobal(data: LibraryUpdateProjectGlobalData): Promise<LibraryUpdateProjectGlobalResponse>;
  /** Update a project incentive (`PATCH /projects/{projectId}/library/incentives/{incentiveId}`). */
  libraryUpdateProjectIncentive(data: LibraryUpdateProjectIncentiveData): Promise<LibraryUpdateProjectIncentiveResponse>;
  /** Update an owned rate pack (`PATCH /library/rates/{packId}`). */
  libraryUpdateRatePack(data: LibraryUpdateRatePackData): Promise<LibraryUpdateRatePackResponse>;
  /** Update a pack item (`PATCH /library/rates/{packId}/items/{itemId}`). */
  libraryUpdateRatePackItem(data: LibraryUpdateRatePackItemData): Promise<LibraryUpdateRatePackItemResponse>;
  /** Update a workspace tag (`PATCH /library/tags/{tagId}`). */
  libraryUpdateTag(data: LibraryUpdateTagData): Promise<LibraryUpdateTagResponse>;
  /** Create a comment (`POST /comments`). */
  masterDataCreateComment(data: MasterDataCreateCommentData): Promise<MasterDataCreateCommentResponse>;
  /** Create a contact (`POST /contacts`). */
  masterDataCreateContact(data: MasterDataCreateContactData): Promise<MasterDataCreateContactResponse>;
  /** Create a project (`POST /projects`). */
  masterDataCreateProject(data: MasterDataCreateProjectData): Promise<MasterDataCreateProjectResponse>;
  /** Create a space (`POST /spaces`). */
  masterDataCreateSpace(data: MasterDataCreateSpaceData): Promise<MasterDataCreateSpaceResponse>;
  /** Update a comment (`PATCH /comments/{commentId}`). */
  masterDataUpdateComment(data: MasterDataUpdateCommentData): Promise<MasterDataUpdateCommentResponse>;
  /** Update a contact (`PATCH /contacts/{contactId}`). */
  masterDataUpdateContact(data: MasterDataUpdateContactData): Promise<MasterDataUpdateContactResponse>;
  /** Update a project (`PATCH /projects/{slugOrId}`). */
  masterDataUpdateProject(data: MasterDataUpdateProjectData): Promise<MasterDataUpdateProjectResponse>;
  /** Update a space (`PATCH /spaces/{spaceId}`). */
  masterDataUpdateSpace(data: MasterDataUpdateSpaceData): Promise<MasterDataUpdateSpaceResponse>;
  /** Create a purchase order (`POST /purchase-orders`). */
  purchaseOrdersCreate(data: PurchaseOrdersCreateData): Promise<PurchaseOrdersCreateResponse>;
  /** Add a purchase order item (`POST /purchase-orders/{purchaseOrderId}/items`). */
  purchaseOrdersCreateItem(data: PurchaseOrdersCreateItemData): Promise<PurchaseOrdersCreateItemResponse>;
  /** Link a transaction to a purchase order (`POST /purchase-orders/{purchaseOrderId}/link`). */
  purchaseOrdersLink(data: PurchaseOrdersLinkData): Promise<PurchaseOrdersLinkResponse>;
  /** Update a purchase order (`PATCH /purchase-orders/{purchaseOrderId}`). */
  purchaseOrdersUpdate(data: PurchaseOrdersUpdateData): Promise<PurchaseOrdersUpdateResponse>;
  /** Update a purchase order item (`PATCH /purchase-orders/{purchaseOrderId}/items/{itemId}`). */
  purchaseOrdersUpdateItem(data: PurchaseOrdersUpdateItemData): Promise<PurchaseOrdersUpdateItemResponse>;
  /** Bulk journal import (`POST /transactions/batch`). */
  transactionsBatchCreate(data: TransactionsBatchCreateData): Promise<TransactionsBatchCreateResponse>;
  /** Create a journal transaction (`POST /transactions`). */
  transactionsCreate(data: TransactionsCreateData): Promise<TransactionsCreateResponse>;
  /** Add a transaction item (`POST /transactions/{txId}/items`). */
  transactionsItemsCreate(data: TransactionsItemsCreateData): Promise<TransactionsItemsCreateResponse>;
  /** Update a transaction item (`PATCH /transactions/{txId}/items/{itemId}`). */
  transactionsItemsUpdate(data: TransactionsItemsUpdateData): Promise<TransactionsItemsUpdateResponse>;
  /** Update a transaction (`PATCH /transactions/{txId}`). */
  transactionsUpdate(data: TransactionsUpdateData): Promise<TransactionsUpdateResponse>;
  /** Create a webhook subscription (`POST /webhooks`). */
  webhooksCreate(data: WebhooksCreateData): Promise<WebhooksCreateResponse>;
  /** Update a webhook subscription (`PATCH /webhooks/{webhookId}`). */
  webhooksUpdate(data: WebhooksUpdateData): Promise<WebhooksUpdateResponse>;
}
