// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// `createBridgeWriteSurface` is a {@link WriteSurface} implementation. Every
// operation forwards its typed `{ path, body, query }` to
// {@link WriteBridge.mutate}. Typing lives in each method's signature.
// Regenerate with:  pnpm --filter @saturation/sdk generate:mutate
//
// 91 write operations.

import type {
  BudgetCreateLineData,
  BudgetCreateLineResponse,
  BudgetCreateLinesBulkData,
  BudgetCreateLinesBulkResponse,
  BudgetCreatePhaseData,
  BudgetCreatePhaseResponse,
  BudgetDeleteLineData,
  BudgetDeleteLineResponse,
  BudgetDeletePhaseData,
  BudgetDeletePhaseResponse,
  BudgetUpdateLineData,
  BudgetUpdateLineResponse,
  BudgetUpdatePhaseData,
  BudgetUpdatePhaseResponse,
  BudgetUpsertLinePhaseDataBulkData,
  BudgetUpsertLinePhaseDataBulkResponse,
  BudgetUpsertLinePhaseDataData,
  BudgetUpsertLinePhaseDataResponse,
  DocumentsDeleteData,
  DocumentsDeleteLinkData,
  DocumentsDeleteLinkResponse,
  DocumentsDeleteResponse,
  DocumentsPutLinkData,
  DocumentsPutLinkResponse,
  DocumentsUpdateData,
  DocumentsUpdateResponse,
  LibraryAddProjectCurrencyData,
  LibraryAddProjectCurrencyResponse,
  LibraryAddProjectFringeData,
  LibraryAddProjectFringeGroupData,
  LibraryAddProjectFringeGroupResponse,
  LibraryAddProjectFringeResponse,
  LibraryAddProjectGlobalData,
  LibraryAddProjectGlobalResponse,
  LibraryAddProjectIncentiveData,
  LibraryAddProjectIncentiveResponse,
  LibraryAddRatePackData,
  LibraryAddRatePackResponse,
  LibraryCreateCurrencyData,
  LibraryCreateCurrencyResponse,
  LibraryCreateFringeData,
  LibraryCreateFringeGroupData,
  LibraryCreateFringeGroupResponse,
  LibraryCreateFringeResponse,
  LibraryCreateGlobalData,
  LibraryCreateGlobalResponse,
  LibraryCreateRatePackData,
  LibraryCreateRatePackItemData,
  LibraryCreateRatePackItemResponse,
  LibraryCreateRatePackResponse,
  LibraryCreateTagData,
  LibraryCreateTagResponse,
  LibraryCreateUnitData,
  LibraryCreateUnitResponse,
  LibraryDeleteCurrencyData,
  LibraryDeleteCurrencyResponse,
  LibraryDeleteFringeData,
  LibraryDeleteFringeGroupData,
  LibraryDeleteFringeGroupResponse,
  LibraryDeleteFringeResponse,
  LibraryDeleteGlobalData,
  LibraryDeleteGlobalResponse,
  LibraryDeleteProjectCurrencyData,
  LibraryDeleteProjectCurrencyResponse,
  LibraryDeleteProjectFringeData,
  LibraryDeleteProjectFringeGroupData,
  LibraryDeleteProjectFringeGroupResponse,
  LibraryDeleteProjectFringeResponse,
  LibraryDeleteProjectGlobalData,
  LibraryDeleteProjectGlobalResponse,
  LibraryDeleteProjectIncentiveData,
  LibraryDeleteProjectIncentiveResponse,
  LibraryDeleteRatePackData,
  LibraryDeleteRatePackItemData,
  LibraryDeleteRatePackItemResponse,
  LibraryDeleteRatePackResponse,
  LibraryDeleteTagData,
  LibraryDeleteTagResponse,
  LibraryDeleteUnitData,
  LibraryDeleteUnitResponse,
  LibraryDisableIncentivePackData,
  LibraryDisableIncentivePackResponse,
  LibraryDisableRatePackData,
  LibraryDisableRatePackResponse,
  LibraryEnableIncentivePackData,
  LibraryEnableIncentivePackResponse,
  LibraryEnableRatePackData,
  LibraryEnableRatePackResponse,
  LibraryRemoveRatePackData,
  LibraryRemoveRatePackResponse,
  LibraryUpdateCurrencyData,
  LibraryUpdateCurrencyResponse,
  LibraryUpdateFringeData,
  LibraryUpdateFringeGroupData,
  LibraryUpdateFringeGroupResponse,
  LibraryUpdateFringeResponse,
  LibraryUpdateGlobalData,
  LibraryUpdateGlobalResponse,
  LibraryUpdateProjectCurrencyData,
  LibraryUpdateProjectCurrencyResponse,
  LibraryUpdateProjectFringeData,
  LibraryUpdateProjectFringeGroupData,
  LibraryUpdateProjectFringeGroupResponse,
  LibraryUpdateProjectFringeResponse,
  LibraryUpdateProjectGlobalData,
  LibraryUpdateProjectGlobalResponse,
  LibraryUpdateProjectIncentiveData,
  LibraryUpdateProjectIncentiveResponse,
  LibraryUpdateRatePackData,
  LibraryUpdateRatePackItemData,
  LibraryUpdateRatePackItemResponse,
  LibraryUpdateRatePackResponse,
  LibraryUpdateTagData,
  LibraryUpdateTagResponse,
  LibraryUpdateUnitData,
  LibraryUpdateUnitResponse,
  MasterDataCreateCommentData,
  MasterDataCreateCommentResponse,
  MasterDataCreateContactData,
  MasterDataCreateContactResponse,
  MasterDataCreateProjectData,
  MasterDataCreateProjectResponse,
  MasterDataCreateSpaceData,
  MasterDataCreateSpaceResponse,
  MasterDataDeleteCommentData,
  MasterDataDeleteCommentResponse,
  MasterDataDeleteContactData,
  MasterDataDeleteContactResponse,
  MasterDataDeleteSpaceData,
  MasterDataDeleteSpaceResponse,
  MasterDataUpdateCommentData,
  MasterDataUpdateCommentResponse,
  MasterDataUpdateContactData,
  MasterDataUpdateContactResponse,
  MasterDataUpdateProjectData,
  MasterDataUpdateProjectResponse,
  MasterDataUpdateSpaceData,
  MasterDataUpdateSpaceResponse,
  PurchaseOrdersCancelSubmissionData,
  PurchaseOrdersCancelSubmissionResponse,
  PurchaseOrdersCreateData,
  PurchaseOrdersCreateItemData,
  PurchaseOrdersCreateItemResponse,
  PurchaseOrdersCreateResponse,
  PurchaseOrdersDeleteData,
  PurchaseOrdersDeleteItemData,
  PurchaseOrdersDeleteItemResponse,
  PurchaseOrdersDeleteResponse,
  PurchaseOrdersDeleteTransactionData,
  PurchaseOrdersDeleteTransactionResponse,
  PurchaseOrdersMarkPaidData,
  PurchaseOrdersMarkPaidResponse,
  PurchaseOrdersPutTransactionData,
  PurchaseOrdersPutTransactionResponse,
  PurchaseOrdersUpdateData,
  PurchaseOrdersUpdateItemData,
  PurchaseOrdersUpdateItemResponse,
  PurchaseOrdersUpdateResponse,
  PurchaseOrdersVoidData,
  PurchaseOrdersVoidResponse,
  TransactionsBulkCreateData,
  TransactionsBulkCreateResponse,
  TransactionsCreateData,
  TransactionsCreateResponse,
  TransactionsDeleteData,
  TransactionsDeleteResponse,
  TransactionsItemsCreateData,
  TransactionsItemsCreateResponse,
  TransactionsItemsDeleteData,
  TransactionsItemsDeleteResponse,
  TransactionsItemsUpdateData,
  TransactionsItemsUpdateResponse,
  TransactionsUpdateData,
  TransactionsUpdateResponse,
  WebhooksCreateData,
  WebhooksCreateResponse,
  WebhooksDeleteData,
  WebhooksDeleteResponse,
  WebhooksSendTestDeliveryData,
  WebhooksSendTestDeliveryResponse,
  WebhooksUpdateData,
  WebhooksUpdateResponse,
} from '../generated/types.gen.js';
import type { WriteSurface } from './write-surface.interface.gen.js';

/** Per-op call arguments forwarded to the dispatcher. */
export interface WriteBridgeArgs {
  path?: Record<string, unknown>;
  body?: unknown;
  query?: Record<string, unknown>;
  /** Request headers (the `Idempotency-Key` channel for keyed creates). */
  headers?: Record<string, string>;
}

/**
 * The minimal generic dispatcher the bridge surface delegates to.
 * {@link MutateClient} satisfies this interface.
 */
export interface WriteBridge {
  mutate(op: string, args: WriteBridgeArgs): Promise<unknown>;
  /**
   * Optional meta-aware dispatch: also surfaces whether the /v1 route answered
   * from a stored idempotency receipt (`Idempotency-Replayed: true`). Hosts
   * that need replay-visible output (the MCP write adapter) call this;
   * `MutateClient.mutateWithMeta` satisfies it.
   */
  mutateWithMeta?(op: string, args: WriteBridgeArgs): Promise<{ data: unknown; replayed: boolean }>;
}

/** A generated hey-api options envelope (the `<Op>Data` request shape). */
type OptionsEnvelope = {
  path?: unknown;
  body?: unknown;
  query?: unknown;
  headers?: unknown;
};

/**
 * Build a {@link WriteSurface} whose every op forwards to the generic dispatcher.
 * Compose it with native per-op implementations and `satisfies WriteSurface` to
 * prove the whole contract is still covered:
 *
 *   const surface = {
 *     ...createBridgeWriteSurface(bridge),
 *     budgetUpsertLinePhaseData: nativeUpsert, // hand-written, type-checked
 *   } satisfies WriteSurface;
 */
export function createBridgeWriteSurface(bridge: WriteBridge): WriteSurface {
  const forward = (op: string, data: OptionsEnvelope): Promise<unknown> =>
    bridge.mutate(op, {
      ...(data.path !== undefined ? { path: data.path as Record<string, unknown> } : {}),
      ...(data.body !== undefined ? { body: data.body } : {}),
      ...(data.query !== undefined ? { query: data.query as Record<string, unknown> } : {}),
      ...(data.headers !== undefined ? { headers: data.headers as Record<string, string> } : {}),
    });

  return {
    budgetCreateLine(data: BudgetCreateLineData): Promise<BudgetCreateLineResponse> {
      return forward('budgetCreateLine', data) as Promise<BudgetCreateLineResponse>;
    },
    budgetCreateLinesBulk(data: BudgetCreateLinesBulkData): Promise<BudgetCreateLinesBulkResponse> {
      return forward('budgetCreateLinesBulk', data) as Promise<BudgetCreateLinesBulkResponse>;
    },
    budgetCreatePhase(data: BudgetCreatePhaseData): Promise<BudgetCreatePhaseResponse> {
      return forward('budgetCreatePhase', data) as Promise<BudgetCreatePhaseResponse>;
    },
    budgetDeleteLine(data: BudgetDeleteLineData): Promise<BudgetDeleteLineResponse> {
      return forward('budgetDeleteLine', data) as Promise<BudgetDeleteLineResponse>;
    },
    budgetDeletePhase(data: BudgetDeletePhaseData): Promise<BudgetDeletePhaseResponse> {
      return forward('budgetDeletePhase', data) as Promise<BudgetDeletePhaseResponse>;
    },
    budgetUpdateLine(data: BudgetUpdateLineData): Promise<BudgetUpdateLineResponse> {
      return forward('budgetUpdateLine', data) as Promise<BudgetUpdateLineResponse>;
    },
    budgetUpdatePhase(data: BudgetUpdatePhaseData): Promise<BudgetUpdatePhaseResponse> {
      return forward('budgetUpdatePhase', data) as Promise<BudgetUpdatePhaseResponse>;
    },
    budgetUpsertLinePhaseData(data: BudgetUpsertLinePhaseDataData): Promise<BudgetUpsertLinePhaseDataResponse> {
      return forward('budgetUpsertLinePhaseData', data) as Promise<BudgetUpsertLinePhaseDataResponse>;
    },
    budgetUpsertLinePhaseDataBulk(data: BudgetUpsertLinePhaseDataBulkData): Promise<BudgetUpsertLinePhaseDataBulkResponse> {
      return forward('budgetUpsertLinePhaseDataBulk', data) as Promise<BudgetUpsertLinePhaseDataBulkResponse>;
    },
    documentsDelete(data: DocumentsDeleteData): Promise<DocumentsDeleteResponse> {
      return forward('documentsDelete', data) as Promise<DocumentsDeleteResponse>;
    },
    documentsDeleteLink(data: DocumentsDeleteLinkData): Promise<DocumentsDeleteLinkResponse> {
      return forward('documentsDeleteLink', data) as Promise<DocumentsDeleteLinkResponse>;
    },
    documentsPutLink(data: DocumentsPutLinkData): Promise<DocumentsPutLinkResponse> {
      return forward('documentsPutLink', data) as Promise<DocumentsPutLinkResponse>;
    },
    documentsUpdate(data: DocumentsUpdateData): Promise<DocumentsUpdateResponse> {
      return forward('documentsUpdate', data) as Promise<DocumentsUpdateResponse>;
    },
    libraryAddProjectCurrency(data: LibraryAddProjectCurrencyData): Promise<LibraryAddProjectCurrencyResponse> {
      return forward('libraryAddProjectCurrency', data) as Promise<LibraryAddProjectCurrencyResponse>;
    },
    libraryAddProjectFringe(data: LibraryAddProjectFringeData): Promise<LibraryAddProjectFringeResponse> {
      return forward('libraryAddProjectFringe', data) as Promise<LibraryAddProjectFringeResponse>;
    },
    libraryAddProjectFringeGroup(data: LibraryAddProjectFringeGroupData): Promise<LibraryAddProjectFringeGroupResponse> {
      return forward('libraryAddProjectFringeGroup', data) as Promise<LibraryAddProjectFringeGroupResponse>;
    },
    libraryAddProjectGlobal(data: LibraryAddProjectGlobalData): Promise<LibraryAddProjectGlobalResponse> {
      return forward('libraryAddProjectGlobal', data) as Promise<LibraryAddProjectGlobalResponse>;
    },
    libraryAddProjectIncentive(data: LibraryAddProjectIncentiveData): Promise<LibraryAddProjectIncentiveResponse> {
      return forward('libraryAddProjectIncentive', data) as Promise<LibraryAddProjectIncentiveResponse>;
    },
    libraryAddRatePack(data: LibraryAddRatePackData): Promise<LibraryAddRatePackResponse> {
      return forward('libraryAddRatePack', data) as Promise<LibraryAddRatePackResponse>;
    },
    libraryCreateCurrency(data: LibraryCreateCurrencyData): Promise<LibraryCreateCurrencyResponse> {
      return forward('libraryCreateCurrency', data) as Promise<LibraryCreateCurrencyResponse>;
    },
    libraryCreateFringe(data: LibraryCreateFringeData): Promise<LibraryCreateFringeResponse> {
      return forward('libraryCreateFringe', data) as Promise<LibraryCreateFringeResponse>;
    },
    libraryCreateFringeGroup(data: LibraryCreateFringeGroupData): Promise<LibraryCreateFringeGroupResponse> {
      return forward('libraryCreateFringeGroup', data) as Promise<LibraryCreateFringeGroupResponse>;
    },
    libraryCreateGlobal(data: LibraryCreateGlobalData): Promise<LibraryCreateGlobalResponse> {
      return forward('libraryCreateGlobal', data) as Promise<LibraryCreateGlobalResponse>;
    },
    libraryCreateRatePack(data: LibraryCreateRatePackData): Promise<LibraryCreateRatePackResponse> {
      return forward('libraryCreateRatePack', data) as Promise<LibraryCreateRatePackResponse>;
    },
    libraryCreateRatePackItem(data: LibraryCreateRatePackItemData): Promise<LibraryCreateRatePackItemResponse> {
      return forward('libraryCreateRatePackItem', data) as Promise<LibraryCreateRatePackItemResponse>;
    },
    libraryCreateTag(data: LibraryCreateTagData): Promise<LibraryCreateTagResponse> {
      return forward('libraryCreateTag', data) as Promise<LibraryCreateTagResponse>;
    },
    libraryCreateUnit(data: LibraryCreateUnitData): Promise<LibraryCreateUnitResponse> {
      return forward('libraryCreateUnit', data) as Promise<LibraryCreateUnitResponse>;
    },
    libraryDeleteCurrency(data: LibraryDeleteCurrencyData): Promise<LibraryDeleteCurrencyResponse> {
      return forward('libraryDeleteCurrency', data) as Promise<LibraryDeleteCurrencyResponse>;
    },
    libraryDeleteFringe(data: LibraryDeleteFringeData): Promise<LibraryDeleteFringeResponse> {
      return forward('libraryDeleteFringe', data) as Promise<LibraryDeleteFringeResponse>;
    },
    libraryDeleteFringeGroup(data: LibraryDeleteFringeGroupData): Promise<LibraryDeleteFringeGroupResponse> {
      return forward('libraryDeleteFringeGroup', data) as Promise<LibraryDeleteFringeGroupResponse>;
    },
    libraryDeleteGlobal(data: LibraryDeleteGlobalData): Promise<LibraryDeleteGlobalResponse> {
      return forward('libraryDeleteGlobal', data) as Promise<LibraryDeleteGlobalResponse>;
    },
    libraryDeleteProjectCurrency(data: LibraryDeleteProjectCurrencyData): Promise<LibraryDeleteProjectCurrencyResponse> {
      return forward('libraryDeleteProjectCurrency', data) as Promise<LibraryDeleteProjectCurrencyResponse>;
    },
    libraryDeleteProjectFringe(data: LibraryDeleteProjectFringeData): Promise<LibraryDeleteProjectFringeResponse> {
      return forward('libraryDeleteProjectFringe', data) as Promise<LibraryDeleteProjectFringeResponse>;
    },
    libraryDeleteProjectFringeGroup(data: LibraryDeleteProjectFringeGroupData): Promise<LibraryDeleteProjectFringeGroupResponse> {
      return forward('libraryDeleteProjectFringeGroup', data) as Promise<LibraryDeleteProjectFringeGroupResponse>;
    },
    libraryDeleteProjectGlobal(data: LibraryDeleteProjectGlobalData): Promise<LibraryDeleteProjectGlobalResponse> {
      return forward('libraryDeleteProjectGlobal', data) as Promise<LibraryDeleteProjectGlobalResponse>;
    },
    libraryDeleteProjectIncentive(data: LibraryDeleteProjectIncentiveData): Promise<LibraryDeleteProjectIncentiveResponse> {
      return forward('libraryDeleteProjectIncentive', data) as Promise<LibraryDeleteProjectIncentiveResponse>;
    },
    libraryDeleteRatePack(data: LibraryDeleteRatePackData): Promise<LibraryDeleteRatePackResponse> {
      return forward('libraryDeleteRatePack', data) as Promise<LibraryDeleteRatePackResponse>;
    },
    libraryDeleteRatePackItem(data: LibraryDeleteRatePackItemData): Promise<LibraryDeleteRatePackItemResponse> {
      return forward('libraryDeleteRatePackItem', data) as Promise<LibraryDeleteRatePackItemResponse>;
    },
    libraryDeleteTag(data: LibraryDeleteTagData): Promise<LibraryDeleteTagResponse> {
      return forward('libraryDeleteTag', data) as Promise<LibraryDeleteTagResponse>;
    },
    libraryDeleteUnit(data: LibraryDeleteUnitData): Promise<LibraryDeleteUnitResponse> {
      return forward('libraryDeleteUnit', data) as Promise<LibraryDeleteUnitResponse>;
    },
    libraryDisableIncentivePack(data: LibraryDisableIncentivePackData): Promise<LibraryDisableIncentivePackResponse> {
      return forward('libraryDisableIncentivePack', data) as Promise<LibraryDisableIncentivePackResponse>;
    },
    libraryDisableRatePack(data: LibraryDisableRatePackData): Promise<LibraryDisableRatePackResponse> {
      return forward('libraryDisableRatePack', data) as Promise<LibraryDisableRatePackResponse>;
    },
    libraryEnableIncentivePack(data: LibraryEnableIncentivePackData): Promise<LibraryEnableIncentivePackResponse> {
      return forward('libraryEnableIncentivePack', data) as Promise<LibraryEnableIncentivePackResponse>;
    },
    libraryEnableRatePack(data: LibraryEnableRatePackData): Promise<LibraryEnableRatePackResponse> {
      return forward('libraryEnableRatePack', data) as Promise<LibraryEnableRatePackResponse>;
    },
    libraryRemoveRatePack(data: LibraryRemoveRatePackData): Promise<LibraryRemoveRatePackResponse> {
      return forward('libraryRemoveRatePack', data) as Promise<LibraryRemoveRatePackResponse>;
    },
    libraryUpdateCurrency(data: LibraryUpdateCurrencyData): Promise<LibraryUpdateCurrencyResponse> {
      return forward('libraryUpdateCurrency', data) as Promise<LibraryUpdateCurrencyResponse>;
    },
    libraryUpdateFringe(data: LibraryUpdateFringeData): Promise<LibraryUpdateFringeResponse> {
      return forward('libraryUpdateFringe', data) as Promise<LibraryUpdateFringeResponse>;
    },
    libraryUpdateFringeGroup(data: LibraryUpdateFringeGroupData): Promise<LibraryUpdateFringeGroupResponse> {
      return forward('libraryUpdateFringeGroup', data) as Promise<LibraryUpdateFringeGroupResponse>;
    },
    libraryUpdateGlobal(data: LibraryUpdateGlobalData): Promise<LibraryUpdateGlobalResponse> {
      return forward('libraryUpdateGlobal', data) as Promise<LibraryUpdateGlobalResponse>;
    },
    libraryUpdateProjectCurrency(data: LibraryUpdateProjectCurrencyData): Promise<LibraryUpdateProjectCurrencyResponse> {
      return forward('libraryUpdateProjectCurrency', data) as Promise<LibraryUpdateProjectCurrencyResponse>;
    },
    libraryUpdateProjectFringe(data: LibraryUpdateProjectFringeData): Promise<LibraryUpdateProjectFringeResponse> {
      return forward('libraryUpdateProjectFringe', data) as Promise<LibraryUpdateProjectFringeResponse>;
    },
    libraryUpdateProjectFringeGroup(data: LibraryUpdateProjectFringeGroupData): Promise<LibraryUpdateProjectFringeGroupResponse> {
      return forward('libraryUpdateProjectFringeGroup', data) as Promise<LibraryUpdateProjectFringeGroupResponse>;
    },
    libraryUpdateProjectGlobal(data: LibraryUpdateProjectGlobalData): Promise<LibraryUpdateProjectGlobalResponse> {
      return forward('libraryUpdateProjectGlobal', data) as Promise<LibraryUpdateProjectGlobalResponse>;
    },
    libraryUpdateProjectIncentive(data: LibraryUpdateProjectIncentiveData): Promise<LibraryUpdateProjectIncentiveResponse> {
      return forward('libraryUpdateProjectIncentive', data) as Promise<LibraryUpdateProjectIncentiveResponse>;
    },
    libraryUpdateRatePack(data: LibraryUpdateRatePackData): Promise<LibraryUpdateRatePackResponse> {
      return forward('libraryUpdateRatePack', data) as Promise<LibraryUpdateRatePackResponse>;
    },
    libraryUpdateRatePackItem(data: LibraryUpdateRatePackItemData): Promise<LibraryUpdateRatePackItemResponse> {
      return forward('libraryUpdateRatePackItem', data) as Promise<LibraryUpdateRatePackItemResponse>;
    },
    libraryUpdateTag(data: LibraryUpdateTagData): Promise<LibraryUpdateTagResponse> {
      return forward('libraryUpdateTag', data) as Promise<LibraryUpdateTagResponse>;
    },
    libraryUpdateUnit(data: LibraryUpdateUnitData): Promise<LibraryUpdateUnitResponse> {
      return forward('libraryUpdateUnit', data) as Promise<LibraryUpdateUnitResponse>;
    },
    masterDataCreateComment(data: MasterDataCreateCommentData): Promise<MasterDataCreateCommentResponse> {
      return forward('masterDataCreateComment', data) as Promise<MasterDataCreateCommentResponse>;
    },
    masterDataCreateContact(data: MasterDataCreateContactData): Promise<MasterDataCreateContactResponse> {
      return forward('masterDataCreateContact', data) as Promise<MasterDataCreateContactResponse>;
    },
    masterDataCreateProject(data: MasterDataCreateProjectData): Promise<MasterDataCreateProjectResponse> {
      return forward('masterDataCreateProject', data) as Promise<MasterDataCreateProjectResponse>;
    },
    masterDataCreateSpace(data: MasterDataCreateSpaceData): Promise<MasterDataCreateSpaceResponse> {
      return forward('masterDataCreateSpace', data) as Promise<MasterDataCreateSpaceResponse>;
    },
    masterDataDeleteComment(data: MasterDataDeleteCommentData): Promise<MasterDataDeleteCommentResponse> {
      return forward('masterDataDeleteComment', data) as Promise<MasterDataDeleteCommentResponse>;
    },
    masterDataDeleteContact(data: MasterDataDeleteContactData): Promise<MasterDataDeleteContactResponse> {
      return forward('masterDataDeleteContact', data) as Promise<MasterDataDeleteContactResponse>;
    },
    masterDataDeleteSpace(data: MasterDataDeleteSpaceData): Promise<MasterDataDeleteSpaceResponse> {
      return forward('masterDataDeleteSpace', data) as Promise<MasterDataDeleteSpaceResponse>;
    },
    masterDataUpdateComment(data: MasterDataUpdateCommentData): Promise<MasterDataUpdateCommentResponse> {
      return forward('masterDataUpdateComment', data) as Promise<MasterDataUpdateCommentResponse>;
    },
    masterDataUpdateContact(data: MasterDataUpdateContactData): Promise<MasterDataUpdateContactResponse> {
      return forward('masterDataUpdateContact', data) as Promise<MasterDataUpdateContactResponse>;
    },
    masterDataUpdateProject(data: MasterDataUpdateProjectData): Promise<MasterDataUpdateProjectResponse> {
      return forward('masterDataUpdateProject', data) as Promise<MasterDataUpdateProjectResponse>;
    },
    masterDataUpdateSpace(data: MasterDataUpdateSpaceData): Promise<MasterDataUpdateSpaceResponse> {
      return forward('masterDataUpdateSpace', data) as Promise<MasterDataUpdateSpaceResponse>;
    },
    purchaseOrdersCancelSubmission(data: PurchaseOrdersCancelSubmissionData): Promise<PurchaseOrdersCancelSubmissionResponse> {
      return forward('purchaseOrdersCancelSubmission', data) as Promise<PurchaseOrdersCancelSubmissionResponse>;
    },
    purchaseOrdersCreate(data: PurchaseOrdersCreateData): Promise<PurchaseOrdersCreateResponse> {
      return forward('purchaseOrdersCreate', data) as Promise<PurchaseOrdersCreateResponse>;
    },
    purchaseOrdersCreateItem(data: PurchaseOrdersCreateItemData): Promise<PurchaseOrdersCreateItemResponse> {
      return forward('purchaseOrdersCreateItem', data) as Promise<PurchaseOrdersCreateItemResponse>;
    },
    purchaseOrdersDelete(data: PurchaseOrdersDeleteData): Promise<PurchaseOrdersDeleteResponse> {
      return forward('purchaseOrdersDelete', data) as Promise<PurchaseOrdersDeleteResponse>;
    },
    purchaseOrdersDeleteItem(data: PurchaseOrdersDeleteItemData): Promise<PurchaseOrdersDeleteItemResponse> {
      return forward('purchaseOrdersDeleteItem', data) as Promise<PurchaseOrdersDeleteItemResponse>;
    },
    purchaseOrdersDeleteTransaction(data: PurchaseOrdersDeleteTransactionData): Promise<PurchaseOrdersDeleteTransactionResponse> {
      return forward('purchaseOrdersDeleteTransaction', data) as Promise<PurchaseOrdersDeleteTransactionResponse>;
    },
    purchaseOrdersMarkPaid(data: PurchaseOrdersMarkPaidData): Promise<PurchaseOrdersMarkPaidResponse> {
      return forward('purchaseOrdersMarkPaid', data) as Promise<PurchaseOrdersMarkPaidResponse>;
    },
    purchaseOrdersPutTransaction(data: PurchaseOrdersPutTransactionData): Promise<PurchaseOrdersPutTransactionResponse> {
      return forward('purchaseOrdersPutTransaction', data) as Promise<PurchaseOrdersPutTransactionResponse>;
    },
    purchaseOrdersUpdate(data: PurchaseOrdersUpdateData): Promise<PurchaseOrdersUpdateResponse> {
      return forward('purchaseOrdersUpdate', data) as Promise<PurchaseOrdersUpdateResponse>;
    },
    purchaseOrdersUpdateItem(data: PurchaseOrdersUpdateItemData): Promise<PurchaseOrdersUpdateItemResponse> {
      return forward('purchaseOrdersUpdateItem', data) as Promise<PurchaseOrdersUpdateItemResponse>;
    },
    purchaseOrdersVoid(data: PurchaseOrdersVoidData): Promise<PurchaseOrdersVoidResponse> {
      return forward('purchaseOrdersVoid', data) as Promise<PurchaseOrdersVoidResponse>;
    },
    transactionsBulkCreate(data: TransactionsBulkCreateData): Promise<TransactionsBulkCreateResponse> {
      return forward('transactionsBulkCreate', data) as Promise<TransactionsBulkCreateResponse>;
    },
    transactionsCreate(data: TransactionsCreateData): Promise<TransactionsCreateResponse> {
      return forward('transactionsCreate', data) as Promise<TransactionsCreateResponse>;
    },
    transactionsDelete(data: TransactionsDeleteData): Promise<TransactionsDeleteResponse> {
      return forward('transactionsDelete', data) as Promise<TransactionsDeleteResponse>;
    },
    transactionsItemsCreate(data: TransactionsItemsCreateData): Promise<TransactionsItemsCreateResponse> {
      return forward('transactionsItemsCreate', data) as Promise<TransactionsItemsCreateResponse>;
    },
    transactionsItemsDelete(data: TransactionsItemsDeleteData): Promise<TransactionsItemsDeleteResponse> {
      return forward('transactionsItemsDelete', data) as Promise<TransactionsItemsDeleteResponse>;
    },
    transactionsItemsUpdate(data: TransactionsItemsUpdateData): Promise<TransactionsItemsUpdateResponse> {
      return forward('transactionsItemsUpdate', data) as Promise<TransactionsItemsUpdateResponse>;
    },
    transactionsUpdate(data: TransactionsUpdateData): Promise<TransactionsUpdateResponse> {
      return forward('transactionsUpdate', data) as Promise<TransactionsUpdateResponse>;
    },
    webhooksCreate(data: WebhooksCreateData): Promise<WebhooksCreateResponse> {
      return forward('webhooksCreate', data) as Promise<WebhooksCreateResponse>;
    },
    webhooksDelete(data: WebhooksDeleteData): Promise<WebhooksDeleteResponse> {
      return forward('webhooksDelete', data) as Promise<WebhooksDeleteResponse>;
    },
    webhooksSendTestDelivery(data: WebhooksSendTestDeliveryData): Promise<WebhooksSendTestDeliveryResponse> {
      return forward('webhooksSendTestDelivery', data) as Promise<WebhooksSendTestDeliveryResponse>;
    },
    webhooksUpdate(data: WebhooksUpdateData): Promise<WebhooksUpdateResponse> {
      return forward('webhooksUpdate', data) as Promise<WebhooksUpdateResponse>;
    },
  } satisfies WriteSurface;
}
