// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// The `mutate` write surface: an explicit allowlist over the generated /v1 SDK
// (CREATE + value-UPDATE, additive only). Regenerate with:
//   pnpm --filter @saturation/sdk generate:mutate
//
// 25 write operations selected from 151 total operations.

/** A single write operation's static metadata, derived from the OpenAPI spec. */
export interface WriteOpDef {
  /** The operation id — the `mutate` op key the model passes. */
  readonly op: string;
  /** HTTP verb the gated /v1 handler is reached through. */
  readonly method: 'post' | 'put' | 'patch';
  /** Templated path (`{param}` segments filled from `path`). */
  readonly url: string;
  /** Ordered path-parameter names this op requires (e.g. `projectId`, `lineId`). */
  readonly pathParams: readonly string[];
  /** The generated request-data type name (provenance; the body shape lives there). */
  readonly dataType: string;
  /**
   * The op's request `body` shape as a compact, model-readable field list
   * (`{ field: Type; field2?: Type2; … }`) resolved one level from `<Op>Data`.
   * This is what lets the model read REAL field types off the catalog instead of
   * a bare type name; the typed `WriteSurface` contract remains the compile-time
   * guarantee. `never` = no body; `unknown` = a doc-generation miss.
   */
  readonly bodyType: string;
  /** Whether the generated request envelope requires a JSON body. */
  readonly bodyRequired: boolean;
  /** Generated top-level body field allowlist used by side-effect-free preview validation. */
  readonly allowedBodyFields: readonly string[];
  /** Generated top-level body fields that must be present. */
  readonly requiredBodyFields: readonly string[];
  /** One-line human summary from the OpenAPI operation. */
  readonly summary: string;
}

/** The generated write-op table, keyed by operation id. */
export const WRITE_OPS = {
  budgetUpdateLine: {
    op: 'budgetUpdateLine',
    method: 'patch',
    url: '/projects/{projectId}/budget/lines/{lineId}',
    pathParams: ['projectId', 'lineId'],
    dataType: 'BudgetUpdateLineData',
    bodyType: "{ name?: string; kind?: BudgetLineKind; code?: string; parentId?: Id; contactId?: Id | null; lineColor?: string | null; emoji?: string | null; notes?: string | null; tagIds?: Array<Id>; subtotalSumAllAbove?: boolean; subtotalIsBold?: boolean; markupAccountFilter?: string | null; phaseData?: { [key: string]: BudgetLinePhaseDataWrite; }; }",
    bodyRequired: true,
    allowedBodyFields: ["name","kind","code","parentId","contactId","lineColor","emoji","notes","tagIds","subtotalSumAllAbove","subtotalIsBold","markupAccountFilter","phaseData"],
    requiredBodyFields: [],
    summary: 'Update a budget line',
  },
  budgetUpdatePhase: {
    op: 'budgetUpdatePhase',
    method: 'patch',
    url: '/projects/{projectId}/budget/phases/{phaseId}',
    pathParams: ['projectId', 'phaseId'],
    dataType: 'BudgetUpdatePhaseData',
    bodyType: "{ name?: string; alias?: string; color?: string | null; isHidden?: boolean; }",
    bodyRequired: true,
    allowedBodyFields: ["name","alias","color","isHidden"],
    requiredBodyFields: [],
    summary: 'Update a budget phase',
  },
  budgetUpsertLinePhaseData: {
    op: 'budgetUpsertLinePhaseData',
    method: 'put',
    url: '/projects/{projectId}/budget/lines/{lineId}/phase-data/{phaseId}',
    pathParams: ['projectId', 'lineId', 'phaseId'],
    dataType: 'BudgetUpsertLinePhaseDataData',
    bodyType: "{ rate?: BudgetDocumentPhaseDataValue; quantity?: BudgetDocumentPhaseDataValue; multiplier?: BudgetDocumentPhaseDataValue; qtyAutoDerived?: boolean | null; unit?: string | null; customUnitId?: Id | null; startDate?: string | null; endDate?: string | null; fringeIds?: Array<Id> | null; fringeTagIds?: Array<Id> | null; currencyId?: Id | null; overtime?: BudgetDocumentOvertime; }",
    bodyRequired: true,
    allowedBodyFields: ["rate","quantity","multiplier","qtyAutoDerived","unit","customUnitId","startDate","endDate","fringeIds","fringeTagIds","currencyId","overtime"],
    requiredBodyFields: [],
    summary: 'Upsert one editable line phase-data entry',
  },
  documentsUpdate: {
    op: 'documentsUpdate',
    method: 'patch',
    url: '/documents/{documentId}',
    pathParams: ['documentId'],
    dataType: 'DocumentsUpdateData',
    bodyType: "{ name?: string; description?: string | null; folderId?: Id | null; }",
    bodyRequired: true,
    allowedBodyFields: ["name","description","folderId"],
    requiredBodyFields: [],
    summary: 'Rename / move / re-describe a document',
  },
  libraryUpdateCurrencyTemplate: {
    op: 'libraryUpdateCurrencyTemplate',
    method: 'patch',
    url: '/library/currencies/{currencyId}',
    pathParams: ['currencyId'],
    dataType: 'LibraryUpdateCurrencyTemplateData',
    bodyType: "{ code?: string; name?: string | null; rate?: number | null; sort?: number; }",
    bodyRequired: true,
    allowedBodyFields: ["code","name","rate","sort"],
    requiredBodyFields: [],
    summary: 'Update a workspace currency template',
  },
  libraryUpdateCustomUnit: {
    op: 'libraryUpdateCustomUnit',
    method: 'patch',
    url: '/library/units/custom/{unitId}',
    pathParams: ['unitId'],
    dataType: 'LibraryUpdateCustomUnitData',
    bodyType: "{ label?: string; description?: string | null; }",
    bodyRequired: true,
    allowedBodyFields: ["label","description"],
    requiredBodyFields: [],
    summary: 'Update a workspace custom unit',
  },
  libraryUpdateFringeTagTemplate: {
    op: 'libraryUpdateFringeTagTemplate',
    method: 'patch',
    url: '/library/fringe-tags/{fringeTagId}',
    pathParams: ['fringeTagId'],
    dataType: 'LibraryUpdateFringeTagTemplateData',
    bodyType: "{ name?: string; color?: TagColor; sort?: number; }",
    bodyRequired: true,
    allowedBodyFields: ["name","color","sort"],
    requiredBodyFields: [],
    summary: 'Update a workspace fringe-tag template',
  },
  libraryUpdateFringeTemplate: {
    op: 'libraryUpdateFringeTemplate',
    method: 'patch',
    url: '/library/fringes/{fringeId}',
    pathParams: ['fringeId'],
    dataType: 'LibraryUpdateFringeTemplateData',
    bodyType: "{ name?: string; rate?: number | null; cap?: Money | null; sort?: number; }",
    bodyRequired: true,
    allowedBodyFields: ["name","rate","cap","sort"],
    requiredBodyFields: [],
    summary: 'Update a workspace fringe template',
  },
  libraryUpdateGlobalTemplate: {
    op: 'libraryUpdateGlobalTemplate',
    method: 'patch',
    url: '/library/globals/{globalId}',
    pathParams: ['globalId'],
    dataType: 'LibraryUpdateGlobalTemplateData',
    bodyType: "{ name?: string; value?: number | null; unit?: string | null; sort?: number; }",
    bodyRequired: true,
    allowedBodyFields: ["name","value","unit","sort"],
    requiredBodyFields: [],
    summary: 'Update a workspace global template',
  },
  libraryUpdateProjectCurrency: {
    op: 'libraryUpdateProjectCurrency',
    method: 'patch',
    url: '/projects/{projectId}/library/currencies/{currencyId}',
    pathParams: ['projectId', 'currencyId'],
    dataType: 'LibraryUpdateProjectCurrencyData',
    bodyType: "{ code?: string; name?: string | null; rate?: number | null; sort?: number; }",
    bodyRequired: true,
    allowedBodyFields: ["code","name","rate","sort"],
    requiredBodyFields: [],
    summary: 'Update a project currency copy',
  },
  libraryUpdateProjectFringe: {
    op: 'libraryUpdateProjectFringe',
    method: 'patch',
    url: '/projects/{projectId}/library/fringes/{fringeId}',
    pathParams: ['projectId', 'fringeId'],
    dataType: 'LibraryUpdateProjectFringeData',
    bodyType: "{ name?: string; rate?: number | null; cap?: Money | null; sort?: number; }",
    bodyRequired: true,
    allowedBodyFields: ["name","rate","cap","sort"],
    requiredBodyFields: [],
    summary: 'Update a project fringe copy',
  },
  libraryUpdateProjectFringeTag: {
    op: 'libraryUpdateProjectFringeTag',
    method: 'patch',
    url: '/projects/{projectId}/library/fringe-tags/{fringeTagId}',
    pathParams: ['projectId', 'fringeTagId'],
    dataType: 'LibraryUpdateProjectFringeTagData',
    bodyType: "{ name?: string; color?: TagColor; sort?: number; }",
    bodyRequired: true,
    allowedBodyFields: ["name","color","sort"],
    requiredBodyFields: [],
    summary: 'Update a project fringe-tag copy',
  },
  libraryUpdateProjectGlobal: {
    op: 'libraryUpdateProjectGlobal',
    method: 'patch',
    url: '/projects/{projectId}/library/globals/{globalId}',
    pathParams: ['projectId', 'globalId'],
    dataType: 'LibraryUpdateProjectGlobalData',
    bodyType: "{ name?: string; value?: number | null; unit?: string | null; sort?: number; }",
    bodyRequired: true,
    allowedBodyFields: ["name","value","unit","sort"],
    requiredBodyFields: [],
    summary: 'Update a project global copy',
  },
  libraryUpdateProjectIncentive: {
    op: 'libraryUpdateProjectIncentive',
    method: 'patch',
    url: '/projects/{projectId}/library/incentives/{incentiveId}',
    pathParams: ['projectId', 'incentiveId'],
    dataType: 'LibraryUpdateProjectIncentiveData',
    bodyType: "{ name?: string; description?: string | null; isApplied?: boolean; }",
    bodyRequired: true,
    allowedBodyFields: ["name","description","isApplied"],
    requiredBodyFields: [],
    summary: 'Update a project incentive',
  },
  libraryUpdateRatePack: {
    op: 'libraryUpdateRatePack',
    method: 'patch',
    url: '/library/rates/{packId}',
    pathParams: ['packId'],
    dataType: 'LibraryUpdateRatePackData',
    bodyType: "{ name?: string; description?: string | null; category?: string; tags?: Array<string>; }",
    bodyRequired: true,
    allowedBodyFields: ["name","description","category","tags"],
    requiredBodyFields: [],
    summary: 'Update an owned rate pack',
  },
  libraryUpdateRatePackItem: {
    op: 'libraryUpdateRatePackItem',
    method: 'patch',
    url: '/library/rates/{packId}/items/{itemId}',
    pathParams: ['packId', 'itemId'],
    dataType: 'LibraryUpdateRatePackItemData',
    bodyType: "{ title?: string; rate?: Money; unit?: string; currency?: string; description?: string | null; quantity?: number | null; multiplier?: number | null; group?: string | null; agreement?: string | null; local?: string | null; effectiveDate?: string | null; labels?: Array<string>; displayTags?: Array<string>; searchAliases?: Array<string>; facets?: { [key: string]: unknown; }; sourceRefs?: Array<string>; qualityFlags?: Array<string>; rateBasis?: string | null; }",
    bodyRequired: true,
    allowedBodyFields: ["title","rate","unit","currency","description","quantity","multiplier","group","agreement","local","effectiveDate","labels","displayTags","searchAliases","facets","sourceRefs","qualityFlags","rateBasis"],
    requiredBodyFields: [],
    summary: 'Update a pack item',
  },
  libraryUpdateTag: {
    op: 'libraryUpdateTag',
    method: 'patch',
    url: '/library/tags/{tagId}',
    pathParams: ['tagId'],
    dataType: 'LibraryUpdateTagData',
    bodyType: "{ name?: string; color?: TagColor; description?: string | null; eligibilityKey?: string | null; sort?: number; }",
    bodyRequired: true,
    allowedBodyFields: ["name","color","description","eligibilityKey","sort"],
    requiredBodyFields: [],
    summary: 'Update a workspace tag',
  },
  masterDataUpdateComment: {
    op: 'masterDataUpdateComment',
    method: 'patch',
    url: '/comments/{commentId}',
    pathParams: ['commentId'],
    dataType: 'MasterDataUpdateCommentData',
    bodyType: "{ content?: string; resolved?: boolean; }",
    bodyRequired: true,
    allowedBodyFields: ["content","resolved"],
    requiredBodyFields: [],
    summary: 'Update a comment',
  },
  masterDataUpdateContact: {
    op: 'masterDataUpdateContact',
    method: 'patch',
    url: '/contacts/{contactId}',
    pathParams: ['contactId'],
    dataType: 'MasterDataUpdateContactData',
    bodyType: "{ name?: string; company?: string | null; title?: string | null; type?: ContactType; email?: string | null; phone?: string | null; address?: string | null; website?: string | null; instagram?: string | null; imdb?: string | null; defaultRate?: Money | null; track1099?: boolean; notes?: string | null; }",
    bodyRequired: true,
    allowedBodyFields: ["name","company","title","type","email","phone","address","website","instagram","imdb","defaultRate","track1099","notes"],
    requiredBodyFields: [],
    summary: 'Update a contact',
  },
  masterDataUpdateProject: {
    op: 'masterDataUpdateProject',
    method: 'patch',
    url: '/projects/{slugOrId}',
    pathParams: ['slugOrId'],
    dataType: 'MasterDataUpdateProjectData',
    bodyType: "{ name?: string; slug?: string; emoji?: string | null; image?: string | null; summary?: string | null; spaceId?: Id | null; status?: 'active' | 'archived'; }",
    bodyRequired: true,
    allowedBodyFields: ["name","slug","emoji","image","summary","spaceId","status"],
    requiredBodyFields: [],
    summary: 'Update a project',
  },
  masterDataUpdateSpace: {
    op: 'masterDataUpdateSpace',
    method: 'patch',
    url: '/spaces/{spaceId}',
    pathParams: ['spaceId'],
    dataType: 'MasterDataUpdateSpaceData',
    bodyType: "{ name?: string; slug?: string; image?: string | null; parentId?: Id | null; archived?: boolean; }",
    bodyRequired: true,
    allowedBodyFields: ["name","slug","image","parentId","archived"],
    requiredBodyFields: [],
    summary: 'Update a space',
  },
  purchaseOrdersUpdate: {
    op: 'purchaseOrdersUpdate',
    method: 'patch',
    url: '/purchase-orders/{purchaseOrderId}',
    pathParams: ['purchaseOrderId'],
    dataType: 'PurchaseOrdersUpdateData',
    bodyType: "{ projectId?: string | null; number?: string | null; title?: string | null; contactId?: string | null; budgetLineId?: string | null; date?: string | null; serviceStartAt?: string | null; serviceEndAt?: string | null; notes?: string | null; sort?: number | null; }",
    bodyRequired: true,
    allowedBodyFields: ["projectId","number","title","contactId","budgetLineId","date","serviceStartAt","serviceEndAt","notes","sort"],
    requiredBodyFields: [],
    summary: 'Update a purchase order',
  },
  purchaseOrdersUpdateItem: {
    op: 'purchaseOrdersUpdateItem',
    method: 'patch',
    url: '/purchase-orders/{purchaseOrderId}/items/{itemId}',
    pathParams: ['purchaseOrderId', 'itemId'],
    dataType: 'PurchaseOrdersUpdateItemData',
    bodyType: "{ lineNumber?: number | null; description?: string | null; budgetLineId?: string | null; qty?: number | null; unit?: string | null; rate?: number | null; amount?: number | null; sort?: number | null; }",
    bodyRequired: true,
    allowedBodyFields: ["lineNumber","description","budgetLineId","qty","unit","rate","amount","sort"],
    requiredBodyFields: [],
    summary: 'Update a purchase order item',
  },
  transactionsItemsUpdate: {
    op: 'transactionsItemsUpdate',
    method: 'patch',
    url: '/transactions/{txId}/items/{itemId}',
    pathParams: ['txId', 'itemId'],
    dataType: 'TransactionsItemsUpdateData',
    bodyType: "{ description?: string | null; budgetLineId?: Id | null; fringeId?: Id | null; qty?: number | null; unit?: string | null; rate?: Money | null; amount?: Money; overtime?: boolean | null; taxable?: boolean | null; nonTaxable?: boolean | null; }",
    bodyRequired: true,
    allowedBodyFields: ["description","budgetLineId","fringeId","qty","unit","rate","amount","overtime","taxable","nonTaxable"],
    requiredBodyFields: [],
    summary: 'Update a transaction item',
  },
  transactionsUpdate: {
    op: 'transactionsUpdate',
    method: 'patch',
    url: '/transactions/{txId}',
    pathParams: ['txId'],
    dataType: 'TransactionsUpdateData',
    bodyType: "{ projectId?: Id | null; contactId?: Id | null; budgetLineId?: Id | null; fringeId?: Id | null; notes?: string | null; number?: string | null; ref?: string | null; amount?: Money; currency?: string; timestamp?: string; type?: TransactionType; status?: TransactionStatus; description?: string | null; merchant?: string | null; sourceLast4?: string | null; sourceName?: string | null; actualized?: boolean; }",
    bodyRequired: true,
    allowedBodyFields: ["projectId","contactId","budgetLineId","fringeId","notes","number","ref","amount","currency","timestamp","type","status","description","merchant","sourceLast4","sourceName","actualized"],
    requiredBodyFields: [],
    summary: 'Update a transaction',
  },
} as const satisfies Record<string, WriteOpDef>;

/** Every allowlisted write operation id (the model-facing op vocabulary). */
export type WriteOp = keyof typeof WRITE_OPS;

/** The ordered list of write-op ids. */
export const WRITE_OP_IDS = Object.keys(WRITE_OPS) as WriteOp[];
