// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// The `mutate` write surface CONTRACT: one typed method per allowlisted /v1
// write op, `<op>(data: <Op>Data): Promise<<Op>Response>`. Regenerate with:
//   pnpm generate:mutate
//
// This interface is the forcing function: when the OpenAPI document (and thus
// the generated `types.gen.ts` request/response types) changes, every
// `satisfies WriteSurface` implementation must update to match or fail `tsc`.
//
// 89 write operations.

import type {
  BudgetCreateLineData,
  BudgetCreateLineResponse,
  BudgetCreateLinesBulkData,
  BudgetCreateLinesBulkResponse,
  BudgetCreatePhaseData,
  BudgetCreatePhaseResponse,
  BudgetDeleteLineData,
  BudgetDeleteLineResponse,
  BudgetDeletePhaseData,
  BudgetDeletePhaseResponse,
  BudgetUpdateLineData,
  BudgetUpdateLinePhaseDataBulkData,
  BudgetUpdateLinePhaseDataBulkResponse,
  BudgetUpdateLinePhaseDataData,
  BudgetUpdateLinePhaseDataResponse,
  BudgetUpdateLineResponse,
  BudgetUpdatePhaseData,
  BudgetUpdatePhaseResponse,
  CommentsCreateData,
  CommentsCreateResponse,
  CommentsDeleteData,
  CommentsDeleteResponse,
  CommentsUpdateData,
  CommentsUpdateResponse,
  ContactsCreateData,
  ContactsCreateResponse,
  ContactsDeleteData,
  ContactsDeleteResponse,
  ContactsUpdateData,
  ContactsUpdateResponse,
  DocumentsDeleteData,
  DocumentsDeleteResponse,
  DocumentsLinkData,
  DocumentsLinkResponse,
  DocumentsUnlinkData,
  DocumentsUnlinkResponse,
  DocumentsUpdateData,
  DocumentsUpdateResponse,
  LibraryAddProjectCurrencyData,
  LibraryAddProjectCurrencyResponse,
  LibraryAddProjectFringeData,
  LibraryAddProjectFringeGroupData,
  LibraryAddProjectFringeGroupResponse,
  LibraryAddProjectFringeResponse,
  LibraryAddProjectGlobalData,
  LibraryAddProjectGlobalResponse,
  LibraryAddProjectIncentiveData,
  LibraryAddProjectIncentiveResponse,
  LibraryCreateCurrencyData,
  LibraryCreateCurrencyResponse,
  LibraryCreateFringeData,
  LibraryCreateFringeGroupData,
  LibraryCreateFringeGroupResponse,
  LibraryCreateFringeResponse,
  LibraryCreateGlobalData,
  LibraryCreateGlobalResponse,
  LibraryCreateRatePackData,
  LibraryCreateRatePackItemData,
  LibraryCreateRatePackItemResponse,
  LibraryCreateRatePackResponse,
  LibraryCreateTagData,
  LibraryCreateTagResponse,
  LibraryCreateUnitData,
  LibraryCreateUnitResponse,
  LibraryDeleteCurrencyData,
  LibraryDeleteCurrencyResponse,
  LibraryDeleteFringeData,
  LibraryDeleteFringeGroupData,
  LibraryDeleteFringeGroupResponse,
  LibraryDeleteFringeResponse,
  LibraryDeleteGlobalData,
  LibraryDeleteGlobalResponse,
  LibraryDeleteProjectCurrencyData,
  LibraryDeleteProjectCurrencyResponse,
  LibraryDeleteProjectFringeData,
  LibraryDeleteProjectFringeGroupData,
  LibraryDeleteProjectFringeGroupResponse,
  LibraryDeleteProjectFringeResponse,
  LibraryDeleteProjectGlobalData,
  LibraryDeleteProjectGlobalResponse,
  LibraryDeleteProjectIncentiveData,
  LibraryDeleteProjectIncentiveResponse,
  LibraryDeleteRatePackData,
  LibraryDeleteRatePackItemData,
  LibraryDeleteRatePackItemResponse,
  LibraryDeleteRatePackResponse,
  LibraryDeleteTagData,
  LibraryDeleteTagResponse,
  LibraryDeleteUnitData,
  LibraryDeleteUnitResponse,
  LibraryDisableIncentivePackData,
  LibraryDisableIncentivePackResponse,
  LibraryDisableRatePackData,
  LibraryDisableRatePackResponse,
  LibraryEnableIncentivePackData,
  LibraryEnableIncentivePackResponse,
  LibraryEnableRatePackData,
  LibraryEnableRatePackResponse,
  LibraryUpdateCurrencyData,
  LibraryUpdateCurrencyResponse,
  LibraryUpdateFringeData,
  LibraryUpdateFringeGroupData,
  LibraryUpdateFringeGroupResponse,
  LibraryUpdateFringeResponse,
  LibraryUpdateGlobalData,
  LibraryUpdateGlobalResponse,
  LibraryUpdateProjectCurrencyData,
  LibraryUpdateProjectCurrencyResponse,
  LibraryUpdateProjectFringeData,
  LibraryUpdateProjectFringeGroupData,
  LibraryUpdateProjectFringeGroupResponse,
  LibraryUpdateProjectFringeResponse,
  LibraryUpdateProjectGlobalData,
  LibraryUpdateProjectGlobalResponse,
  LibraryUpdateProjectIncentiveData,
  LibraryUpdateProjectIncentiveResponse,
  LibraryUpdateRatePackData,
  LibraryUpdateRatePackItemData,
  LibraryUpdateRatePackItemResponse,
  LibraryUpdateRatePackResponse,
  LibraryUpdateTagData,
  LibraryUpdateTagResponse,
  LibraryUpdateUnitData,
  LibraryUpdateUnitResponse,
  ProjectsCreateData,
  ProjectsCreateResponse,
  ProjectsUpdateData,
  ProjectsUpdateResponse,
  PurchaseOrdersCancelSubmissionData,
  PurchaseOrdersCancelSubmissionResponse,
  PurchaseOrdersCreateData,
  PurchaseOrdersCreateItemData,
  PurchaseOrdersCreateItemResponse,
  PurchaseOrdersCreateResponse,
  PurchaseOrdersDeleteData,
  PurchaseOrdersDeleteItemData,
  PurchaseOrdersDeleteItemResponse,
  PurchaseOrdersDeleteResponse,
  PurchaseOrdersLinkTransactionData,
  PurchaseOrdersLinkTransactionResponse,
  PurchaseOrdersMarkPaidData,
  PurchaseOrdersMarkPaidResponse,
  PurchaseOrdersUnlinkTransactionData,
  PurchaseOrdersUnlinkTransactionResponse,
  PurchaseOrdersUpdateData,
  PurchaseOrdersUpdateItemData,
  PurchaseOrdersUpdateItemResponse,
  PurchaseOrdersUpdateResponse,
  PurchaseOrdersVoidData,
  PurchaseOrdersVoidResponse,
  SpacesCreateData,
  SpacesCreateResponse,
  SpacesDeleteData,
  SpacesDeleteResponse,
  SpacesUpdateData,
  SpacesUpdateResponse,
  TransactionsCreateBulkData,
  TransactionsCreateBulkResponse,
  TransactionsCreateData,
  TransactionsCreateItemData,
  TransactionsCreateItemResponse,
  TransactionsCreateResponse,
  TransactionsDeleteData,
  TransactionsDeleteItemData,
  TransactionsDeleteItemResponse,
  TransactionsDeleteResponse,
  TransactionsUpdateData,
  TransactionsUpdateItemData,
  TransactionsUpdateItemResponse,
  TransactionsUpdateResponse,
  WebhooksCreateData,
  WebhooksCreateResponse,
  WebhooksDeleteData,
  WebhooksDeleteResponse,
  WebhooksSendTestDeliveryData,
  WebhooksSendTestDeliveryResponse,
  WebhooksUpdateData,
  WebhooksUpdateResponse,
} from '../generated/types.gen.js';

/**
 * The typed write surface over the gated /v1 API. Each method takes the
 * generated hey-api options envelope (`{ body, path, query, headers? }`) for its
 * op and resolves the unwrapped success payload (the created/updated resource).
 */
export interface WriteSurface {
  /** Create a budget line (`POST /projects/{projectId}/budget/lines`). */
  budgetCreateLine(data: BudgetCreateLineData): Promise<BudgetCreateLineResponse>;
  /** Create budget lines (`POST /projects/{projectId}/budget/lines/bulk`). */
  budgetCreateLinesBulk(data: BudgetCreateLinesBulkData): Promise<BudgetCreateLinesBulkResponse>;
  /** Create a budget phase (`POST /projects/{projectId}/budget/phases`). */
  budgetCreatePhase(data: BudgetCreatePhaseData): Promise<BudgetCreatePhaseResponse>;
  /** Delete a budget line (`DELETE /projects/{projectId}/budget/lines/{lineId}`). */
  budgetDeleteLine(data: BudgetDeleteLineData): Promise<BudgetDeleteLineResponse>;
  /** Delete a budget phase (`DELETE /projects/{projectId}/budget/phases/{phaseId}`). */
  budgetDeletePhase(data: BudgetDeletePhaseData): Promise<BudgetDeletePhaseResponse>;
  /** Update a budget line (`PATCH /projects/{projectId}/budget/lines/{lineId}`). */
  budgetUpdateLine(data: BudgetUpdateLineData): Promise<BudgetUpdateLineResponse>;
  /** Update phase data for a budget line (`PUT /projects/{projectId}/budget/lines/{lineId}/phase-data/{phaseId}`). */
  budgetUpdateLinePhaseData(data: BudgetUpdateLinePhaseDataData): Promise<BudgetUpdateLinePhaseDataResponse>;
  /** Update phase data for budget lines (`POST /projects/{projectId}/budget/lines/phase-data/bulk`). */
  budgetUpdateLinePhaseDataBulk(data: BudgetUpdateLinePhaseDataBulkData): Promise<BudgetUpdateLinePhaseDataBulkResponse>;
  /** Update a budget phase (`PATCH /projects/{projectId}/budget/phases/{phaseId}`). */
  budgetUpdatePhase(data: BudgetUpdatePhaseData): Promise<BudgetUpdatePhaseResponse>;
  /** Create a comment (`POST /projects/{projectId}/comments`). */
  commentsCreate(data: CommentsCreateData): Promise<CommentsCreateResponse>;
  /** Delete a comment (`DELETE /projects/{projectId}/comments/{commentId}`). */
  commentsDelete(data: CommentsDeleteData): Promise<CommentsDeleteResponse>;
  /** Update a comment (`PATCH /projects/{projectId}/comments/{commentId}`). */
  commentsUpdate(data: CommentsUpdateData): Promise<CommentsUpdateResponse>;
  /** Create a contact (`POST /contacts`). */
  contactsCreate(data: ContactsCreateData): Promise<ContactsCreateResponse>;
  /** Delete a contact (`DELETE /contacts/{contactId}`). */
  contactsDelete(data: ContactsDeleteData): Promise<ContactsDeleteResponse>;
  /** Update a contact (`PATCH /contacts/{contactId}`). */
  contactsUpdate(data: ContactsUpdateData): Promise<ContactsUpdateResponse>;
  /** Delete a document (`DELETE /documents/{documentId}`). */
  documentsDelete(data: DocumentsDeleteData): Promise<DocumentsDeleteResponse>;
  /** Link a document (`PUT /documents/{documentId}/links/{kind}`). */
  documentsLink(data: DocumentsLinkData): Promise<DocumentsLinkResponse>;
  /** Remove a document link (`DELETE /documents/{documentId}/links/{kind}`). */
  documentsUnlink(data: DocumentsUnlinkData): Promise<DocumentsUnlinkResponse>;
  /** Update a document (`PATCH /documents/{documentId}`). */
  documentsUpdate(data: DocumentsUpdateData): Promise<DocumentsUpdateResponse>;
  /** Add a currency to a project (`POST /projects/{projectId}/library/currencies`). */
  libraryAddProjectCurrency(data: LibraryAddProjectCurrencyData): Promise<LibraryAddProjectCurrencyResponse>;
  /** Add a fringe to a project (`POST /projects/{projectId}/library/fringes`). */
  libraryAddProjectFringe(data: LibraryAddProjectFringeData): Promise<LibraryAddProjectFringeResponse>;
  /** Add a fringe group to a project (`POST /projects/{projectId}/library/fringe-groups`). */
  libraryAddProjectFringeGroup(data: LibraryAddProjectFringeGroupData): Promise<LibraryAddProjectFringeGroupResponse>;
  /** Add a global to a project (`POST /projects/{projectId}/library/globals`). */
  libraryAddProjectGlobal(data: LibraryAddProjectGlobalData): Promise<LibraryAddProjectGlobalResponse>;
  /** Add an incentive to a project (`POST /projects/{projectId}/library/incentives`). */
  libraryAddProjectIncentive(data: LibraryAddProjectIncentiveData): Promise<LibraryAddProjectIncentiveResponse>;
  /** Create a currency (`POST /library/currencies`). */
  libraryCreateCurrency(data: LibraryCreateCurrencyData): Promise<LibraryCreateCurrencyResponse>;
  /** Create a fringe (`POST /library/fringes`). */
  libraryCreateFringe(data: LibraryCreateFringeData): Promise<LibraryCreateFringeResponse>;
  /** Create a fringe group (`POST /library/fringe-groups`). */
  libraryCreateFringeGroup(data: LibraryCreateFringeGroupData): Promise<LibraryCreateFringeGroupResponse>;
  /** Create a global (`POST /library/globals`). */
  libraryCreateGlobal(data: LibraryCreateGlobalData): Promise<LibraryCreateGlobalResponse>;
  /** Create a rate pack (`POST /library/rate-packs`). */
  libraryCreateRatePack(data: LibraryCreateRatePackData): Promise<LibraryCreateRatePackResponse>;
  /** Add a rate pack item (`POST /library/rate-packs/{packId}/items`). */
  libraryCreateRatePackItem(data: LibraryCreateRatePackItemData): Promise<LibraryCreateRatePackItemResponse>;
  /** Create a workspace tag (`POST /library/tags`). */
  libraryCreateTag(data: LibraryCreateTagData): Promise<LibraryCreateTagResponse>;
  /** Create a unit (`POST /library/units`). */
  libraryCreateUnit(data: LibraryCreateUnitData): Promise<LibraryCreateUnitResponse>;
  /** Delete a currency (`DELETE /library/currencies/{currencyId}`). */
  libraryDeleteCurrency(data: LibraryDeleteCurrencyData): Promise<LibraryDeleteCurrencyResponse>;
  /** Delete a fringe (`DELETE /library/fringes/{fringeId}`). */
  libraryDeleteFringe(data: LibraryDeleteFringeData): Promise<LibraryDeleteFringeResponse>;
  /** Delete a fringe group (`DELETE /library/fringe-groups/{fringeGroupId}`). */
  libraryDeleteFringeGroup(data: LibraryDeleteFringeGroupData): Promise<LibraryDeleteFringeGroupResponse>;
  /** Delete a global (`DELETE /library/globals/{globalId}`). */
  libraryDeleteGlobal(data: LibraryDeleteGlobalData): Promise<LibraryDeleteGlobalResponse>;
  /** Remove a project currency (`DELETE /projects/{projectId}/library/currencies/{currencyId}`). */
  libraryDeleteProjectCurrency(data: LibraryDeleteProjectCurrencyData): Promise<LibraryDeleteProjectCurrencyResponse>;
  /** Remove a project fringe (`DELETE /projects/{projectId}/library/fringes/{fringeId}`). */
  libraryDeleteProjectFringe(data: LibraryDeleteProjectFringeData): Promise<LibraryDeleteProjectFringeResponse>;
  /** Remove a project fringe group (`DELETE /projects/{projectId}/library/fringe-groups/{fringeGroupId}`). */
  libraryDeleteProjectFringeGroup(data: LibraryDeleteProjectFringeGroupData): Promise<LibraryDeleteProjectFringeGroupResponse>;
  /** Remove a project global (`DELETE /projects/{projectId}/library/globals/{globalId}`). */
  libraryDeleteProjectGlobal(data: LibraryDeleteProjectGlobalData): Promise<LibraryDeleteProjectGlobalResponse>;
  /** Remove a project incentive (`DELETE /projects/{projectId}/library/incentives/{incentiveId}`). */
  libraryDeleteProjectIncentive(data: LibraryDeleteProjectIncentiveData): Promise<LibraryDeleteProjectIncentiveResponse>;
  /** Delete a rate pack (`DELETE /library/rate-packs/{packId}`). */
  libraryDeleteRatePack(data: LibraryDeleteRatePackData): Promise<LibraryDeleteRatePackResponse>;
  /** Delete a rate pack item (`DELETE /library/rate-packs/{packId}/items/{itemId}`). */
  libraryDeleteRatePackItem(data: LibraryDeleteRatePackItemData): Promise<LibraryDeleteRatePackItemResponse>;
  /** Delete a workspace tag (`DELETE /library/tags/{tagId}`). */
  libraryDeleteTag(data: LibraryDeleteTagData): Promise<LibraryDeleteTagResponse>;
  /** Delete a unit (`DELETE /library/units/{unitId}`). */
  libraryDeleteUnit(data: LibraryDeleteUnitData): Promise<LibraryDeleteUnitResponse>;
  /** Disable an incentive pack for the workspace (`DELETE /library/incentive-packs/{packId}/enablement`). */
  libraryDisableIncentivePack(data: LibraryDisableIncentivePackData): Promise<LibraryDisableIncentivePackResponse>;
  /** Disable a rate pack for the workspace (`DELETE /library/rate-packs/{packId}/enablement`). */
  libraryDisableRatePack(data: LibraryDisableRatePackData): Promise<LibraryDisableRatePackResponse>;
  /** Enable an incentive pack for the workspace (`POST /library/incentive-packs/{packId}/enablement`). */
  libraryEnableIncentivePack(data: LibraryEnableIncentivePackData): Promise<LibraryEnableIncentivePackResponse>;
  /** Enable a rate pack for the workspace (`POST /library/rate-packs/{packId}/enablement`). */
  libraryEnableRatePack(data: LibraryEnableRatePackData): Promise<LibraryEnableRatePackResponse>;
  /** Update a currency (`PATCH /library/currencies/{currencyId}`). */
  libraryUpdateCurrency(data: LibraryUpdateCurrencyData): Promise<LibraryUpdateCurrencyResponse>;
  /** Update a fringe (`PATCH /library/fringes/{fringeId}`). */
  libraryUpdateFringe(data: LibraryUpdateFringeData): Promise<LibraryUpdateFringeResponse>;
  /** Update a fringe group (`PATCH /library/fringe-groups/{fringeGroupId}`). */
  libraryUpdateFringeGroup(data: LibraryUpdateFringeGroupData): Promise<LibraryUpdateFringeGroupResponse>;
  /** Update a global (`PATCH /library/globals/{globalId}`). */
  libraryUpdateGlobal(data: LibraryUpdateGlobalData): Promise<LibraryUpdateGlobalResponse>;
  /** Update a project currency (`PATCH /projects/{projectId}/library/currencies/{currencyId}`). */
  libraryUpdateProjectCurrency(data: LibraryUpdateProjectCurrencyData): Promise<LibraryUpdateProjectCurrencyResponse>;
  /** Update a project fringe (`PATCH /projects/{projectId}/library/fringes/{fringeId}`). */
  libraryUpdateProjectFringe(data: LibraryUpdateProjectFringeData): Promise<LibraryUpdateProjectFringeResponse>;
  /** Update a project fringe group (`PATCH /projects/{projectId}/library/fringe-groups/{fringeGroupId}`). */
  libraryUpdateProjectFringeGroup(data: LibraryUpdateProjectFringeGroupData): Promise<LibraryUpdateProjectFringeGroupResponse>;
  /** Update a project global (`PATCH /projects/{projectId}/library/globals/{globalId}`). */
  libraryUpdateProjectGlobal(data: LibraryUpdateProjectGlobalData): Promise<LibraryUpdateProjectGlobalResponse>;
  /** Update a project incentive (`PATCH /projects/{projectId}/library/incentives/{incentiveId}`). */
  libraryUpdateProjectIncentive(data: LibraryUpdateProjectIncentiveData): Promise<LibraryUpdateProjectIncentiveResponse>;
  /** Update a rate pack (`PATCH /library/rate-packs/{packId}`). */
  libraryUpdateRatePack(data: LibraryUpdateRatePackData): Promise<LibraryUpdateRatePackResponse>;
  /** Update a rate pack item (`PATCH /library/rate-packs/{packId}/items/{itemId}`). */
  libraryUpdateRatePackItem(data: LibraryUpdateRatePackItemData): Promise<LibraryUpdateRatePackItemResponse>;
  /** Update a workspace tag (`PATCH /library/tags/{tagId}`). */
  libraryUpdateTag(data: LibraryUpdateTagData): Promise<LibraryUpdateTagResponse>;
  /** Update a unit (`PATCH /library/units/{unitId}`). */
  libraryUpdateUnit(data: LibraryUpdateUnitData): Promise<LibraryUpdateUnitResponse>;
  /** Create a project (`POST /projects`). */
  projectsCreate(data: ProjectsCreateData): Promise<ProjectsCreateResponse>;
  /** Update a project (`PATCH /projects/{projectId}`). */
  projectsUpdate(data: ProjectsUpdateData): Promise<ProjectsUpdateResponse>;
  /** Cancel a pending submission (`POST /purchase-orders/{purchaseOrderId}/cancel-submission`). */
  purchaseOrdersCancelSubmission(data: PurchaseOrdersCancelSubmissionData): Promise<PurchaseOrdersCancelSubmissionResponse>;
  /** Create a purchase order (`POST /purchase-orders`). */
  purchaseOrdersCreate(data: PurchaseOrdersCreateData): Promise<PurchaseOrdersCreateResponse>;
  /** Add a purchase order item (`POST /purchase-orders/{purchaseOrderId}/items`). */
  purchaseOrdersCreateItem(data: PurchaseOrdersCreateItemData): Promise<PurchaseOrdersCreateItemResponse>;
  /** Delete a purchase order (`DELETE /purchase-orders/{purchaseOrderId}`). */
  purchaseOrdersDelete(data: PurchaseOrdersDeleteData): Promise<PurchaseOrdersDeleteResponse>;
  /** Delete a purchase order item (`DELETE /purchase-orders/{purchaseOrderId}/items/{itemId}`). */
  purchaseOrdersDeleteItem(data: PurchaseOrdersDeleteItemData): Promise<PurchaseOrdersDeleteItemResponse>;
  /** Link a transaction to a purchase order (`PUT /purchase-orders/{purchaseOrderId}/transactions/{transactionId}`). */
  purchaseOrdersLinkTransaction(data: PurchaseOrdersLinkTransactionData): Promise<PurchaseOrdersLinkTransactionResponse>;
  /** Mark a purchase order as paid (`POST /purchase-orders/{purchaseOrderId}/mark-paid`). */
  purchaseOrdersMarkPaid(data: PurchaseOrdersMarkPaidData): Promise<PurchaseOrdersMarkPaidResponse>;
  /** Unlink a transaction from a purchase order (`DELETE /purchase-orders/{purchaseOrderId}/transactions/{transactionId}`). */
  purchaseOrdersUnlinkTransaction(data: PurchaseOrdersUnlinkTransactionData): Promise<PurchaseOrdersUnlinkTransactionResponse>;
  /** Update a purchase order (`PATCH /purchase-orders/{purchaseOrderId}`). */
  purchaseOrdersUpdate(data: PurchaseOrdersUpdateData): Promise<PurchaseOrdersUpdateResponse>;
  /** Update a purchase order item (`PATCH /purchase-orders/{purchaseOrderId}/items/{itemId}`). */
  purchaseOrdersUpdateItem(data: PurchaseOrdersUpdateItemData): Promise<PurchaseOrdersUpdateItemResponse>;
  /** Void a purchase order (`POST /purchase-orders/{purchaseOrderId}/void`). */
  purchaseOrdersVoid(data: PurchaseOrdersVoidData): Promise<PurchaseOrdersVoidResponse>;
  /** Create a space (`POST /spaces`). */
  spacesCreate(data: SpacesCreateData): Promise<SpacesCreateResponse>;
  /** Delete a space (`DELETE /spaces/{spaceId}`). */
  spacesDelete(data: SpacesDeleteData): Promise<SpacesDeleteResponse>;
  /** Update a space (`PATCH /spaces/{spaceId}`). */
  spacesUpdate(data: SpacesUpdateData): Promise<SpacesUpdateResponse>;
  /** Create a manual transaction (`POST /transactions`). */
  transactionsCreate(data: TransactionsCreateData): Promise<TransactionsCreateResponse>;
  /** Create manual transactions in bulk (`POST /transactions/bulk`). */
  transactionsCreateBulk(data: TransactionsCreateBulkData): Promise<TransactionsCreateBulkResponse>;
  /** Add a transaction item (`POST /transactions/{transactionId}/items`). */
  transactionsCreateItem(data: TransactionsCreateItemData): Promise<TransactionsCreateItemResponse>;
  /** Delete a manual transaction (`DELETE /transactions/{transactionId}`). */
  transactionsDelete(data: TransactionsDeleteData): Promise<TransactionsDeleteResponse>;
  /** Delete a transaction item (`DELETE /transactions/{transactionId}/items/{itemId}`). */
  transactionsDeleteItem(data: TransactionsDeleteItemData): Promise<TransactionsDeleteItemResponse>;
  /** Update a transaction (`PATCH /transactions/{transactionId}`). */
  transactionsUpdate(data: TransactionsUpdateData): Promise<TransactionsUpdateResponse>;
  /** Update a transaction item (`PATCH /transactions/{transactionId}/items/{itemId}`). */
  transactionsUpdateItem(data: TransactionsUpdateItemData): Promise<TransactionsUpdateItemResponse>;
  /** Create a webhook subscription (`POST /webhooks`). */
  webhooksCreate(data: WebhooksCreateData): Promise<WebhooksCreateResponse>;
  /** Delete a webhook subscription (`DELETE /webhooks/{webhookId}`). */
  webhooksDelete(data: WebhooksDeleteData): Promise<WebhooksDeleteResponse>;
  /** Send a test delivery (`POST /webhooks/{webhookId}/test-delivery`). */
  webhooksSendTestDelivery(data: WebhooksSendTestDeliveryData): Promise<WebhooksSendTestDeliveryResponse>;
  /** Update a webhook subscription (`PATCH /webhooks/{webhookId}`). */
  webhooksUpdate(data: WebhooksUpdateData): Promise<WebhooksUpdateResponse>;
}
