// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// `createBridgeWriteSurface` — the interim {@link WriteSurface} implementation:
// every op forwards its typed `{ path, body, query }` to the generic in-process
// dispatcher ({@link WriteBridge.mutate}, built with `fetch: app.fetch`), so the
// body still flows bearerAuth -> CASL -> $transaction -> audit verbatim. Typing
// lives in each method's signature; the runtime is the generic gated bridge.
// Regenerate with:  pnpm --filter @saturation/sdk generate:mutate
//
// 94 write operations.

import type {
  BudgetCreateLineData,
  BudgetCreateLineResponse,
  BudgetCreateLinesBatchData,
  BudgetCreateLinesBatchResponse,
  BudgetCreatePhaseData,
  BudgetCreatePhaseResponse,
  BudgetDeleteLineData,
  BudgetDeleteLineResponse,
  BudgetDeletePhaseData,
  BudgetDeletePhaseResponse,
  BudgetUpdateLineData,
  BudgetUpdateLineResponse,
  BudgetUpdatePhaseData,
  BudgetUpdatePhaseResponse,
  BudgetUpsertLinePhaseDataBatchData,
  BudgetUpsertLinePhaseDataBatchResponse,
  BudgetUpsertLinePhaseDataData,
  BudgetUpsertLinePhaseDataResponse,
  DocumentsAssignData,
  DocumentsAssignResponse,
  DocumentsDeleteData,
  DocumentsDeleteResponse,
  DocumentsUnassignData,
  DocumentsUnassignResponse,
  DocumentsUpdateData,
  DocumentsUpdateResponse,
  LibraryAddProjectCurrencyData,
  LibraryAddProjectCurrencyResponse,
  LibraryAddProjectFringeData,
  LibraryAddProjectFringeResponse,
  LibraryAddProjectFringeTagData,
  LibraryAddProjectFringeTagResponse,
  LibraryAddProjectGlobalData,
  LibraryAddProjectGlobalResponse,
  LibraryAddProjectIncentiveData,
  LibraryAddProjectIncentiveResponse,
  LibraryAddProjectTagData,
  LibraryAddProjectTagResponse,
  LibraryAddRatePackData,
  LibraryAddRatePackResponse,
  LibraryCreateCurrencyTemplateData,
  LibraryCreateCurrencyTemplateResponse,
  LibraryCreateCustomUnitData,
  LibraryCreateCustomUnitResponse,
  LibraryCreateFringeTagTemplateData,
  LibraryCreateFringeTagTemplateResponse,
  LibraryCreateFringeTemplateData,
  LibraryCreateFringeTemplateResponse,
  LibraryCreateGlobalTemplateData,
  LibraryCreateGlobalTemplateResponse,
  LibraryCreateRatePackData,
  LibraryCreateRatePackItemData,
  LibraryCreateRatePackItemResponse,
  LibraryCreateRatePackResponse,
  LibraryCreateTagData,
  LibraryCreateTagResponse,
  LibraryDeleteCurrencyTemplateData,
  LibraryDeleteCurrencyTemplateResponse,
  LibraryDeleteCustomUnitData,
  LibraryDeleteCustomUnitResponse,
  LibraryDeleteFringeTagTemplateData,
  LibraryDeleteFringeTagTemplateResponse,
  LibraryDeleteFringeTemplateData,
  LibraryDeleteFringeTemplateResponse,
  LibraryDeleteGlobalTemplateData,
  LibraryDeleteGlobalTemplateResponse,
  LibraryDeleteProjectCurrencyData,
  LibraryDeleteProjectCurrencyResponse,
  LibraryDeleteProjectFringeData,
  LibraryDeleteProjectFringeResponse,
  LibraryDeleteProjectFringeTagData,
  LibraryDeleteProjectFringeTagResponse,
  LibraryDeleteProjectGlobalData,
  LibraryDeleteProjectGlobalResponse,
  LibraryDeleteProjectIncentiveData,
  LibraryDeleteProjectIncentiveResponse,
  LibraryDeleteRatePackData,
  LibraryDeleteRatePackItemData,
  LibraryDeleteRatePackItemResponse,
  LibraryDeleteRatePackResponse,
  LibraryDeleteTagData,
  LibraryDeleteTagResponse,
  LibraryDisableIncentivePackData,
  LibraryDisableIncentivePackResponse,
  LibraryDisableRatePackData,
  LibraryDisableRatePackResponse,
  LibraryEnableIncentivePackData,
  LibraryEnableIncentivePackResponse,
  LibraryEnableRatePackData,
  LibraryEnableRatePackResponse,
  LibraryRemoveProjectTagData,
  LibraryRemoveProjectTagResponse,
  LibraryRemoveRatePackData,
  LibraryRemoveRatePackResponse,
  LibraryUpdateCurrencyTemplateData,
  LibraryUpdateCurrencyTemplateResponse,
  LibraryUpdateCustomUnitData,
  LibraryUpdateCustomUnitResponse,
  LibraryUpdateFringeTagTemplateData,
  LibraryUpdateFringeTagTemplateResponse,
  LibraryUpdateFringeTemplateData,
  LibraryUpdateFringeTemplateResponse,
  LibraryUpdateGlobalTemplateData,
  LibraryUpdateGlobalTemplateResponse,
  LibraryUpdateProjectCurrencyData,
  LibraryUpdateProjectCurrencyResponse,
  LibraryUpdateProjectFringeData,
  LibraryUpdateProjectFringeResponse,
  LibraryUpdateProjectFringeTagData,
  LibraryUpdateProjectFringeTagResponse,
  LibraryUpdateProjectGlobalData,
  LibraryUpdateProjectGlobalResponse,
  LibraryUpdateProjectIncentiveData,
  LibraryUpdateProjectIncentiveResponse,
  LibraryUpdateRatePackData,
  LibraryUpdateRatePackItemData,
  LibraryUpdateRatePackItemResponse,
  LibraryUpdateRatePackResponse,
  LibraryUpdateTagData,
  LibraryUpdateTagResponse,
  MasterDataCreateCommentData,
  MasterDataCreateCommentResponse,
  MasterDataCreateContactData,
  MasterDataCreateContactResponse,
  MasterDataCreateProjectData,
  MasterDataCreateProjectResponse,
  MasterDataCreateSpaceData,
  MasterDataCreateSpaceResponse,
  MasterDataDeleteCommentData,
  MasterDataDeleteCommentResponse,
  MasterDataDeleteContactData,
  MasterDataDeleteContactResponse,
  MasterDataDeleteProjectData,
  MasterDataDeleteProjectResponse,
  MasterDataDeleteSpaceData,
  MasterDataDeleteSpaceResponse,
  MasterDataUpdateCommentData,
  MasterDataUpdateCommentResponse,
  MasterDataUpdateContactData,
  MasterDataUpdateContactResponse,
  MasterDataUpdateProjectData,
  MasterDataUpdateProjectResponse,
  MasterDataUpdateSpaceData,
  MasterDataUpdateSpaceResponse,
  PurchaseOrdersCancelSubmissionData,
  PurchaseOrdersCancelSubmissionResponse,
  PurchaseOrdersCreateData,
  PurchaseOrdersCreateItemData,
  PurchaseOrdersCreateItemResponse,
  PurchaseOrdersCreateResponse,
  PurchaseOrdersDeleteData,
  PurchaseOrdersDeleteItemData,
  PurchaseOrdersDeleteItemResponse,
  PurchaseOrdersDeleteResponse,
  PurchaseOrdersLinkData,
  PurchaseOrdersLinkResponse,
  PurchaseOrdersMarkPaidData,
  PurchaseOrdersMarkPaidResponse,
  PurchaseOrdersUnlinkData,
  PurchaseOrdersUnlinkResponse,
  PurchaseOrdersUpdateData,
  PurchaseOrdersUpdateItemData,
  PurchaseOrdersUpdateItemResponse,
  PurchaseOrdersUpdateResponse,
  PurchaseOrdersVoidData,
  PurchaseOrdersVoidResponse,
  TransactionsBatchCreateData,
  TransactionsBatchCreateResponse,
  TransactionsCreateData,
  TransactionsCreateResponse,
  TransactionsDeleteData,
  TransactionsDeleteResponse,
  TransactionsItemsCreateData,
  TransactionsItemsCreateResponse,
  TransactionsItemsDeleteData,
  TransactionsItemsDeleteResponse,
  TransactionsItemsUpdateData,
  TransactionsItemsUpdateResponse,
  TransactionsUpdateData,
  TransactionsUpdateResponse,
  WebhooksCreateData,
  WebhooksCreateResponse,
  WebhooksDeleteData,
  WebhooksDeleteResponse,
  WebhooksPingData,
  WebhooksPingResponse,
  WebhooksUpdateData,
  WebhooksUpdateResponse,
} from '../generated/types.gen.js';
import type { WriteSurface } from './write-surface.interface.gen.js';

/** Per-op call arguments forwarded to the dispatcher. */
export interface WriteBridgeArgs {
  path?: Record<string, unknown>;
  body?: unknown;
  query?: Record<string, unknown>;
  /** Request headers (the `Idempotency-Key` channel for keyed creates). */
  headers?: Record<string, string>;
}

/**
 * The minimal generic dispatcher the bridge surface delegates to. A
 * {@link MutateClient} (built with `fetch: app.fetch`) satisfies it: its
 * `mutate(op, args)` runs the op through the gated /v1 chain in-process.
 */
export interface WriteBridge {
  mutate(op: string, args: WriteBridgeArgs): Promise<unknown>;
  /**
   * Optional meta-aware dispatch: also surfaces whether the /v1 route answered
   * from a stored idempotency receipt (`Idempotency-Replayed: true`). Hosts
   * that need replay-visible output (the MCP write adapter) call this;
   * `MutateClient.mutateWithMeta` satisfies it.
   */
  mutateWithMeta?(op: string, args: WriteBridgeArgs): Promise<{ data: unknown; replayed: boolean }>;
}

/** A generated hey-api options envelope (the `<Op>Data` request shape). */
type OptionsEnvelope = {
  path?: unknown;
  body?: unknown;
  query?: unknown;
  headers?: unknown;
};

/**
 * Build a {@link WriteSurface} whose every op forwards to the generic dispatcher.
 * Compose it with native per-op implementations and `satisfies WriteSurface` to
 * prove the whole contract is still covered:
 *
 *   const surface = {
 *     ...createBridgeWriteSurface(bridge),
 *     budgetUpsertLinePhaseData: nativeUpsert, // hand-written, type-checked
 *   } satisfies WriteSurface;
 */
export function createBridgeWriteSurface(bridge: WriteBridge): WriteSurface {
  const forward = (op: string, data: OptionsEnvelope): Promise<unknown> =>
    bridge.mutate(op, {
      ...(data.path !== undefined ? { path: data.path as Record<string, unknown> } : {}),
      ...(data.body !== undefined ? { body: data.body } : {}),
      ...(data.query !== undefined ? { query: data.query as Record<string, unknown> } : {}),
      ...(data.headers !== undefined ? { headers: data.headers as Record<string, string> } : {}),
    });

  return {
    budgetCreateLine(data: BudgetCreateLineData): Promise<BudgetCreateLineResponse> {
      return forward('budgetCreateLine', data) as Promise<BudgetCreateLineResponse>;
    },
    budgetCreateLinesBatch(data: BudgetCreateLinesBatchData): Promise<BudgetCreateLinesBatchResponse> {
      return forward('budgetCreateLinesBatch', data) as Promise<BudgetCreateLinesBatchResponse>;
    },
    budgetCreatePhase(data: BudgetCreatePhaseData): Promise<BudgetCreatePhaseResponse> {
      return forward('budgetCreatePhase', data) as Promise<BudgetCreatePhaseResponse>;
    },
    budgetDeleteLine(data: BudgetDeleteLineData): Promise<BudgetDeleteLineResponse> {
      return forward('budgetDeleteLine', data) as Promise<BudgetDeleteLineResponse>;
    },
    budgetDeletePhase(data: BudgetDeletePhaseData): Promise<BudgetDeletePhaseResponse> {
      return forward('budgetDeletePhase', data) as Promise<BudgetDeletePhaseResponse>;
    },
    budgetUpdateLine(data: BudgetUpdateLineData): Promise<BudgetUpdateLineResponse> {
      return forward('budgetUpdateLine', data) as Promise<BudgetUpdateLineResponse>;
    },
    budgetUpdatePhase(data: BudgetUpdatePhaseData): Promise<BudgetUpdatePhaseResponse> {
      return forward('budgetUpdatePhase', data) as Promise<BudgetUpdatePhaseResponse>;
    },
    budgetUpsertLinePhaseData(data: BudgetUpsertLinePhaseDataData): Promise<BudgetUpsertLinePhaseDataResponse> {
      return forward('budgetUpsertLinePhaseData', data) as Promise<BudgetUpsertLinePhaseDataResponse>;
    },
    budgetUpsertLinePhaseDataBatch(data: BudgetUpsertLinePhaseDataBatchData): Promise<BudgetUpsertLinePhaseDataBatchResponse> {
      return forward('budgetUpsertLinePhaseDataBatch', data) as Promise<BudgetUpsertLinePhaseDataBatchResponse>;
    },
    documentsAssign(data: DocumentsAssignData): Promise<DocumentsAssignResponse> {
      return forward('documentsAssign', data) as Promise<DocumentsAssignResponse>;
    },
    documentsDelete(data: DocumentsDeleteData): Promise<DocumentsDeleteResponse> {
      return forward('documentsDelete', data) as Promise<DocumentsDeleteResponse>;
    },
    documentsUnassign(data: DocumentsUnassignData): Promise<DocumentsUnassignResponse> {
      return forward('documentsUnassign', data) as Promise<DocumentsUnassignResponse>;
    },
    documentsUpdate(data: DocumentsUpdateData): Promise<DocumentsUpdateResponse> {
      return forward('documentsUpdate', data) as Promise<DocumentsUpdateResponse>;
    },
    libraryAddProjectCurrency(data: LibraryAddProjectCurrencyData): Promise<LibraryAddProjectCurrencyResponse> {
      return forward('libraryAddProjectCurrency', data) as Promise<LibraryAddProjectCurrencyResponse>;
    },
    libraryAddProjectFringe(data: LibraryAddProjectFringeData): Promise<LibraryAddProjectFringeResponse> {
      return forward('libraryAddProjectFringe', data) as Promise<LibraryAddProjectFringeResponse>;
    },
    libraryAddProjectFringeTag(data: LibraryAddProjectFringeTagData): Promise<LibraryAddProjectFringeTagResponse> {
      return forward('libraryAddProjectFringeTag', data) as Promise<LibraryAddProjectFringeTagResponse>;
    },
    libraryAddProjectGlobal(data: LibraryAddProjectGlobalData): Promise<LibraryAddProjectGlobalResponse> {
      return forward('libraryAddProjectGlobal', data) as Promise<LibraryAddProjectGlobalResponse>;
    },
    libraryAddProjectIncentive(data: LibraryAddProjectIncentiveData): Promise<LibraryAddProjectIncentiveResponse> {
      return forward('libraryAddProjectIncentive', data) as Promise<LibraryAddProjectIncentiveResponse>;
    },
    libraryAddProjectTag(data: LibraryAddProjectTagData): Promise<LibraryAddProjectTagResponse> {
      return forward('libraryAddProjectTag', data) as Promise<LibraryAddProjectTagResponse>;
    },
    libraryAddRatePack(data: LibraryAddRatePackData): Promise<LibraryAddRatePackResponse> {
      return forward('libraryAddRatePack', data) as Promise<LibraryAddRatePackResponse>;
    },
    libraryCreateCurrencyTemplate(data: LibraryCreateCurrencyTemplateData): Promise<LibraryCreateCurrencyTemplateResponse> {
      return forward('libraryCreateCurrencyTemplate', data) as Promise<LibraryCreateCurrencyTemplateResponse>;
    },
    libraryCreateCustomUnit(data: LibraryCreateCustomUnitData): Promise<LibraryCreateCustomUnitResponse> {
      return forward('libraryCreateCustomUnit', data) as Promise<LibraryCreateCustomUnitResponse>;
    },
    libraryCreateFringeTagTemplate(data: LibraryCreateFringeTagTemplateData): Promise<LibraryCreateFringeTagTemplateResponse> {
      return forward('libraryCreateFringeTagTemplate', data) as Promise<LibraryCreateFringeTagTemplateResponse>;
    },
    libraryCreateFringeTemplate(data: LibraryCreateFringeTemplateData): Promise<LibraryCreateFringeTemplateResponse> {
      return forward('libraryCreateFringeTemplate', data) as Promise<LibraryCreateFringeTemplateResponse>;
    },
    libraryCreateGlobalTemplate(data: LibraryCreateGlobalTemplateData): Promise<LibraryCreateGlobalTemplateResponse> {
      return forward('libraryCreateGlobalTemplate', data) as Promise<LibraryCreateGlobalTemplateResponse>;
    },
    libraryCreateRatePack(data: LibraryCreateRatePackData): Promise<LibraryCreateRatePackResponse> {
      return forward('libraryCreateRatePack', data) as Promise<LibraryCreateRatePackResponse>;
    },
    libraryCreateRatePackItem(data: LibraryCreateRatePackItemData): Promise<LibraryCreateRatePackItemResponse> {
      return forward('libraryCreateRatePackItem', data) as Promise<LibraryCreateRatePackItemResponse>;
    },
    libraryCreateTag(data: LibraryCreateTagData): Promise<LibraryCreateTagResponse> {
      return forward('libraryCreateTag', data) as Promise<LibraryCreateTagResponse>;
    },
    libraryDeleteCurrencyTemplate(data: LibraryDeleteCurrencyTemplateData): Promise<LibraryDeleteCurrencyTemplateResponse> {
      return forward('libraryDeleteCurrencyTemplate', data) as Promise<LibraryDeleteCurrencyTemplateResponse>;
    },
    libraryDeleteCustomUnit(data: LibraryDeleteCustomUnitData): Promise<LibraryDeleteCustomUnitResponse> {
      return forward('libraryDeleteCustomUnit', data) as Promise<LibraryDeleteCustomUnitResponse>;
    },
    libraryDeleteFringeTagTemplate(data: LibraryDeleteFringeTagTemplateData): Promise<LibraryDeleteFringeTagTemplateResponse> {
      return forward('libraryDeleteFringeTagTemplate', data) as Promise<LibraryDeleteFringeTagTemplateResponse>;
    },
    libraryDeleteFringeTemplate(data: LibraryDeleteFringeTemplateData): Promise<LibraryDeleteFringeTemplateResponse> {
      return forward('libraryDeleteFringeTemplate', data) as Promise<LibraryDeleteFringeTemplateResponse>;
    },
    libraryDeleteGlobalTemplate(data: LibraryDeleteGlobalTemplateData): Promise<LibraryDeleteGlobalTemplateResponse> {
      return forward('libraryDeleteGlobalTemplate', data) as Promise<LibraryDeleteGlobalTemplateResponse>;
    },
    libraryDeleteProjectCurrency(data: LibraryDeleteProjectCurrencyData): Promise<LibraryDeleteProjectCurrencyResponse> {
      return forward('libraryDeleteProjectCurrency', data) as Promise<LibraryDeleteProjectCurrencyResponse>;
    },
    libraryDeleteProjectFringe(data: LibraryDeleteProjectFringeData): Promise<LibraryDeleteProjectFringeResponse> {
      return forward('libraryDeleteProjectFringe', data) as Promise<LibraryDeleteProjectFringeResponse>;
    },
    libraryDeleteProjectFringeTag(data: LibraryDeleteProjectFringeTagData): Promise<LibraryDeleteProjectFringeTagResponse> {
      return forward('libraryDeleteProjectFringeTag', data) as Promise<LibraryDeleteProjectFringeTagResponse>;
    },
    libraryDeleteProjectGlobal(data: LibraryDeleteProjectGlobalData): Promise<LibraryDeleteProjectGlobalResponse> {
      return forward('libraryDeleteProjectGlobal', data) as Promise<LibraryDeleteProjectGlobalResponse>;
    },
    libraryDeleteProjectIncentive(data: LibraryDeleteProjectIncentiveData): Promise<LibraryDeleteProjectIncentiveResponse> {
      return forward('libraryDeleteProjectIncentive', data) as Promise<LibraryDeleteProjectIncentiveResponse>;
    },
    libraryDeleteRatePack(data: LibraryDeleteRatePackData): Promise<LibraryDeleteRatePackResponse> {
      return forward('libraryDeleteRatePack', data) as Promise<LibraryDeleteRatePackResponse>;
    },
    libraryDeleteRatePackItem(data: LibraryDeleteRatePackItemData): Promise<LibraryDeleteRatePackItemResponse> {
      return forward('libraryDeleteRatePackItem', data) as Promise<LibraryDeleteRatePackItemResponse>;
    },
    libraryDeleteTag(data: LibraryDeleteTagData): Promise<LibraryDeleteTagResponse> {
      return forward('libraryDeleteTag', data) as Promise<LibraryDeleteTagResponse>;
    },
    libraryDisableIncentivePack(data: LibraryDisableIncentivePackData): Promise<LibraryDisableIncentivePackResponse> {
      return forward('libraryDisableIncentivePack', data) as Promise<LibraryDisableIncentivePackResponse>;
    },
    libraryDisableRatePack(data: LibraryDisableRatePackData): Promise<LibraryDisableRatePackResponse> {
      return forward('libraryDisableRatePack', data) as Promise<LibraryDisableRatePackResponse>;
    },
    libraryEnableIncentivePack(data: LibraryEnableIncentivePackData): Promise<LibraryEnableIncentivePackResponse> {
      return forward('libraryEnableIncentivePack', data) as Promise<LibraryEnableIncentivePackResponse>;
    },
    libraryEnableRatePack(data: LibraryEnableRatePackData): Promise<LibraryEnableRatePackResponse> {
      return forward('libraryEnableRatePack', data) as Promise<LibraryEnableRatePackResponse>;
    },
    libraryRemoveProjectTag(data: LibraryRemoveProjectTagData): Promise<LibraryRemoveProjectTagResponse> {
      return forward('libraryRemoveProjectTag', data) as Promise<LibraryRemoveProjectTagResponse>;
    },
    libraryRemoveRatePack(data: LibraryRemoveRatePackData): Promise<LibraryRemoveRatePackResponse> {
      return forward('libraryRemoveRatePack', data) as Promise<LibraryRemoveRatePackResponse>;
    },
    libraryUpdateCurrencyTemplate(data: LibraryUpdateCurrencyTemplateData): Promise<LibraryUpdateCurrencyTemplateResponse> {
      return forward('libraryUpdateCurrencyTemplate', data) as Promise<LibraryUpdateCurrencyTemplateResponse>;
    },
    libraryUpdateCustomUnit(data: LibraryUpdateCustomUnitData): Promise<LibraryUpdateCustomUnitResponse> {
      return forward('libraryUpdateCustomUnit', data) as Promise<LibraryUpdateCustomUnitResponse>;
    },
    libraryUpdateFringeTagTemplate(data: LibraryUpdateFringeTagTemplateData): Promise<LibraryUpdateFringeTagTemplateResponse> {
      return forward('libraryUpdateFringeTagTemplate', data) as Promise<LibraryUpdateFringeTagTemplateResponse>;
    },
    libraryUpdateFringeTemplate(data: LibraryUpdateFringeTemplateData): Promise<LibraryUpdateFringeTemplateResponse> {
      return forward('libraryUpdateFringeTemplate', data) as Promise<LibraryUpdateFringeTemplateResponse>;
    },
    libraryUpdateGlobalTemplate(data: LibraryUpdateGlobalTemplateData): Promise<LibraryUpdateGlobalTemplateResponse> {
      return forward('libraryUpdateGlobalTemplate', data) as Promise<LibraryUpdateGlobalTemplateResponse>;
    },
    libraryUpdateProjectCurrency(data: LibraryUpdateProjectCurrencyData): Promise<LibraryUpdateProjectCurrencyResponse> {
      return forward('libraryUpdateProjectCurrency', data) as Promise<LibraryUpdateProjectCurrencyResponse>;
    },
    libraryUpdateProjectFringe(data: LibraryUpdateProjectFringeData): Promise<LibraryUpdateProjectFringeResponse> {
      return forward('libraryUpdateProjectFringe', data) as Promise<LibraryUpdateProjectFringeResponse>;
    },
    libraryUpdateProjectFringeTag(data: LibraryUpdateProjectFringeTagData): Promise<LibraryUpdateProjectFringeTagResponse> {
      return forward('libraryUpdateProjectFringeTag', data) as Promise<LibraryUpdateProjectFringeTagResponse>;
    },
    libraryUpdateProjectGlobal(data: LibraryUpdateProjectGlobalData): Promise<LibraryUpdateProjectGlobalResponse> {
      return forward('libraryUpdateProjectGlobal', data) as Promise<LibraryUpdateProjectGlobalResponse>;
    },
    libraryUpdateProjectIncentive(data: LibraryUpdateProjectIncentiveData): Promise<LibraryUpdateProjectIncentiveResponse> {
      return forward('libraryUpdateProjectIncentive', data) as Promise<LibraryUpdateProjectIncentiveResponse>;
    },
    libraryUpdateRatePack(data: LibraryUpdateRatePackData): Promise<LibraryUpdateRatePackResponse> {
      return forward('libraryUpdateRatePack', data) as Promise<LibraryUpdateRatePackResponse>;
    },
    libraryUpdateRatePackItem(data: LibraryUpdateRatePackItemData): Promise<LibraryUpdateRatePackItemResponse> {
      return forward('libraryUpdateRatePackItem', data) as Promise<LibraryUpdateRatePackItemResponse>;
    },
    libraryUpdateTag(data: LibraryUpdateTagData): Promise<LibraryUpdateTagResponse> {
      return forward('libraryUpdateTag', data) as Promise<LibraryUpdateTagResponse>;
    },
    masterDataCreateComment(data: MasterDataCreateCommentData): Promise<MasterDataCreateCommentResponse> {
      return forward('masterDataCreateComment', data) as Promise<MasterDataCreateCommentResponse>;
    },
    masterDataCreateContact(data: MasterDataCreateContactData): Promise<MasterDataCreateContactResponse> {
      return forward('masterDataCreateContact', data) as Promise<MasterDataCreateContactResponse>;
    },
    masterDataCreateProject(data: MasterDataCreateProjectData): Promise<MasterDataCreateProjectResponse> {
      return forward('masterDataCreateProject', data) as Promise<MasterDataCreateProjectResponse>;
    },
    masterDataCreateSpace(data: MasterDataCreateSpaceData): Promise<MasterDataCreateSpaceResponse> {
      return forward('masterDataCreateSpace', data) as Promise<MasterDataCreateSpaceResponse>;
    },
    masterDataDeleteComment(data: MasterDataDeleteCommentData): Promise<MasterDataDeleteCommentResponse> {
      return forward('masterDataDeleteComment', data) as Promise<MasterDataDeleteCommentResponse>;
    },
    masterDataDeleteContact(data: MasterDataDeleteContactData): Promise<MasterDataDeleteContactResponse> {
      return forward('masterDataDeleteContact', data) as Promise<MasterDataDeleteContactResponse>;
    },
    masterDataDeleteProject(data: MasterDataDeleteProjectData): Promise<MasterDataDeleteProjectResponse> {
      return forward('masterDataDeleteProject', data) as Promise<MasterDataDeleteProjectResponse>;
    },
    masterDataDeleteSpace(data: MasterDataDeleteSpaceData): Promise<MasterDataDeleteSpaceResponse> {
      return forward('masterDataDeleteSpace', data) as Promise<MasterDataDeleteSpaceResponse>;
    },
    masterDataUpdateComment(data: MasterDataUpdateCommentData): Promise<MasterDataUpdateCommentResponse> {
      return forward('masterDataUpdateComment', data) as Promise<MasterDataUpdateCommentResponse>;
    },
    masterDataUpdateContact(data: MasterDataUpdateContactData): Promise<MasterDataUpdateContactResponse> {
      return forward('masterDataUpdateContact', data) as Promise<MasterDataUpdateContactResponse>;
    },
    masterDataUpdateProject(data: MasterDataUpdateProjectData): Promise<MasterDataUpdateProjectResponse> {
      return forward('masterDataUpdateProject', data) as Promise<MasterDataUpdateProjectResponse>;
    },
    masterDataUpdateSpace(data: MasterDataUpdateSpaceData): Promise<MasterDataUpdateSpaceResponse> {
      return forward('masterDataUpdateSpace', data) as Promise<MasterDataUpdateSpaceResponse>;
    },
    purchaseOrdersCancelSubmission(data: PurchaseOrdersCancelSubmissionData): Promise<PurchaseOrdersCancelSubmissionResponse> {
      return forward('purchaseOrdersCancelSubmission', data) as Promise<PurchaseOrdersCancelSubmissionResponse>;
    },
    purchaseOrdersCreate(data: PurchaseOrdersCreateData): Promise<PurchaseOrdersCreateResponse> {
      return forward('purchaseOrdersCreate', data) as Promise<PurchaseOrdersCreateResponse>;
    },
    purchaseOrdersCreateItem(data: PurchaseOrdersCreateItemData): Promise<PurchaseOrdersCreateItemResponse> {
      return forward('purchaseOrdersCreateItem', data) as Promise<PurchaseOrdersCreateItemResponse>;
    },
    purchaseOrdersDelete(data: PurchaseOrdersDeleteData): Promise<PurchaseOrdersDeleteResponse> {
      return forward('purchaseOrdersDelete', data) as Promise<PurchaseOrdersDeleteResponse>;
    },
    purchaseOrdersDeleteItem(data: PurchaseOrdersDeleteItemData): Promise<PurchaseOrdersDeleteItemResponse> {
      return forward('purchaseOrdersDeleteItem', data) as Promise<PurchaseOrdersDeleteItemResponse>;
    },
    purchaseOrdersLink(data: PurchaseOrdersLinkData): Promise<PurchaseOrdersLinkResponse> {
      return forward('purchaseOrdersLink', data) as Promise<PurchaseOrdersLinkResponse>;
    },
    purchaseOrdersMarkPaid(data: PurchaseOrdersMarkPaidData): Promise<PurchaseOrdersMarkPaidResponse> {
      return forward('purchaseOrdersMarkPaid', data) as Promise<PurchaseOrdersMarkPaidResponse>;
    },
    purchaseOrdersUnlink(data: PurchaseOrdersUnlinkData): Promise<PurchaseOrdersUnlinkResponse> {
      return forward('purchaseOrdersUnlink', data) as Promise<PurchaseOrdersUnlinkResponse>;
    },
    purchaseOrdersUpdate(data: PurchaseOrdersUpdateData): Promise<PurchaseOrdersUpdateResponse> {
      return forward('purchaseOrdersUpdate', data) as Promise<PurchaseOrdersUpdateResponse>;
    },
    purchaseOrdersUpdateItem(data: PurchaseOrdersUpdateItemData): Promise<PurchaseOrdersUpdateItemResponse> {
      return forward('purchaseOrdersUpdateItem', data) as Promise<PurchaseOrdersUpdateItemResponse>;
    },
    purchaseOrdersVoid(data: PurchaseOrdersVoidData): Promise<PurchaseOrdersVoidResponse> {
      return forward('purchaseOrdersVoid', data) as Promise<PurchaseOrdersVoidResponse>;
    },
    transactionsBatchCreate(data: TransactionsBatchCreateData): Promise<TransactionsBatchCreateResponse> {
      return forward('transactionsBatchCreate', data) as Promise<TransactionsBatchCreateResponse>;
    },
    transactionsCreate(data: TransactionsCreateData): Promise<TransactionsCreateResponse> {
      return forward('transactionsCreate', data) as Promise<TransactionsCreateResponse>;
    },
    transactionsDelete(data: TransactionsDeleteData): Promise<TransactionsDeleteResponse> {
      return forward('transactionsDelete', data) as Promise<TransactionsDeleteResponse>;
    },
    transactionsItemsCreate(data: TransactionsItemsCreateData): Promise<TransactionsItemsCreateResponse> {
      return forward('transactionsItemsCreate', data) as Promise<TransactionsItemsCreateResponse>;
    },
    transactionsItemsDelete(data: TransactionsItemsDeleteData): Promise<TransactionsItemsDeleteResponse> {
      return forward('transactionsItemsDelete', data) as Promise<TransactionsItemsDeleteResponse>;
    },
    transactionsItemsUpdate(data: TransactionsItemsUpdateData): Promise<TransactionsItemsUpdateResponse> {
      return forward('transactionsItemsUpdate', data) as Promise<TransactionsItemsUpdateResponse>;
    },
    transactionsUpdate(data: TransactionsUpdateData): Promise<TransactionsUpdateResponse> {
      return forward('transactionsUpdate', data) as Promise<TransactionsUpdateResponse>;
    },
    webhooksCreate(data: WebhooksCreateData): Promise<WebhooksCreateResponse> {
      return forward('webhooksCreate', data) as Promise<WebhooksCreateResponse>;
    },
    webhooksDelete(data: WebhooksDeleteData): Promise<WebhooksDeleteResponse> {
      return forward('webhooksDelete', data) as Promise<WebhooksDeleteResponse>;
    },
    webhooksPing(data: WebhooksPingData): Promise<WebhooksPingResponse> {
      return forward('webhooksPing', data) as Promise<WebhooksPingResponse>;
    },
    webhooksUpdate(data: WebhooksUpdateData): Promise<WebhooksUpdateResponse> {
      return forward('webhooksUpdate', data) as Promise<WebhooksUpdateResponse>;
    },
  } satisfies WriteSurface;
}
