// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// `createBridgeWriteSurface` — the interim {@link WriteSurface} implementation:
// every op forwards its typed `{ path, body, query }` to the generic in-process
// dispatcher ({@link WriteBridge.mutate}, built with `fetch: app.fetch`), so the
// body still flows bearerAuth -> CASL -> $transaction -> audit verbatim. Typing
// lives in each method's signature; the runtime is the generic gated bridge.
// Regenerate with:  pnpm --filter @saturation/sdk generate:mutate
//
// 61 write operations.

import type {
  BudgetCreateLineData,
  BudgetCreateLineResponse,
  BudgetCreateLinesBatchData,
  BudgetCreateLinesBatchResponse,
  BudgetCreatePhaseData,
  BudgetCreatePhaseResponse,
  BudgetDeleteLineData,
  BudgetDeleteLineResponse,
  BudgetDeletePhaseData,
  BudgetDeletePhaseResponse,
  BudgetUpdateLineData,
  BudgetUpdateLineResponse,
  BudgetUpdatePhaseData,
  BudgetUpdatePhaseResponse,
  BudgetUpsertLinePhaseDataBatchData,
  BudgetUpsertLinePhaseDataBatchResponse,
  BudgetUpsertLinePhaseDataData,
  BudgetUpsertLinePhaseDataResponse,
  DocumentsAssignData,
  DocumentsAssignResponse,
  DocumentsUpdateData,
  DocumentsUpdateResponse,
  LibraryAddProjectIncentiveData,
  LibraryAddProjectIncentiveResponse,
  LibraryAddRatePackData,
  LibraryAddRatePackResponse,
  LibraryCreateCurrencyTemplateData,
  LibraryCreateCurrencyTemplateResponse,
  LibraryCreateCustomUnitData,
  LibraryCreateCustomUnitResponse,
  LibraryCreateFringeTagTemplateData,
  LibraryCreateFringeTagTemplateResponse,
  LibraryCreateFringeTemplateData,
  LibraryCreateFringeTemplateResponse,
  LibraryCreateGlobalTemplateData,
  LibraryCreateGlobalTemplateResponse,
  LibraryCreateRatePackData,
  LibraryCreateRatePackItemData,
  LibraryCreateRatePackItemResponse,
  LibraryCreateRatePackResponse,
  LibraryCreateTagData,
  LibraryCreateTagResponse,
  LibraryEnableIncentivePackData,
  LibraryEnableIncentivePackResponse,
  LibraryEnableRatePackData,
  LibraryEnableRatePackResponse,
  LibraryUpdateCurrencyTemplateData,
  LibraryUpdateCurrencyTemplateResponse,
  LibraryUpdateCustomUnitData,
  LibraryUpdateCustomUnitResponse,
  LibraryUpdateFringeTagTemplateData,
  LibraryUpdateFringeTagTemplateResponse,
  LibraryUpdateFringeTemplateData,
  LibraryUpdateFringeTemplateResponse,
  LibraryUpdateGlobalTemplateData,
  LibraryUpdateGlobalTemplateResponse,
  LibraryUpdateProjectCurrencyData,
  LibraryUpdateProjectCurrencyResponse,
  LibraryUpdateProjectFringeData,
  LibraryUpdateProjectFringeResponse,
  LibraryUpdateProjectFringeTagData,
  LibraryUpdateProjectFringeTagResponse,
  LibraryUpdateProjectGlobalData,
  LibraryUpdateProjectGlobalResponse,
  LibraryUpdateProjectIncentiveData,
  LibraryUpdateProjectIncentiveResponse,
  LibraryUpdateRatePackData,
  LibraryUpdateRatePackItemData,
  LibraryUpdateRatePackItemResponse,
  LibraryUpdateRatePackResponse,
  LibraryUpdateTagData,
  LibraryUpdateTagResponse,
  MasterDataCreateCommentData,
  MasterDataCreateCommentResponse,
  MasterDataCreateContactData,
  MasterDataCreateContactResponse,
  MasterDataCreateProjectData,
  MasterDataCreateProjectResponse,
  MasterDataCreateSpaceData,
  MasterDataCreateSpaceResponse,
  MasterDataDeleteContactData,
  MasterDataDeleteContactResponse,
  MasterDataUpdateCommentData,
  MasterDataUpdateCommentResponse,
  MasterDataUpdateContactData,
  MasterDataUpdateContactResponse,
  MasterDataUpdateProjectData,
  MasterDataUpdateProjectResponse,
  MasterDataUpdateSpaceData,
  MasterDataUpdateSpaceResponse,
  PurchaseOrdersCancelSubmissionData,
  PurchaseOrdersCancelSubmissionResponse,
  PurchaseOrdersCreateData,
  PurchaseOrdersCreateItemData,
  PurchaseOrdersCreateItemResponse,
  PurchaseOrdersCreateResponse,
  PurchaseOrdersDeleteData,
  PurchaseOrdersDeleteResponse,
  PurchaseOrdersLinkData,
  PurchaseOrdersLinkResponse,
  PurchaseOrdersMarkPaidData,
  PurchaseOrdersMarkPaidResponse,
  PurchaseOrdersUnlinkData,
  PurchaseOrdersUnlinkResponse,
  PurchaseOrdersUpdateData,
  PurchaseOrdersUpdateItemData,
  PurchaseOrdersUpdateItemResponse,
  PurchaseOrdersUpdateResponse,
  PurchaseOrdersVoidData,
  PurchaseOrdersVoidResponse,
  TransactionsBatchCreateData,
  TransactionsBatchCreateResponse,
  TransactionsCreateData,
  TransactionsCreateResponse,
  TransactionsDeleteData,
  TransactionsDeleteResponse,
  TransactionsItemsCreateData,
  TransactionsItemsCreateResponse,
  TransactionsItemsUpdateData,
  TransactionsItemsUpdateResponse,
  TransactionsUpdateData,
  TransactionsUpdateResponse,
} from '../generated/types.gen.js';
import type { WriteSurface } from './write-surface.interface.gen.js';

/** Per-op call arguments forwarded to the dispatcher. */
export interface WriteBridgeArgs {
  path?: Record<string, unknown>;
  body?: unknown;
  query?: Record<string, unknown>;
  /** Request headers (the `Idempotency-Key` channel for keyed creates). */
  headers?: Record<string, string>;
}

/**
 * The minimal generic dispatcher the bridge surface delegates to. A
 * {@link MutateClient} (built with `fetch: app.fetch`) satisfies it: its
 * `mutate(op, args)` runs the op through the gated /v1 chain in-process.
 */
export interface WriteBridge {
  mutate(op: string, args: WriteBridgeArgs): Promise<unknown>;
  /**
   * Optional meta-aware dispatch: also surfaces whether the /v1 route answered
   * from a stored idempotency receipt (`Idempotency-Replayed: true`). Hosts
   * that need replay-visible output (the MCP write adapter) call this;
   * `MutateClient.mutateWithMeta` satisfies it.
   */
  mutateWithMeta?(op: string, args: WriteBridgeArgs): Promise<{ data: unknown; replayed: boolean }>;
}

/** A generated hey-api options envelope (the `<Op>Data` request shape). */
type OptionsEnvelope = {
  path?: unknown;
  body?: unknown;
  query?: unknown;
  headers?: unknown;
};

/**
 * Build a {@link WriteSurface} whose every op forwards to the generic dispatcher.
 * Compose it with native per-op implementations and `satisfies WriteSurface` to
 * prove the whole contract is still covered:
 *
 *   const surface = {
 *     ...createBridgeWriteSurface(bridge),
 *     budgetUpsertLinePhaseData: nativeUpsert, // hand-written, type-checked
 *   } satisfies WriteSurface;
 */
export function createBridgeWriteSurface(bridge: WriteBridge): WriteSurface {
  const forward = (op: string, data: OptionsEnvelope): Promise<unknown> =>
    bridge.mutate(op, {
      ...(data.path !== undefined ? { path: data.path as Record<string, unknown> } : {}),
      ...(data.body !== undefined ? { body: data.body } : {}),
      ...(data.query !== undefined ? { query: data.query as Record<string, unknown> } : {}),
      ...(data.headers !== undefined ? { headers: data.headers as Record<string, string> } : {}),
    });

  return {
    budgetCreateLine(data: BudgetCreateLineData): Promise<BudgetCreateLineResponse> {
      return forward('budgetCreateLine', data) as Promise<BudgetCreateLineResponse>;
    },
    budgetCreateLinesBatch(data: BudgetCreateLinesBatchData): Promise<BudgetCreateLinesBatchResponse> {
      return forward('budgetCreateLinesBatch', data) as Promise<BudgetCreateLinesBatchResponse>;
    },
    budgetCreatePhase(data: BudgetCreatePhaseData): Promise<BudgetCreatePhaseResponse> {
      return forward('budgetCreatePhase', data) as Promise<BudgetCreatePhaseResponse>;
    },
    budgetDeleteLine(data: BudgetDeleteLineData): Promise<BudgetDeleteLineResponse> {
      return forward('budgetDeleteLine', data) as Promise<BudgetDeleteLineResponse>;
    },
    budgetDeletePhase(data: BudgetDeletePhaseData): Promise<BudgetDeletePhaseResponse> {
      return forward('budgetDeletePhase', data) as Promise<BudgetDeletePhaseResponse>;
    },
    budgetUpdateLine(data: BudgetUpdateLineData): Promise<BudgetUpdateLineResponse> {
      return forward('budgetUpdateLine', data) as Promise<BudgetUpdateLineResponse>;
    },
    budgetUpdatePhase(data: BudgetUpdatePhaseData): Promise<BudgetUpdatePhaseResponse> {
      return forward('budgetUpdatePhase', data) as Promise<BudgetUpdatePhaseResponse>;
    },
    budgetUpsertLinePhaseData(data: BudgetUpsertLinePhaseDataData): Promise<BudgetUpsertLinePhaseDataResponse> {
      return forward('budgetUpsertLinePhaseData', data) as Promise<BudgetUpsertLinePhaseDataResponse>;
    },
    budgetUpsertLinePhaseDataBatch(data: BudgetUpsertLinePhaseDataBatchData): Promise<BudgetUpsertLinePhaseDataBatchResponse> {
      return forward('budgetUpsertLinePhaseDataBatch', data) as Promise<BudgetUpsertLinePhaseDataBatchResponse>;
    },
    documentsAssign(data: DocumentsAssignData): Promise<DocumentsAssignResponse> {
      return forward('documentsAssign', data) as Promise<DocumentsAssignResponse>;
    },
    documentsUpdate(data: DocumentsUpdateData): Promise<DocumentsUpdateResponse> {
      return forward('documentsUpdate', data) as Promise<DocumentsUpdateResponse>;
    },
    libraryAddProjectIncentive(data: LibraryAddProjectIncentiveData): Promise<LibraryAddProjectIncentiveResponse> {
      return forward('libraryAddProjectIncentive', data) as Promise<LibraryAddProjectIncentiveResponse>;
    },
    libraryAddRatePack(data: LibraryAddRatePackData): Promise<LibraryAddRatePackResponse> {
      return forward('libraryAddRatePack', data) as Promise<LibraryAddRatePackResponse>;
    },
    libraryCreateCurrencyTemplate(data: LibraryCreateCurrencyTemplateData): Promise<LibraryCreateCurrencyTemplateResponse> {
      return forward('libraryCreateCurrencyTemplate', data) as Promise<LibraryCreateCurrencyTemplateResponse>;
    },
    libraryCreateCustomUnit(data: LibraryCreateCustomUnitData): Promise<LibraryCreateCustomUnitResponse> {
      return forward('libraryCreateCustomUnit', data) as Promise<LibraryCreateCustomUnitResponse>;
    },
    libraryCreateFringeTagTemplate(data: LibraryCreateFringeTagTemplateData): Promise<LibraryCreateFringeTagTemplateResponse> {
      return forward('libraryCreateFringeTagTemplate', data) as Promise<LibraryCreateFringeTagTemplateResponse>;
    },
    libraryCreateFringeTemplate(data: LibraryCreateFringeTemplateData): Promise<LibraryCreateFringeTemplateResponse> {
      return forward('libraryCreateFringeTemplate', data) as Promise<LibraryCreateFringeTemplateResponse>;
    },
    libraryCreateGlobalTemplate(data: LibraryCreateGlobalTemplateData): Promise<LibraryCreateGlobalTemplateResponse> {
      return forward('libraryCreateGlobalTemplate', data) as Promise<LibraryCreateGlobalTemplateResponse>;
    },
    libraryCreateRatePack(data: LibraryCreateRatePackData): Promise<LibraryCreateRatePackResponse> {
      return forward('libraryCreateRatePack', data) as Promise<LibraryCreateRatePackResponse>;
    },
    libraryCreateRatePackItem(data: LibraryCreateRatePackItemData): Promise<LibraryCreateRatePackItemResponse> {
      return forward('libraryCreateRatePackItem', data) as Promise<LibraryCreateRatePackItemResponse>;
    },
    libraryCreateTag(data: LibraryCreateTagData): Promise<LibraryCreateTagResponse> {
      return forward('libraryCreateTag', data) as Promise<LibraryCreateTagResponse>;
    },
    libraryEnableIncentivePack(data: LibraryEnableIncentivePackData): Promise<LibraryEnableIncentivePackResponse> {
      return forward('libraryEnableIncentivePack', data) as Promise<LibraryEnableIncentivePackResponse>;
    },
    libraryEnableRatePack(data: LibraryEnableRatePackData): Promise<LibraryEnableRatePackResponse> {
      return forward('libraryEnableRatePack', data) as Promise<LibraryEnableRatePackResponse>;
    },
    libraryUpdateCurrencyTemplate(data: LibraryUpdateCurrencyTemplateData): Promise<LibraryUpdateCurrencyTemplateResponse> {
      return forward('libraryUpdateCurrencyTemplate', data) as Promise<LibraryUpdateCurrencyTemplateResponse>;
    },
    libraryUpdateCustomUnit(data: LibraryUpdateCustomUnitData): Promise<LibraryUpdateCustomUnitResponse> {
      return forward('libraryUpdateCustomUnit', data) as Promise<LibraryUpdateCustomUnitResponse>;
    },
    libraryUpdateFringeTagTemplate(data: LibraryUpdateFringeTagTemplateData): Promise<LibraryUpdateFringeTagTemplateResponse> {
      return forward('libraryUpdateFringeTagTemplate', data) as Promise<LibraryUpdateFringeTagTemplateResponse>;
    },
    libraryUpdateFringeTemplate(data: LibraryUpdateFringeTemplateData): Promise<LibraryUpdateFringeTemplateResponse> {
      return forward('libraryUpdateFringeTemplate', data) as Promise<LibraryUpdateFringeTemplateResponse>;
    },
    libraryUpdateGlobalTemplate(data: LibraryUpdateGlobalTemplateData): Promise<LibraryUpdateGlobalTemplateResponse> {
      return forward('libraryUpdateGlobalTemplate', data) as Promise<LibraryUpdateGlobalTemplateResponse>;
    },
    libraryUpdateProjectCurrency(data: LibraryUpdateProjectCurrencyData): Promise<LibraryUpdateProjectCurrencyResponse> {
      return forward('libraryUpdateProjectCurrency', data) as Promise<LibraryUpdateProjectCurrencyResponse>;
    },
    libraryUpdateProjectFringe(data: LibraryUpdateProjectFringeData): Promise<LibraryUpdateProjectFringeResponse> {
      return forward('libraryUpdateProjectFringe', data) as Promise<LibraryUpdateProjectFringeResponse>;
    },
    libraryUpdateProjectFringeTag(data: LibraryUpdateProjectFringeTagData): Promise<LibraryUpdateProjectFringeTagResponse> {
      return forward('libraryUpdateProjectFringeTag', data) as Promise<LibraryUpdateProjectFringeTagResponse>;
    },
    libraryUpdateProjectGlobal(data: LibraryUpdateProjectGlobalData): Promise<LibraryUpdateProjectGlobalResponse> {
      return forward('libraryUpdateProjectGlobal', data) as Promise<LibraryUpdateProjectGlobalResponse>;
    },
    libraryUpdateProjectIncentive(data: LibraryUpdateProjectIncentiveData): Promise<LibraryUpdateProjectIncentiveResponse> {
      return forward('libraryUpdateProjectIncentive', data) as Promise<LibraryUpdateProjectIncentiveResponse>;
    },
    libraryUpdateRatePack(data: LibraryUpdateRatePackData): Promise<LibraryUpdateRatePackResponse> {
      return forward('libraryUpdateRatePack', data) as Promise<LibraryUpdateRatePackResponse>;
    },
    libraryUpdateRatePackItem(data: LibraryUpdateRatePackItemData): Promise<LibraryUpdateRatePackItemResponse> {
      return forward('libraryUpdateRatePackItem', data) as Promise<LibraryUpdateRatePackItemResponse>;
    },
    libraryUpdateTag(data: LibraryUpdateTagData): Promise<LibraryUpdateTagResponse> {
      return forward('libraryUpdateTag', data) as Promise<LibraryUpdateTagResponse>;
    },
    masterDataCreateComment(data: MasterDataCreateCommentData): Promise<MasterDataCreateCommentResponse> {
      return forward('masterDataCreateComment', data) as Promise<MasterDataCreateCommentResponse>;
    },
    masterDataCreateContact(data: MasterDataCreateContactData): Promise<MasterDataCreateContactResponse> {
      return forward('masterDataCreateContact', data) as Promise<MasterDataCreateContactResponse>;
    },
    masterDataCreateProject(data: MasterDataCreateProjectData): Promise<MasterDataCreateProjectResponse> {
      return forward('masterDataCreateProject', data) as Promise<MasterDataCreateProjectResponse>;
    },
    masterDataCreateSpace(data: MasterDataCreateSpaceData): Promise<MasterDataCreateSpaceResponse> {
      return forward('masterDataCreateSpace', data) as Promise<MasterDataCreateSpaceResponse>;
    },
    masterDataDeleteContact(data: MasterDataDeleteContactData): Promise<MasterDataDeleteContactResponse> {
      return forward('masterDataDeleteContact', data) as Promise<MasterDataDeleteContactResponse>;
    },
    masterDataUpdateComment(data: MasterDataUpdateCommentData): Promise<MasterDataUpdateCommentResponse> {
      return forward('masterDataUpdateComment', data) as Promise<MasterDataUpdateCommentResponse>;
    },
    masterDataUpdateContact(data: MasterDataUpdateContactData): Promise<MasterDataUpdateContactResponse> {
      return forward('masterDataUpdateContact', data) as Promise<MasterDataUpdateContactResponse>;
    },
    masterDataUpdateProject(data: MasterDataUpdateProjectData): Promise<MasterDataUpdateProjectResponse> {
      return forward('masterDataUpdateProject', data) as Promise<MasterDataUpdateProjectResponse>;
    },
    masterDataUpdateSpace(data: MasterDataUpdateSpaceData): Promise<MasterDataUpdateSpaceResponse> {
      return forward('masterDataUpdateSpace', data) as Promise<MasterDataUpdateSpaceResponse>;
    },
    purchaseOrdersCancelSubmission(data: PurchaseOrdersCancelSubmissionData): Promise<PurchaseOrdersCancelSubmissionResponse> {
      return forward('purchaseOrdersCancelSubmission', data) as Promise<PurchaseOrdersCancelSubmissionResponse>;
    },
    purchaseOrdersCreate(data: PurchaseOrdersCreateData): Promise<PurchaseOrdersCreateResponse> {
      return forward('purchaseOrdersCreate', data) as Promise<PurchaseOrdersCreateResponse>;
    },
    purchaseOrdersCreateItem(data: PurchaseOrdersCreateItemData): Promise<PurchaseOrdersCreateItemResponse> {
      return forward('purchaseOrdersCreateItem', data) as Promise<PurchaseOrdersCreateItemResponse>;
    },
    purchaseOrdersDelete(data: PurchaseOrdersDeleteData): Promise<PurchaseOrdersDeleteResponse> {
      return forward('purchaseOrdersDelete', data) as Promise<PurchaseOrdersDeleteResponse>;
    },
    purchaseOrdersLink(data: PurchaseOrdersLinkData): Promise<PurchaseOrdersLinkResponse> {
      return forward('purchaseOrdersLink', data) as Promise<PurchaseOrdersLinkResponse>;
    },
    purchaseOrdersMarkPaid(data: PurchaseOrdersMarkPaidData): Promise<PurchaseOrdersMarkPaidResponse> {
      return forward('purchaseOrdersMarkPaid', data) as Promise<PurchaseOrdersMarkPaidResponse>;
    },
    purchaseOrdersUnlink(data: PurchaseOrdersUnlinkData): Promise<PurchaseOrdersUnlinkResponse> {
      return forward('purchaseOrdersUnlink', data) as Promise<PurchaseOrdersUnlinkResponse>;
    },
    purchaseOrdersUpdate(data: PurchaseOrdersUpdateData): Promise<PurchaseOrdersUpdateResponse> {
      return forward('purchaseOrdersUpdate', data) as Promise<PurchaseOrdersUpdateResponse>;
    },
    purchaseOrdersUpdateItem(data: PurchaseOrdersUpdateItemData): Promise<PurchaseOrdersUpdateItemResponse> {
      return forward('purchaseOrdersUpdateItem', data) as Promise<PurchaseOrdersUpdateItemResponse>;
    },
    purchaseOrdersVoid(data: PurchaseOrdersVoidData): Promise<PurchaseOrdersVoidResponse> {
      return forward('purchaseOrdersVoid', data) as Promise<PurchaseOrdersVoidResponse>;
    },
    transactionsBatchCreate(data: TransactionsBatchCreateData): Promise<TransactionsBatchCreateResponse> {
      return forward('transactionsBatchCreate', data) as Promise<TransactionsBatchCreateResponse>;
    },
    transactionsCreate(data: TransactionsCreateData): Promise<TransactionsCreateResponse> {
      return forward('transactionsCreate', data) as Promise<TransactionsCreateResponse>;
    },
    transactionsDelete(data: TransactionsDeleteData): Promise<TransactionsDeleteResponse> {
      return forward('transactionsDelete', data) as Promise<TransactionsDeleteResponse>;
    },
    transactionsItemsCreate(data: TransactionsItemsCreateData): Promise<TransactionsItemsCreateResponse> {
      return forward('transactionsItemsCreate', data) as Promise<TransactionsItemsCreateResponse>;
    },
    transactionsItemsUpdate(data: TransactionsItemsUpdateData): Promise<TransactionsItemsUpdateResponse> {
      return forward('transactionsItemsUpdate', data) as Promise<TransactionsItemsUpdateResponse>;
    },
    transactionsUpdate(data: TransactionsUpdateData): Promise<TransactionsUpdateResponse> {
      return forward('transactionsUpdate', data) as Promise<TransactionsUpdateResponse>;
    },
  } satisfies WriteSurface;
}
