/**
 * Generate the `mutate` write surface from the generated SDK.
 *
 * The `mutate` tool's model-facing surface is an **explicit write allowlist** over
 * the generated `/v1` SDK — NOT a naive `POST/PUT/PATCH/DELETE` verb filter (some
 * POSTs are state-transition / computed actions, not data writes). This script:
 *
 *   1. Parses the do-not-edit `src/generated/sdk.gen.ts` (one block per operation:
 *      JSDoc summary + `export const <op> = … .<method>({ url: '<url>' … })`).
 *   2. Keeps ONLY allowlisted PATCH/PUT value updates. POST operations remain
 *      excluded until durable retry identity is enforced end-to-end; DELETE and
 *      destructive/lifecycle actions are excluded by construction. Fail-safe: a
 *      new write op is invisible until it is explicitly reviewed here.
 *   3. Emits three artifacts, all keyed off the SAME allowlist so they cannot
 *      drift from each other or from the real route set:
 *      - `src/mutate/write-surface.gen.ts`: the typed write-op METADATA table the
 *        generic dispatcher and the agent tool description consume.
 *      - `src/mutate/write-surface.interface.gen.ts`: the typed `WriteSurface`
 *        CONTRACT — one `<op>(data: <Op>Data): Promise<<Op>Response>` method per
 *        allowlisted op, request/response types imported from the generated
 *        `types.gen.ts`. This is the autogenerated interface an implementation
 *        must satisfy; when the OpenAPI (and thus the generated types) changes,
 *        the regenerated interface forces every `satisfies WriteSurface`
 *        implementation to update or fail `tsc`.
 *      - `src/mutate/write-surface.bridge.gen.ts`: `createBridgeWriteSurface`, a
 *        ready-made `WriteSurface` whose every method forwards its typed
 *        `{ path, body, query }` to the generic in-process dispatcher (the
 *        app.fetch bridge). Hosts compose this with hand-written native ops
 *        (e.g. the in-memory budget path) and `satisfies WriteSurface` proves the
 *        composition still covers the whole contract.
 *
 * Re-run after any SDK regeneration: pnpm generate:mutate
 *
 * The allowlist is the security boundary; everything else is derived from the
 * spec by code, so the surface cannot drift from the real route set.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SDK_GEN = join(HERE, '../src/generated/sdk.gen.ts');
const TYPES_GEN = join(HERE, '../src/generated/types.gen.ts');
const OUT = join(HERE, '../src/mutate/write-surface.gen.ts');
const OUT_INTERFACE = join(HERE, '../src/mutate/write-surface.interface.gen.ts');
const OUT_BRIDGE = join(HERE, '../src/mutate/write-surface.bridge.gen.ts');

/**
 * HTTP verbs a data write can use. DELETE joined 2026-08-02 (Simon's
 * #development ruling): the five reviewed row deletes are SOFT deletes behind
 * their routes' lifecycle rules, a gap in the surface rather than a finance
 * boundary. Hard deletes stay absent.
 */
type WriteMethod = 'post' | 'put' | 'patch' | 'delete';

/**
 * The source v1 write inventory. The final hosted surface below narrows this to
 * retry-safe PATCH/PUT value updates.
 *
 * Curated from the route inventory. Excluded on purpose (NOT a write, or
 * destructive/deferred to the rollback ledger): every `*Delete*` EXCEPT the
 * five reviewed soft deletes admitted 2026-08-02, plus
 * `documentsUnlink`, `library{Disable,Remove}*`, and `webhooksSendTestDelivery` (a
 * side-effecting test action, not a data write — the exact "computed POST" a
 * verb filter would leak). The PO lifecycle (`Unlink` included; `Submit`
 * still reserved — the /v1 stub always 409s) was admitted 2026-08-07 (Simon's write-surface ruling for the write-audit
 * program): transitions are guarded by the routes' own status preconditions.
 */
const WRITE_OP_ALLOWLIST: ReadonlySet<string> = new Set<string>([
  // ── budget: create lines/phases, set/upsert phase-data (value edits) ──
  'budgetCreateLine',
  'budgetCreateLinesBulk',
  'budgetCreatePhase',
  'budgetUpdateLinePhaseData',
  'budgetUpdateLinePhaseDataBulk',
  'budgetUpdateLine',
  'budgetUpdatePhase',
  // ── reviewed soft deletes (Simon, 2026-08-02): the row keeps a deletedAt
  //    tombstone; each route's own lifecycle rules stand (journal-only
  //    transaction delete, draft-only PO delete) ──
  'transactionsDelete',
  'contactsDelete',
  'budgetDeleteLine',
  'budgetDeletePhase',
  'purchaseOrdersDelete',
  // ── documents: drop (create) + assign (link) + field update ──
  'documentsUpload',
  'documentsLink',
  'documentsUpdate',
  // ── library: workspace templates + project installs (additive) + field updates ──
  'libraryAddProjectCurrency',
  'libraryAddProjectFringe',
  'libraryAddProjectFringeGroup',
  'libraryAddProjectGlobal',
  'libraryAddProjectIncentive',
  'libraryAddRatePack',
  'libraryCreateCurrency',
  'libraryCreateUnit',
  'libraryCreateFringeGroup',
  'libraryCreateFringe',
  'libraryCreateGlobal',
  'libraryCreateRatePack',
  'libraryCreateRatePackItem',
  'libraryCreateTag',
  'libraryEnableIncentivePack',
  'libraryEnableRatePack',
  'libraryUpdateCurrency',
  'libraryUpdateUnit',
  'libraryUpdateFringeGroup',
  'libraryUpdateFringe',
  'libraryUpdateGlobal',
  'libraryUpdateProjectCurrency',
  'libraryUpdateProjectFringe',
  'libraryUpdateProjectFringeGroup',
  'libraryUpdateProjectGlobal',
  'libraryUpdateProjectIncentive',
  'libraryUpdateRatePack',
  'libraryUpdateRatePackItem',
  'libraryUpdateTag',
  // ── master data: contacts / projects / spaces / comments ──
  'commentsCreate',
  'contactsCreate',
  'projectsCreate',
  'spacesCreate',
  'commentsUpdate',
  'contactsUpdate',
  'projectsUpdate',
  'spacesUpdate',
  // ── purchase orders: create header/item, link to budget, field updates ──
  'purchaseOrdersCreate',
  'purchaseOrdersCreateItem',
  'purchaseOrdersCancelSubmission',
  'purchaseOrdersMarkPaid',
  'purchaseOrdersLinkTransaction',
  'purchaseOrdersUnlinkTransaction',
  'purchaseOrdersUpdate',
  'purchaseOrdersUpdateItem',
  'purchaseOrdersVoid',
  // ── transactions: create (single + batch), items, field updates ──
  'transactionsCreate',
  'transactionsCreateBulk',
  'transactionsCreateItem',
  'transactionsUpdate',
  'transactionsUpdateItem',
  // ── webhooks: full config surface ──
  'webhooksCreate',
  'webhooksUpdate',
  // ── full-surface ruling additions (2026-08-07): remaining deletes,
  //    disable/remove/unassign, webhook delete + ping ──
  'documentsDelete',
  'documentsUnlink',
  'libraryDeleteCurrency',
  'libraryDeleteUnit',
  'libraryDeleteFringeGroup',
  'libraryDeleteFringe',
  'libraryDeleteGlobal',
  'libraryDeleteProjectCurrency',
  'libraryDeleteProjectFringe',
  'libraryDeleteProjectFringeGroup',
  'libraryDeleteProjectGlobal',
  'libraryDeleteProjectIncentive',
  'libraryDeleteRatePack',
  'libraryDeleteRatePackItem',
  'libraryDeleteTag',
  'libraryDisableIncentivePack',
  'libraryDisableRatePack',
  'libraryRemoveRatePack',
  'commentsDelete',
  'spacesDelete',
  'purchaseOrdersDeleteItem',
  'transactionsDeleteItem',
  'webhooksDelete',
  'webhooksSendTestDelivery',
]);

/**
 * The canonical model-facing write surface: one explicit list, no
 * verb filter. POSTs re-admitted 2026-07-28 — durable transactional
 * idempotency receipts (next-api) enforce retry identity end-to-end, and the
 * declaration gate below proves every keyed create declares its REQUIRED
 * `Idempotency-Key` header in the generated types (so an outcome-ambiguous
 * timeout replays instead of duplicating).
 *
 * FULL SURFACE (Simon, 2026-08-07): the exposed set IS the allowlist — every
 * op above ships in the model-facing catalog. The only /v1 writes absent are
 * the two structural carve-outs documented on the allowlist
 * (`purchaseOrdersSubmit` reserved stub, `documentsUpload` upload-tool bytes).
 */
const AGENT_WRITE_EXPOSED_OPS: readonly string[] = [
  // ── value updates (the pre-existing exposed set) ──
  'budgetUpdateLine',
  'budgetUpdatePhase',
  'budgetUpdateLinePhaseData',
  'documentsUpdate',
  'libraryUpdateCurrency',
  'libraryUpdateUnit',
  'libraryUpdateFringeGroup',
  'libraryUpdateFringe',
  'libraryUpdateGlobal',
  'libraryUpdateProjectCurrency',
  'libraryUpdateProjectFringe',
  'libraryUpdateProjectFringeGroup',
  'libraryUpdateProjectGlobal',
  'libraryUpdateProjectIncentive',
  'libraryUpdateRatePack',
  'libraryUpdateRatePackItem',
  'libraryUpdateTag',
  'commentsUpdate',
  'contactsUpdate',
  'projectsUpdate',
  'spacesUpdate',
  'purchaseOrdersUpdate',
  'purchaseOrdersUpdateItem',
  'transactionsUpdateItem',
  'transactionsUpdate',
  // ── keyed creates (receipt-backed; Idempotency-Key REQUIRED — D6) ──
  'budgetCreateLine',
  'budgetCreateLinesBulk',
  'budgetCreatePhase',
  'budgetUpdateLinePhaseDataBulk',
  'libraryCreateCurrency',
  'libraryCreateUnit',
  'libraryCreateFringeGroup',
  'libraryCreateFringe',
  'libraryCreateGlobal',
  'libraryCreateRatePack',
  'libraryCreateRatePackItem',
  'libraryCreateTag',
  'commentsCreate',
  'contactsCreate',
  'projectsCreate',
  'spacesCreate',
  'purchaseOrdersCreate',
  'purchaseOrdersCreateItem',
  'transactionsCreateBulk',
  'transactionsCreate',
  'transactionsCreateItem',
  // ── PO lifecycle transitions (Simon, 2026-08-07): status moves guarded by
  //    the routes' own lifecycle preconditions — a repeated call is rejected
  //    with a typed 4xx (or is a same-state no-op), never a duplicate ──
  'purchaseOrdersCancelSubmission',
  'purchaseOrdersMarkPaid',
  'purchaseOrdersVoid',
  'purchaseOrdersLinkTransaction',
  'purchaseOrdersUnlinkTransaction',
  // ── naturally idempotent creates (no key; repeat call returns the original) ──
  'documentsLink',
  'libraryAddProjectIncentive',
  'libraryAddRatePack',
  // ── library pack enables (Simon, 2026-08-02): enabling a pack the workspace
  //    may access is not authoring it; PUBLIC curated rows stay read-only via
  //    the routes' own scope rules ──
  'libraryEnableRatePack',
  'libraryEnableIncentivePack',
  // ── soft deletes. Classified `none`, NOT `natural`: a repeat delete hits
  //    the tombstoned row and returns 404 (webhooksDelete alone 204s twice),
  //    so "repeat returns the original record" would be a lie the model acts
  //    on. The public catalog publishes delete-specific retry wording. ──
  'transactionsDelete',
  'contactsDelete',
  'budgetDeleteLine',
  'budgetDeletePhase',
  'purchaseOrdersDelete',
  // ── full-surface ruling (2026-08-07): the rest of the write inventory ──
  'documentsDelete',
  'documentsUnlink',
  'libraryAddProjectCurrency',
  'libraryAddProjectFringe',
  'libraryAddProjectFringeGroup',
  'libraryAddProjectGlobal',
  'libraryDeleteCurrency',
  'libraryDeleteUnit',
  'libraryDeleteFringeGroup',
  'libraryDeleteFringe',
  'libraryDeleteGlobal',
  'libraryDeleteProjectCurrency',
  'libraryDeleteProjectFringe',
  'libraryDeleteProjectFringeGroup',
  'libraryDeleteProjectGlobal',
  'libraryDeleteProjectIncentive',
  'libraryDeleteRatePack',
  'libraryDeleteRatePackItem',
  'libraryDeleteTag',
  'libraryDisableIncentivePack',
  'libraryDisableRatePack',
  'libraryRemoveRatePack',
  'commentsDelete',
  'spacesDelete',
  'purchaseOrdersDeleteItem',
  'transactionsDeleteItem',
  'webhooksCreate',
  'webhooksDelete',
  'webhooksSendTestDelivery',
  'webhooksUpdate',
];
const AGENT_WRITE_EXPOSED_SET: ReadonlySet<string> = new Set(AGENT_WRITE_EXPOSED_OPS);

/**
 * POSTs whose retry identity is a durable receipt: the /v1 route REQUIRES the
 * `Idempotency-Key` header (400 without it), and the generated `<Op>Data` type
 * must declare it NON-OPTIONAL — the gate below parses `types.gen.ts` and
 * fails generation on drift in either direction.
 */
const KEYED_CREATE_OPS: ReadonlySet<string> = new Set([
  'budgetCreateLine',
  'budgetCreateLinesBulk',
  'budgetCreatePhase',
  'budgetUpdateLinePhaseDataBulk',
  'libraryCreateCurrency',
  'libraryCreateUnit',
  'libraryCreateFringeGroup',
  'libraryCreateFringe',
  'libraryCreateGlobal',
  'libraryCreateRatePack',
  'libraryCreateRatePackItem',
  'libraryCreateTag',
  'commentsCreate',
  'contactsCreate',
  'projectsCreate',
  'spacesCreate',
  'purchaseOrdersCreate',
  'purchaseOrdersCreateItem',
  'transactionsCreateBulk',
  'transactionsCreate',
  'transactionsCreateItem',
]);

/**
 * POSTs that are replay-equivalent WITHOUT a key, each with its mechanism —
 * a repeat call returns the ORIGINAL record, never a duplicate or a 409.
 */
const NATURALLY_IDEMPOTENT_OPS: Readonly<Record<string, string>> = {
  documentsLink: 'same-id FK set; the route has an explicit same-target no-op branch',
  libraryAddProjectIncentive: 'copy-on-use `@@unique([projectId, source])` — repeat add returns the existing link',
  libraryAddRatePack: 'copy-on-use `@@unique([projectId, ratePackId])` — repeat add returns the existing link',
  libraryEnableRatePack: 'upsert on `@@unique([workspaceId, ratePackId])` with deterministic id `wrp-<ws>-<pack>` — repeat enable returns the existing enablement',
  libraryEnableIncentivePack: 'upsert on `@@unique([workspaceId, incentivePackId])` with deterministic id `wip-<ws>-<pack>` — repeat enable returns the existing enablement',
  libraryAddProjectCurrency: 'copy-on-use add, idempotent on `@@unique([projectId, sourceId])` — repeat add returns the existing project copy',
  libraryAddProjectFringe: 'copy-on-use add, idempotent on `@@unique([projectId, sourceId])` — repeat add returns the existing project copy',
  libraryAddProjectFringeGroup: 'copy-on-use add, idempotent on `@@unique([projectId, sourceId])` — repeat add returns the existing project copy',
  libraryAddProjectGlobal: 'copy-on-use add, idempotent on `@@unique([projectId, sourceId])` — repeat add returns the existing project copy',
};

/**
 * PO lifecycle transitions (Simon, 2026-08-07): POSTs that move a purchase
 * order between states (or link/unlink its paid leg). Retry identity comes
 * from the route's status preconditions, not a key — a repeated transition is
 * rejected with a typed 4xx (or is a same-state no-op), never a duplicate.
 */
const TRANSITION_OPS: ReadonlySet<string> = new Set([
  'purchaseOrdersCancelSubmission',
  'purchaseOrdersMarkPaid',
  'purchaseOrdersVoid',
  'purchaseOrdersLinkTransaction',
  'purchaseOrdersUnlinkTransaction',
  // Guarded actions (full-surface ruling 2026-08-07): a repeat cannot
  // duplicate data — unassign of an unassigned doc is a typed miss; webhook
  // create 409s on a duplicate URL; ping re-sends a test event (no data row).
  'documentsUnlink',
  'webhooksCreate',
  'webhooksSendTestDelivery',
]);

interface ParsedOp {
  op: string;
  method: WriteMethod;
  url: string;
  dataType: string;
  summary: string;
}

/** Parse every operation block out of the generated `sdk.gen.ts`. */
function parseOperations(source: string): ParsedOp[] {
  const lines = source.split('\n');
  const ops: ParsedOp[] = [];

  // Matches: export const NAME = <ThrowOnError…>(options: Options<DATA, ThrowOnError>) => (options.client ?? client).METHOD<…>({
  const declRe =
    /^export const (\w+) = <ThrowOnError[^>]*>\(options: Options<(\w+), ThrowOnError>\) => \(options\.client \?\? client\)\.(get|post|put|patch|delete|head|options)</;
  const urlRe = /^\s*url: '([^']+)',/;

  for (let i = 0; i < lines.length; i++) {
    const m = declRe.exec(lines[i]!);
    if (!m) continue;
    const [, op, dataType, method] = m as unknown as [string, string, string, string];

    // The url is on one of the next few lines (after `security:`).
    let url = '';
    for (let j = i + 1; j < Math.min(i + 8, lines.length); j++) {
      const um = urlRe.exec(lines[j]!);
      if (um) {
        url = um[1]!;
        break;
      }
    }

    // The JSDoc summary is the first content line after the nearest `/**` above.
    let summary = '';
    for (let k = i - 1; k >= 0 && k > i - 30; k--) {
      const line = lines[k]!.trim();
      if (line.startsWith('export const')) break; // hit the previous op
      if (line === '*/') {
        // Walk up to the first ` * <text>` line inside this block.
        for (let s = k - 1; s >= 0; s--) {
          const inner = lines[s]!.trim();
          if (inner.startsWith('/**')) break;
          if (inner.startsWith('* ') && inner.length > 2) {
            summary = inner.slice(2).trim();
          }
        }
        break;
      }
    }

    ops.push({ op, method: method as WriteMethod, url, dataType, summary });
  }

  return ops;
}

/** Extract `{param}` path-parameter names from a templated url, in order. */
function pathParams(url: string): string[] {
  return [...url.matchAll(/\{(\w+)\}/g)].map((m) => m[1]!);
}

/**
 * Read the literal RHS block of `export type <name> = { … };` out of the
 * generated types, or `null` if `<name>` is not an object-type alias. The block
 * keeps brace depth so nested inline objects round-trip.
 */
function readTypeBlock(types: string, name: string): string | null {
  const start = new RegExp(`^export type ${name} = \\{`, 'm').exec(types);
  if (!start) return null;
  const from = start.index + start[0].length - 1; // position of the opening `{`
  let depth = 0;
  for (let i = from; i < types.length; i++) {
    const ch = types[i];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) return types.slice(from, i + 1);
    }
  }
  return null;
}

/**
 * Collapse a type block to a compact, comment-free, single-line field list the
 * model can read off the catalog (`{ field: Type; field2?: Type2; … }`). JSDoc
 * comment lines are stripped (the field NAMES + TYPES are the load-bearing part;
 * prose blows the discovery token budget); indentation is flattened.
 */
function compactTypeBlock(block: string): string {
  const out: string[] = [];
  for (const raw of block.split('\n')) {
    const line = raw.trim();
    if (line === '') continue;
    if (line.startsWith('/**') || line.startsWith('*') || line === '*/') continue;
    out.push(line);
  }
  return out.join(' ').replace(/\s+/g, ' ').trim();
}

/**
 * Resolve a named type to its object-literal block, following single-name alias
 * hops (`export type A = B;`) up to `maxHops` deep — hey-api routinely emits an
 * alias chain (e.g. `BudgetLinePhaseDataUpsert = BudgetLinePhaseDataWrite = { … }`)
 * whose object literal is several names removed. Returns `null` if no object
 * literal is reached (a union/primitive/cyclic alias).
 */
function objectBlockFor(types: string, name: string, maxHops = 4): string | null {
  let current = name;
  for (let hop = 0; hop < maxHops; hop++) {
    const block = readTypeBlock(types, current);
    if (block) return block;
    const alias = new RegExp(`^export type ${current} = (\\w+);`, 'm').exec(types);
    if (!alias) return null;
    current = alias[1]!;
  }
  return null;
}

/**
 * The model-facing body shape for an op: the real field types of `<Op>Data`'s
 * `body` member. We read the `body` member's type expression, then — when it is
 * a single named object alias (the hey-api norm, e.g. `body: ContactCreate`) —
 * resolve into that alias's compacted field list (following alias hops) so the
 * model reads actual fields, not just a type name. A bare `never`/primitive/union
 * is emitted verbatim. Never throws: a doc-generation miss degrades to the type
 * name, the typed `WriteSurface` contract (not this string) is the compile-time
 * guarantee.
 */
/**
 * The Money teaching string inlined wherever a body references the `Money`
 * alias (W-2, B0 finding: `{amount: 4750}` was accepted as $47.50 while the
 * model believed it wrote $4,750 — the minor-units JSDoc lives on the alias,
 * and compaction strips comments, so the catalog never taught it).
 */
const MONEY_INLINE =
  "{ amount: number (MINOR units - integer count of the smallest currency unit, e.g. cents: $4,750.00 USD = 475000, never major-unit dollars); currency: string (ISO-4217) }";

/**
 * Per-FIELD inline teachings for bare-number money fields the compaction
 * strips of unit semantics. The wire convention is ONE rule contract-wide
 * (Peter's 5846 review): integer MINOR units; routes own any storage-side
 * conversion. Teach it where the field is a bare number without the Money
 * envelope.
 */
const FIELD_INLINE_TEACHINGS: Readonly<Record<string, string>> = {
  appliedCreditCap:
    'appliedCreditCap?: number (integer MINOR units like all contract money - $1,500,000 = 150000000; whole-currency amounts only) | null (clears the cap)',
};

/** Union expansions stay readable: cap members and total width. */
const UNION_EXPAND_MAX_MEMBERS = 20;
const UNION_EXPAND_MAX_CHARS = 400;
/** Money-bearing object aliases expand inline (R6-F1); cap the width. */
const MONEY_OBJECT_EXPAND_MAX_CHARS = 700;

/**
 * Expand TEACHABLE aliases inline in a compacted body string (W-1, B0
 * finding: `type: TransactionJournalType; amount: Money` teaches neither the
 * enum members nor the Money shape, so models guess and the create never
 * lands). Two expansions, applied recursively over fresh names:
 *   - a string-literal union alias becomes its member list
 *     (`type: 'Invoice' | 'Cash' | …`);
 *   - `Money` becomes {@link MONEY_INLINE} with its minor-units semantics.
 * Named OBJECT aliases (e.g. nested item creates) are left as names — one
 * level of teaching, not a full schema dump.
 */
function expandTeachableAliases(types: string, text: string): string {
  const seen = new Set<string>();
  let out = text;
  for (const [field, teaching] of Object.entries(FIELD_INLINE_TEACHINGS)) {
    out = out.replace(
      new RegExp(`\\b${field}\\?: number \\| null`, 'g'),
      teaching,
    );
  }
  // Bounded passes: an expansion can reference nothing expandable, so 3 is plenty.
  for (let pass = 0; pass < 3; pass++) {
    const names = [...new Set(out.match(/\b[A-Z][A-Za-z0-9]{2,}\b/g) ?? [])].filter(
      (n) => !seen.has(n),
    );
    let changed = false;
    for (const name of names) {
      seen.add(name);
      if (name === 'Money') {
        out = out.replace(/\bMoney\b/g, MONEY_INLINE);
        changed = true;
        continue;
      }
      const union = new RegExp(
        `^export type ${name} = ('[^;]+');$`,
        'm',
      ).exec(types);
      if (!union) {
        // Money-bearing OBJECT aliases expand inline too (R6-F1: the PO
        // create's `items?: Array<PurchaseOrderItemWrite>` taught nothing, so
        // the model wrote major-unit dollars into `amount` and a $16,850 PO
        // committed as $168.50 - the same W-1 class, one hop further in).
        // Non-money object aliases stay as names: one level of teaching, not
        // a full schema dump.
        const objectBlock = objectBlockFor(types, name);
        if (!objectBlock || !/\bamount\??:/.test(objectBlock)) continue;
        let inline = compactTypeBlock(objectBlock);
        if (inline.length > MONEY_OBJECT_EXPAND_MAX_CHARS) continue;
        inline = inline.replace(
          /\bamount\?: number \| null/g,
          'amount?: number (integer MINOR units - $12,400.00 = 1240000, never major-unit dollars) | null',
        );
        out = out.replace(new RegExp(`\\b${name}\\b`, 'g'), inline);
        changed = true;
        continue;
      }
      const members = union[1]!;
      // Only pure string-literal unions, and only readable ones.
      if (!/^'[^']*'(?:\s*\|\s*'[^']*')*$/.test(members)) continue;
      if (members.length > UNION_EXPAND_MAX_CHARS) continue;
      if (members.split('|').length > UNION_EXPAND_MAX_MEMBERS) continue;
      out = out.replace(new RegExp(`\\b${name}\\b`, 'g'), members.replace(/\s+/g, ' '));
      changed = true;
    }
    if (!changed) break;
  }
  return out;
}

function bodyTypeText(types: string, dataType: string): string {
  const dataBlock = readTypeBlock(types, dataType);
  if (!dataBlock) return 'unknown';
  const bodyKey = /\bbody\??:\s*/.exec(dataBlock);
  if (!bodyKey) return 'never';
  const rest = dataBlock.slice(bodyKey.index + bodyKey[0].length);
  let expr: string;
  if (rest.startsWith('{')) {
    // INLINE-OBJECT body: the value spans inner `;`-separated members, so we
    // can't stop at the first `;` (that truncates the catalog string). Extract
    // the FULL brace-balanced block, then compact it like the named-alias path.
    let depth = 0;
    let end = -1;
    for (let i = 0; i < rest.length; i++) {
      const ch = rest[i];
      if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) {
          end = i + 1;
          break;
        }
      }
    }
    if (end === -1) return 'unknown';
    return expandTeachableAliases(types, compactTypeBlock(rest.slice(0, end)));
  }
  // A named alias / union / primitive ends at its member `;`.
  const semi = rest.indexOf(';');
  expr = (semi === -1 ? rest : rest.slice(0, semi)).trim();
  // Resolve a single named object alias (chasing alias hops); otherwise keep expr.
  if (/^[A-Z]\w*$/.test(expr)) {
    const named = objectBlockFor(types, expr);
    if (named) return expandTeachableAliases(types, compactTypeBlock(named));
  }
  return expandTeachableAliases(types, expr);
}

interface BodyContract {
  required: boolean;
  allowedFields: string[];
  requiredFields: string[];
}

/** Runtime-shape metadata derived at generation time from the same request type
 * that powers bodyType. Nested object members stay inside their parent segment;
 * the validator deliberately checks the top-level API envelope and leaves value
 * semantics to the real route validator at commit. */
function bodyContract(types: string, dataType: string): BodyContract {
  const dataBlock = readTypeBlock(types, dataType);
  if (!dataBlock) return { required: false, allowedFields: [], requiredFields: [] };
  const bodyKey = /\bbody(\?)?:\s*/.exec(dataBlock);
  if (!bodyKey) return { required: false, allowedFields: [], requiredFields: [] };
  const bodyType = bodyTypeText(types, dataType);
  if (!bodyType.startsWith('{')) {
    return { required: bodyKey[1] !== '?', allowedFields: [], requiredFields: [] };
  }

  const members: string[] = [];
  let start = 1;
  let depth = 1;
  for (let i = 1; i < bodyType.length - 1; i++) {
    const ch = bodyType[i];
    if (ch === '{' || ch === '[' || ch === '(' || ch === '<') depth++;
    else if (ch === '}' || ch === ']' || ch === ')' || ch === '>') depth--;
    else if (ch === ';' && depth === 1) {
      members.push(bodyType.slice(start, i).trim());
      start = i + 1;
    }
  }

  const parsed = members.flatMap((member) => {
    const match = /^([A-Za-z_$][\w$]*)(\?)?:/.exec(member);
    return match ? [{ name: match[1]!, optional: match[2] === '?' }] : [];
  });
  return {
    required: bodyKey[1] !== '?',
    allowedFields: parsed.map((field) => field.name),
    requiredFields: parsed.filter((field) => !field.optional).map((field) => field.name),
  };
}

/**
 * The response-type name for an op, derived purely from its request-data type:
 * hey-api emits a flattened singular `<Op>Response` (the unwrapped success body)
 * alongside `<Op>Data`, so `Data -> Response` is the deterministic transform.
 * No extra SDK parsing — every selected op is verified to have both at runtime.
 */
function responseType(dataType: string): string {
  return dataType.replace(/Data$/, 'Response');
}

/** The sorted, de-duped list of generated types both gen files import. */
function importedTypeNames(selected: ParsedOp[]): string[] {
  const names = new Set<string>();
  for (const o of selected) {
    names.add(o.dataType);
    names.add(responseType(o.dataType));
  }
  return [...names].sort();
}

/**
 * Emit the `WriteSurface` interface — the autogenerated CONTRACT. One typed
 * method per allowlisted op, `<op>(data: <Op>Data): Promise<<Op>Response>`.
 */
function emitInterface(selected: ParsedOp[]): string {
  const imports = importedTypeNames(selected)
    .map((n) => `  ${n},`)
    .join('\n');

  const methods = selected
    .map((o) => {
      const res = responseType(o.dataType);
      return `  /** ${o.summary.replace(/\*\//g, '* /')} (\`${o.method.toUpperCase()} ${o.url}\`). */
  ${o.op}(data: ${o.dataType}): Promise<${res}>;`;
    })
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// The \`mutate\` write surface CONTRACT: one typed method per allowlisted /v1
// write op, \`<op>(data: <Op>Data): Promise<<Op>Response>\`. Regenerate with:
//   pnpm generate:mutate
//
// This interface is the forcing function: when the OpenAPI document (and thus
// the generated \`types.gen.ts\` request/response types) changes, every
// \`satisfies WriteSurface\` implementation must update to match or fail \`tsc\`.
//
// ${selected.length} write operations.

import type {
${imports}
} from '../generated/types.gen.js';

/**
 * The typed write surface over the gated /v1 API. Each method takes the
 * generated hey-api options envelope (\`{ body, path, query, headers? }\`) for its
 * op and resolves the unwrapped success payload (the created/updated resource).
 */
export interface WriteSurface {
${methods}
}
`;
}

/**
 * Emit `createBridgeWriteSurface` — a `WriteSurface` whose every method forwards
 * its typed `{ path, body, query }` to the generic in-process dispatcher. This
 * is the interim, uniformly-typed implementation hosts compose with native ops.
 */
function emitBridge(selected: ParsedOp[]): string {
  const imports = importedTypeNames(selected)
    .map((n) => `  ${n},`)
    .join('\n');

  const methods = selected
    .map((o) => {
      const res = responseType(o.dataType);
      return `    ${o.op}(data: ${o.dataType}): Promise<${res}> {
      return forward('${o.op}', data) as Promise<${res}>;
    },`;
    })
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// \`createBridgeWriteSurface\` — the interim {@link WriteSurface} implementation:
// every op forwards its typed \`{ path, body, query }\` to the generic in-process
// dispatcher ({@link WriteBridge.mutate}, built with \`fetch: app.fetch\`), so the
// body still flows bearerAuth -> CASL -> \$transaction -> audit verbatim. Typing
// lives in each method's signature; the runtime is the generic gated bridge.
// Regenerate with: pnpm generate:mutate
//
// ${selected.length} write operations.

import type {
${imports}
} from '../generated/types.gen.js';
import type { WriteSurface } from './write-surface.interface.gen.js';

/** Per-op call arguments forwarded to the dispatcher. */
export interface WriteBridgeArgs {
  path?: Record<string, unknown>;
  body?: unknown;
  query?: Record<string, unknown>;
  /** Request headers (the \`Idempotency-Key\` channel for keyed creates). */
  headers?: Record<string, string>;
}

/**
 * The minimal generic dispatcher the bridge surface delegates to. A
 * {@link MutateClient} (built with \`fetch: app.fetch\`) satisfies it: its
 * \`mutate(op, args)\` runs the op through the gated /v1 chain in-process.
 */
export interface WriteBridge {
  mutate(op: string, args: WriteBridgeArgs): Promise<unknown>;
  /**
   * Optional meta-aware dispatch: also surfaces whether the /v1 route answered
   * from a stored idempotency receipt (\`Idempotency-Replayed: true\`). Hosts
   * that need replay-visible output (the MCP write adapter) call this;
   * \`MutateClient.mutateWithMeta\` satisfies it.
   */
  mutateWithMeta?(op: string, args: WriteBridgeArgs): Promise<{ data: unknown; replayed: boolean }>;
}

/** A generated hey-api options envelope (the \`<Op>Data\` request shape). */
type OptionsEnvelope = {
  path?: unknown;
  body?: unknown;
  query?: unknown;
  headers?: unknown;
};

/**
 * Build a {@link WriteSurface} whose every op forwards to the generic dispatcher.
 * Compose it with native per-op implementations and \`satisfies WriteSurface\` to
 * prove the whole contract is still covered:
 *
 *   const surface = {
 *     ...createBridgeWriteSurface(bridge),
 *     budgetUpdateLinePhaseData: nativeUpsert, // hand-written, type-checked
 *   } satisfies WriteSurface;
 */
export function createBridgeWriteSurface(bridge: WriteBridge): WriteSurface {
  const forward = (op: string, data: OptionsEnvelope): Promise<unknown> =>
    bridge.mutate(op, {
      ...(data.path !== undefined ? { path: data.path as Record<string, unknown> } : {}),
      ...(data.body !== undefined ? { body: data.body } : {}),
      ...(data.query !== undefined ? { query: data.query as Record<string, unknown> } : {}),
      ...(data.headers !== undefined ? { headers: data.headers as Record<string, string> } : {}),
    });

  return {
${methods}
  } satisfies WriteSurface;
}
`;
}

function main(): void {
  const source = readFileSync(SDK_GEN, 'utf8');
  const all = parseOperations(source);

  // Filter to the explicit allowlist; sort for a stable diff.
  const allowlisted = all.filter((o) => WRITE_OP_ALLOWLIST.has(o.op));
  const selected = allowlisted
    .filter((o) => AGENT_WRITE_EXPOSED_SET.has(o.op))
    .sort((a, b) => a.op.localeCompare(b.op));

  // The exposed list is the model-facing boundary: every entry must be a real
  // allowlisted op (a typo would silently shrink the surface), and both
  // idempotency sets must be subsets of it.
  const notAllowlisted = AGENT_WRITE_EXPOSED_OPS.filter((op) => !WRITE_OP_ALLOWLIST.has(op));
  if (notAllowlisted.length > 0) {
    throw new Error(
      `AGENT_WRITE_EXPOSED_OPS entries missing from WRITE_OP_ALLOWLIST: ${notAllowlisted.join(', ')}`,
    );
  }
  const strayIdempotency = [...KEYED_CREATE_OPS, ...Object.keys(NATURALLY_IDEMPOTENT_OPS)]
    .filter((op) => !AGENT_WRITE_EXPOSED_SET.has(op));
  if (strayIdempotency.length > 0) {
    throw new Error(
      `Idempotency-classified ops not in AGENT_WRITE_EXPOSED_OPS: ${strayIdempotency.join(', ')}`,
    );
  }
  const notGenerated = AGENT_WRITE_EXPOSED_OPS.filter((op) => !allowlisted.some((o) => o.op === op));
  if (notGenerated.length > 0) {
    throw new Error(
      `AGENT_WRITE_EXPOSED_OPS entries absent from the generated SDK: ${notGenerated.join(', ')}`,
    );
  }

  // Fail loud: every allowlisted op MUST resolve to a real generated operation,
  // and it must be a write verb. A typo'd allowlist entry is a generation bug.
  const found = new Set(allowlisted.map((o) => o.op));
  const missing = [...WRITE_OP_ALLOWLIST].filter((op) => !found.has(op));
  if (missing.length > 0) {
    throw new Error(
      `Allowlisted write ops absent from the generated SDK (typo or removed route): ${missing.join(', ')}`,
    );
  }
  // The surface is curated, and THE ALLOWLIST IS THE SECURITY BOUNDARY, so
  // its safety invariants are asserted HERE — next to the allowlist — not only in
  // next-api's integration test (a different package a `generate:mutate` run need
  // not execute). A regen that violates these throws before it can emit.
  //
  // (1) Every op must resolve to a write verb (post/put/patch) — reject GET and,
  //     defensively, any delete/head/options that slipped past the type.
  const WRITE_METHODS = new Set<string>(['post', 'put', 'patch', 'delete']);
  const nonWrite = selected.filter((o) => !WRITE_METHODS.has(o.method));
  if (nonWrite.length > 0) {
    throw new Error(
      `Allowlisted ops resolve to a non-write verb (only post/put/patch are additive): ${nonWrite
        .map((o) => `${o.op} [${o.method}]`)
        .join(', ')}`,
    );
  }
  // (2) No op whose NAME signals a destructive or lifecycle-mutating action may
  //     ship, even on a write verb — these are deferred to the rollback ledger.
  //     This is the authoritative source for the catalog guard mirrored in
  //     mutate.integration.test.ts (kept in sync).
  const DESTRUCTIVE_NAME =
    /Delete|Disable|Deactivate|Remove|Unassign|Unlink|Void|Ping|Submit|Finalize|MarkPaid|Cancel|Archive/;
  const REVIEWED_LIFECYCLE_OPS = new Set([
    // PO lifecycle + guarded actions admitted 2026-08-07 (Simon's
    // full-surface ruling). `purchaseOrdersSubmit` stays out: the /v1
    // endpoint is a reserved stub (always 409) until approval-run wiring.
    'purchaseOrdersCancelSubmission',
    'purchaseOrdersMarkPaid',
    'purchaseOrdersVoid',
    'purchaseOrdersUnlinkTransaction',
    'documentsUnlink',
    'webhooksSendTestDelivery',
  ]);
  // SOFT deletes: the five reviewed 2026-08-02 plus the remainder of the
  // delete inventory admitted by the 2026-08-07 full-surface ruling. Every
  // delete is soft behind its route's own lifecycle rules; a FUTURE delete
  // op still fails here until it is explicitly enumerated.
  const REVIEWED_SOFT_DELETE_OPS = new Set([
    'transactionsDelete',
    'contactsDelete',
    'budgetDeleteLine',
    'budgetDeletePhase',
    'purchaseOrdersDelete',
    'documentsDelete',
    'libraryDeleteCurrency',
    'libraryDeleteUnit',
    'libraryDeleteFringeGroup',
    'libraryDeleteFringe',
    'libraryDeleteGlobal',
    'libraryDeleteProjectCurrency',
    'libraryDeleteProjectFringe',
    'libraryDeleteProjectFringeGroup',
    'libraryDeleteProjectGlobal',
    'libraryDeleteProjectIncentive',
    'libraryDeleteRatePack',
    'libraryDeleteRatePackItem',
    'libraryDeleteTag',
    'libraryDisableIncentivePack',
    'libraryDisableRatePack',
    'libraryRemoveRatePack',
    'commentsDelete',
    'spacesDelete',
    'purchaseOrdersDeleteItem',
    'transactionsDeleteItem',
    'webhooksDelete',
  ]);
  const destructive = selected.filter((o) =>
    DESTRUCTIVE_NAME.test(o.op) && !REVIEWED_LIFECYCLE_OPS.has(o.op) && !REVIEWED_SOFT_DELETE_OPS.has(o.op));
  if (destructive.length > 0) {
    throw new Error(
      `Allowlisted ops have destructive/lifecycle names (additive-only surface — defer to the rollback ledger): ${destructive
        .map((o) => o.op)
        .join(', ')}`,
    );
  }
  // (3) A parse miss must never emit a malformed op with no path.
  const noUrl = selected.filter((o) => o.url === '');
  if (noUrl.length > 0) {
    throw new Error(
      `Allowlisted ops have no resolved url (parse miss): ${noUrl.map((o) => o.op).join(', ')}`,
    );
  }
  // (4) The typed contract assumes the hey-api `Data -> Response` pairing holds:
  //     every op's `<Op>Data` request type AND its flattened `<Op>Response`
  //     success type must exist in the generated types. A drift here would emit
  //     an interface referencing a missing type — fail loud at generation time.
  const types = readFileSync(TYPES_GEN, 'utf8');
  const typeExists = (name: string): boolean =>
    new RegExp(`^export type ${name}\\b`, 'm').test(types);
  const missingTypes = selected.flatMap((o) => {
    const gaps: string[] = [];
    if (!typeExists(o.dataType)) gaps.push(o.dataType);
    if (!typeExists(responseType(o.dataType))) gaps.push(responseType(o.dataType));
    return gaps;
  });
  if (missingTypes.length > 0) {
    throw new Error(
      `Allowlisted ops reference generated types absent from types.gen.ts ` +
        `(hey-api naming drift): ${missingTypes.join(', ')}`,
    );
  }

  // ── Idempotency-declaration gate (spec P2-14) ────────────────────────────
  // Ground truth is the GENERATED type: a keyed create's `<Op>Data.headers`
  // must declare `'Idempotency-Key': string` NON-OPTIONAL (the /v1 route 400s
  // without the header — an optional declaration would let generated clients
  // ship calls the server rejects). A naturally-idempotent create must NOT
  // require a key. Any exposed POST outside both sets is unclassified — fail.
  const headerDeclaration = (dataType: string): 'required' | 'optional' | 'absent' => {
    const block = new RegExp(
      `export type ${dataType} = \\{[\\s\\S]*?\\n\\};`, 'm',
    ).exec(types)?.[0];
    if (!block) return 'absent';
    const decl = /'Idempotency-Key'(\?)?:\s*string/.exec(block);
    if (!decl) return 'absent';
    return decl[1] === '?' ? 'optional' : 'required';
  };
  for (const o of selected) {
    if (o.method !== 'post') continue;
    const declared = headerDeclaration(o.dataType);
    if (KEYED_CREATE_OPS.has(o.op)) {
      if (declared !== 'required') {
        throw new Error(
          `Keyed create ${o.op}: the generated ${o.dataType} must declare a REQUIRED ` +
            `'Idempotency-Key' header (found: ${declared}). Fix the OpenAPI declaration and regenerate.`,
        );
      }
    } else if (o.op in NATURALLY_IDEMPOTENT_OPS) {
      if (declared === 'required') {
        throw new Error(
          `Naturally-idempotent op ${o.op} declares a REQUIRED Idempotency-Key — ` +
            `either reclassify it as a keyed create or fix the OpenAPI declaration.`,
        );
      }
    } else if (TRANSITION_OPS.has(o.op)) {
      if (declared === 'required') {
        throw new Error(
          `Transition op ${o.op} declares a REQUIRED Idempotency-Key — transitions ` +
            `take retry identity from the route's status preconditions, not a key.`,
        );
      }
    } else {
      throw new Error(
        `Exposed POST ${o.op} has no idempotency classification: add it to ` +
          `KEYED_CREATE_OPS (receipt-backed) or NATURALLY_IDEMPOTENT_OPS (with its mechanism).`,
      );
    }
  }

  const entries = selected
    .map((o) => {
      const params = pathParams(o.url);
      const summary = o.summary.replace(/'/g, "\\'");
      let bodyTypeStr = bodyTypeText(types, o.dataType);
      // PO item ops take the item shape as their whole body, so no alias name
      // survives for the money-alias expansion to teach (R6-F1). Teach the
      // amount is minor units everywhere on the contract. Quantity and rate
      // stay as the contract's raw number-or-formula strings.
      if (o.op === 'purchaseOrdersCreateItem' || o.op === 'purchaseOrdersUpdateItem') {
        bodyTypeStr = bodyTypeStr
          .replace(
            /\bamount\?: number \| null/g,
            'amount?: number (integer MINOR units - $12,400.00 = 1240000, never major-unit dollars) | null',
          );
      }
      const bodyType = JSON.stringify(bodyTypeStr);
      const contract = bodyContract(types, o.dataType);
      const idempotency = KEYED_CREATE_OPS.has(o.op)
        ? 'required'
        : o.op in NATURALLY_IDEMPOTENT_OPS
          ? 'natural'
          : TRANSITION_OPS.has(o.op)
            ? 'transition'
            : 'none';
      return `  ${o.op}: {
    op: '${o.op}',
    method: '${o.method}',
    url: '${o.url}',
    pathParams: [${params.map((p) => `'${p}'`).join(', ')}],
    dataType: '${o.dataType}',
    bodyType: ${bodyType},
    bodyRequired: ${contract.required},
    allowedBodyFields: ${JSON.stringify(contract.allowedFields)},
    requiredBodyFields: ${JSON.stringify(contract.requiredFields)},
    idempotency: '${idempotency}',
    summary: '${summary}',
  },`;
    })
    .join('\n');

  const out = `// AUTO-GENERATED by scripts/generate-write-surface.ts — DO NOT EDIT.
//
// The \`mutate\` write surface: an explicit allowlist over the generated /v1 SDK
// (CREATE + value-UPDATE, additive only). Regenerate with:
//   pnpm generate:mutate
//
// ${selected.length} write operations selected from ${all.length} total operations.

/** A single write operation's static metadata, derived from the OpenAPI spec. */
export interface WriteOpDef {
  /** The operation id — the \`mutate\` op key the model passes. */
  readonly op: string;
  /** HTTP verb the gated /v1 handler is reached through. */
  readonly method: 'post' | 'put' | 'patch' | 'delete';
  /** Templated path (\`{param}\` segments filled from \`path\`). */
  readonly url: string;
  /** Ordered path-parameter names this op requires (e.g. \`projectId\`, \`lineId\`). */
  readonly pathParams: readonly string[];
  /** The generated request-data type name (provenance; the body shape lives there). */
  readonly dataType: string;
  /**
   * The op's request \`body\` shape as a compact, model-readable field list
   * (\`{ field: Type; field2?: Type2; … }\`) resolved one level from \`<Op>Data\`.
   * This is what lets the model read REAL field types off the catalog instead of
   * a bare type name; the typed \`WriteSurface\` contract remains the compile-time
   * guarantee. \`never\` = no body; \`unknown\` = a doc-generation miss.
   */
  readonly bodyType: string;
  /** Whether the generated request envelope requires a JSON body. */
  readonly bodyRequired: boolean;
  /** Generated top-level body field allowlist used by side-effect-free preview validation. */
  readonly allowedBodyFields: readonly string[];
  /** Generated top-level body fields that must be present. */
  readonly requiredBodyFields: readonly string[];
  /**
   * Retry identity: \`required\` = the /v1 route requires an \`Idempotency-Key\`
   * header (receipt-backed replay); \`natural\` = replay-equivalent without a
   * key (repeat call returns the original record); \`transition\` = a lifecycle
   * move guarded by the route's status preconditions (a repeat is rejected
   * with a typed 4xx or is a same-state no-op, never a duplicate); \`none\` =
   * a value update (inherently retry-safe). Derived at generation time and
   * gate-checked against the generated header declarations.
   */
  readonly idempotency: 'required' | 'natural' | 'transition' | 'none';
  /** One-line human summary from the OpenAPI operation. */
  readonly summary: string;
}

/** The generated write-op table, keyed by operation id. */
export const WRITE_OPS = {
${entries}
} as const satisfies Record<string, WriteOpDef>;

/** Every allowlisted write operation id (the model-facing op vocabulary). */
export type WriteOp = keyof typeof WRITE_OPS;

/** The ordered list of write-op ids. */
export const WRITE_OP_IDS = Object.keys(WRITE_OPS) as WriteOp[];
`;

  writeFileSync(OUT, out, 'utf8');

  // The typed CONTRACT + its interim bridge implementation, both derived from the
  // SAME `selected` allowlist so they cannot drift from the metadata table or each
  // other. ResType is a pure `Data -> Response` transform of the captured dataType
  // (verified below: every selected op has both `<Op>Response` and the source
  // `<Op>Data` in the generated types), so no extra SDK parsing is needed.
  writeFileSync(OUT_INTERFACE, emitInterface(selected), 'utf8');
  writeFileSync(OUT_BRIDGE, emitBridge(selected), 'utf8');

  // eslint-disable-next-line no-console
  console.log(
    `[generate-write-surface] wrote ${selected.length} write ops to:\n` +
      `  ${OUT}\n  ${OUT_INTERFACE}\n  ${OUT_BRIDGE}`,
  );
}

main();
